### ISSUE TITLE
Type mismatch between Logger.level in log4js.d.ts and logger.js

### ISSUE THREAD

**Issue by pjone** [log4js-node/log4js-node#1010]
Type of `getLogger().level` shown by VS Code intellisense is `string`. But when I run it, I'm getting `Level` object.

It seems there is a mismatch between `Logger` class in log4js.d.ts and logger.js (please refer the attached image), or I'm missing something here.

![mismatch](https://user-images.githubusercontent.com/17271447/81914441-ee3dbd00-95ee-11ea-93f9-24b0ec451d41.png)

**Comment by rnd-debug** [comment]
@pjone Can you check if using a union type in `log4js.d.ts` will work properly ?
```
export class Logger {
...
	level: Level | string;
...
}
```
( using union type instead of simply `Level`, because log4js is using get/set accessors of different types for the Logger.level: getting a Level, but allowing to set from a Level or a String)
