### ISSUE TITLE
Pattern format and date docs

### ISSUE THREAD

**Issue by thernstig** [log4js-node/log4js-node#1012]
According to https://github.com/log4js-node/log4js-node/blob/master/docs/layouts.md#pattern-format the pattern options are:

> `%d` date, formatted - default is `ISO8601`, format options are: `ISO8601`, `ISO8601_WITH_TZ_OFFSET`, `ABSOLUTE`, `DATE`, or any string compatible with the [date-format](https://www.npmjs.com/package/date-format) library. e.g. `%d{DATE}`, `%d{yyyy/MM/dd-hh.mm.ss}`

These names do not correspond to what is seen in the link specified, see https://www.npmjs.com/package/date-format#formatting-dates-as-strings

I assume this could be because log4js uses an older version? In any sense, it is confusing for users as one cannot check the npm site for the options, as they aren't completely identical.

**Comment by peteriman** [comment]
https://github.com/log4js-node/log4js-node/blob/9fdbed5ad45d1b09b35c1ef5355ba726b60cb702/lib/layouts.js#L142-L159

There is a mapping from the String in `log4js` options to `date-format` library options.

|Reserved String|dateFormat Constant|Actual String|Output|
|-|-|-|-|
|"ISO8601"|`ISO8601_FORMAT`|"yyyy-MM-ddThh:mm:ss.SSS"|`2017-03-14T14:10:20.391` (local time used)|
|"ISO8601_WITH_TZ_OFFSET"|`ISO8601_WITH_TZ_OFFSET_FORMAT`|"yyyy-MM-ddThh:mm:ss.SSSO"|`2017-03-14T14:10:20.391+11:00` (local + TZ used)|
|"ABSOLUTE"|`ABSOLUTETIME_FORMAT`|"hh:mm:ss.SSS"|`14:10:20.391` (local time used)|
|"DATE"|`DATETIME_FORMAT`|"dd MM yyyy hh:mm:ss.SSS"|`14 03 2017 14:10:20.391` (local time used)|

**Comment by thernstig** [comment]
My intention was to check that if maybe `ABSOLUTE` should be renamed to `ABSOLUTETIME` and `DATE` to `DATETIME` to correspond 1-to-1 to what is in [date-format](https://www.npmjs.com/package/date-format). It is a minor thing really and possibly not worth it, since it is a breaking change. Or you could allow both e.g. `ABSOLUTE` and `ABSOLUTETIME` to map to `dateFormat.ABSOLUTETIME_FORMAT`. In any case it is not a big thing and maybe does not make sense, so it's possible this can be closed.

**Comment by peteriman** [comment]
That's a good suggestion to have both aliases so that the old one could be marked deprecated (so it's non-breaking) for future consistency.
