### ISSUE TITLE
Problem using webpack with dateFile Appender

### ISSUE THREAD

**Issue by chenqf6** [log4js-node/log4js-node#1017]
The "path" argument must be of type string. Received type undefined" in log4js@5.2.2

**Comment by rnd-debug** [comment]
@chenqf6 Looks similar to #1008 . Should be fixed in version 6.3.0 of log4js. Can you verify?

**Comment by techmunk** [comment]
This is also happening with the tcp appender when using webpack, and I think would also happen with the other core appenders that are not listed there, such as tcp-server, recording, multiprocess, multifile.

I was trying to work around this by using `import * as TCPAppender from 'log4js/lib/appenders/tcp'` and then setting type to `TCPAppender`, but I'm also using typescript, so now typescript complains about their being no declaration file there and having an implicit any. I know I can work around the implicit any problem. It'd be really nice not to have to though.

**Comment by peteriman** [comment]
* dateFileAppender (#1008) - fixed in `log4js@6.3.0`
* tcpAppender (#1028 ) - fixed in `log4js@6.4.0`

**Comment by peteriman** [comment]
Sorry, I mixed up fileAppender with dateFileAppender.
Re-opening this issue. Can you do a check with `log4js@6.4.0`?

**Comment by lamweili** [comment]
Closed due to extended period of inactivity.
