### ISSUE TITLE
How to disable console output from log4js when running unit tests

### ISSUE THREAD

**Issue by raphaelsoul** [log4js-node/log4js-node#1020]
as title described: How to disable console output from log4js when running unit tests?

**Comment by rnd-debug** [comment]
Hello. Can you be more specific? Unit tests of log4js? An example of messages you want to hide? Your own unit tests in which you are using log4js (with which log4js config)?

**Comment by raphaelsoul** [comment]
hi a created an example project to reproduce my issue @rnd-debug 
https://github.com/raphaelsoul/logj4s-reproduce

**Comment by raphaelsoul** [comment]
might calling `configure` to remove console appender or setting log level again in unit test work?

**Comment by rnd-debug** [comment]
@raphaelsoul Thank you for quick answer. You are right: doing something like this in the test (requestApp.js) should mute `log4js` completely.
```
const {getLogger} = require("log4js")
const logger = getLogger("http")
logger.level = 'off'
````
