### ISSUE TITLE
Layout type return undefined

### ISSUE THREAD

**Issue by snirad** [log4js-node/log4js-node#1021]
Hi, we have a path in our App where we would like to log specific data only when we access our api with keyword debug.
and so we created a logLevel debugInfo.

```javascript
log4js.addLayout('json', jsonLayout);
    log4js.addLayout('debugInfo', debugInfo);
    log4js.configure({
        levels: {
            debugInfo: {
                value: 10000, colour: 'green'
            }
        },
        appenders: {
            out: {
                type: 'stdout',
                layout: {type: 'json'}
            },
            debugLevel: {type: 'stdout', layout: {type: 'debugInfo'}},
            debugLogger: {type: 'logLevelFilter', appender: 'debugLevel', level: 'debugInfo'}

        },
        categories: {
            default: {
                appenders: ['out', 'debugLogger'],
                level: config.log4js.level,
                enableCallStack: ['DEBUG', 'TRACE'].includes(config.log4js.level)
            }
        }
    })
```
and if we want to log something with the debuginfo level we would do
logger.debuginfo("blabla bla") 

Now, Only want to print something using debugInfo if we pass certain parameter to the API
so I added in debugInfo Layout a check to see if this parameter was passed.
Problem is that when I dont return anything the logger just print undefined to the console.

How can I make it not print anything ?

**Comment by rnd-debug** [comment]
@snirad Hello. Maybe you can use a conditional configuration for log4js? Something like:
```
const defaultConfig = ... 
const configWhenAPIParam = ... // the custom config that you defined 
log4js.configure( API.param === 'something' ? configWhenAPIParam : defaultConfig);
```
