### ISSUE TITLE
How can I use multiple appenders?

### ISSUE THREAD

**Issue by daviddavid** [log4js-node/log4js-node#1024]
I'm trying to output log messages to different appenders based on their log level. To achieve this, I'm using one appender to output `error` messages to a file and a second appender to log everything to the console. However, no matter what I try, log4js is only using the "default" catergory and the appenders defined there.

For demonstration purposes, I set up [this runkit](https://runkit.com/daviddavid/5ed1808bd7e3300013347ff2) which is supposed to output `error` messages to `console.error` and everything to `console.log`.

```
log4js.configure({
  appenders: {
    err: { type: 'stderr' },
    console: { type: 'console' }
  },
  categories: {
    error: { appenders: ['err'], level: 'error' },
    default: { appenders: ['console'], level: 'trace' }
  }
});

var logger = log4js.getLogger();

logger.error('AAArgh! Something went wrong', { some: 'otherObject', useful_for: 'debug purposes' });
logger.info('This should appear as info output');
logger.log("Log doesn't even log the actual message");
```

However, as you can see, only the default category is ever evoked. What am I doing wrong and how do I get log4js to use a different appender based on the error log level? Possibly related to #973

Btw, is there a reason for the `log` level message to not even be logged?

**Comment by rnd-debug** [comment]
@daviddavid Hello. In order to use a specific category, you need to call `getLogger(CATEGORY_NAME)`. In your example:
```
var logger = log4js.getLogger('error');
logger.error('this is written to stderr');
logger.fatal('but this also go to stderr');
logger.trace('this is not written, because the level of category is set to error');
```
In order to achieve what you want (different log sinks according to different log levels), I think that you need to give a look to the [logLevelFilter](https://log4js-node.github.io/log4js-node/logLevelFilter.html) appender. See example:
```
log4js.configure({
  appenders: {
    everything: { type: 'console' },
    emergencies: { type: 'file', filename: 'panic-now.log' },
    errors: { type: 'logLevelFilter', appender: 'emergencies', level: 'error' }
  },
  categories: {
     myCat: { appenders: ['errors', 'everything' ], level: 'trace' },
    default: { appenders: [ 'everything' ], level: 'debug' }
  }
});

var logger = log4js.getLogger('myCat');
logger.fatal('goes to file and console');
logger.error('also goes to file and console' });
logger.debug('Only to console');
```

**Comment by rnd-debug** [comment]
Concerning the question about: `Logger.log()`: 
- the signature of the method is different. If you want to use it directly:
```logger.log('warn', 'this will be written as a message with log level WARN')```
- **log** is not a log level, so don't expect it to work as other log levels :wink:

**Comment by daviddavid** [comment]
Ohh, I didn't see the logLevelFilter in the docs. Thanks for the quick reply :)
