### ISSUE TITLE
Change timezone to UTC?

### ISSUE THREAD

**Issue by u05rav** [log4js-node/log4js-node#1025]
Is it possible to have the the timestamps in my logs be in UTC timezone rather than my local timezone?

**Comment by rnd-debug** [comment]
@u05rav Hello,
check custom [layouts and date-format](https://log4js-node.github.io/log4js-node/layouts.html).
For example:
```
console: { type: 'console', layout: {
          type: 'pattern',
          pattern: '%[[%x{myTime}] [%p] %c -%] %m',
          tokens: {
            myTime: function(logEvent) {
              return logEvent.startTime.toISOString();
}}}}
```

**Comment by ngohuytrieu** [comment]
Thank

> @u05rav Hello, check custom [layouts and date-format](https://log4js-node.github.io/log4js-node/layouts.html). For example:
> 
> ```js
> console: {
>   type: 'console',
>   layout: {
>     type: 'pattern',
>     pattern: '%[[%x{myTime}] [%p] %c -%] %m',
>     tokens: {
>       myTime: function(logEvent) {
>         return logEvent.startTime.toISOString();
>       }
>     }
>   }
> }
> ```

Thank you. You saved my day!
