### ISSUE TITLE
Why it keeps splitting log files?

### ISSUE THREAD

**Issue by foresthub** [log4js-node/log4js-node#1034]
Hello,

I hope it's ok to ask question here.
I'm using log4js to log the test results to files. I have four test files and each file will create its own log file. So that should be 4 log files total, but I'm getting 6 log files total. Somehow it only logs the first two lines into the log file, but the rest of the lines are copied to new log files.  my configuration in log4js.json may not be correct then.  Can someone help thanks?

file: log4js.json

```
{
    "appenders": {
        "test": {
            "type": "multiFile",
            "base": "testOutput/",
            "property": "categoryName",

            "flags": "w",
            "pattern": "yyyy-MM-dd-hh-mm-ss", 
            "compress": false,
            "alwaysIncludePattern": true,
            "extension": ".log",
            "keepFileExt": true
        }
    },
    "categories": {
        "default": {
            "appenders": ["test"],
            "level": "info"
        }
    }
}
```

file: log4jsConfig.js

```
const log4jsLogger = require('log4js');
log4jsLogger.configure("./helpers/logger/log4js.json");

let getLoggerHelper = function(){
    this.createLogFile = function(filename){
        return log4jsLogger.getLogger(filename);
    }
}

module.exports = new getLoggerHelper();
```

After that I have four test files that will import log4js to create log file.  So each file will create its own log file so that means there should be four log files.  But after protractor completing running the test files, I always get 10 logs file.  

Below it's from one of the 4 test files when it starts calling log4js and logging to the log file.

file: testCalculator.js

```
let calculator = require("../pages/superCal/calculator");
const log4jsConfig = require("../helpers/logger/log4jsConfig.js");

describe("Test Suite- Calculator", function(){
    var testLogger = log4jsConfig.createLogFile("logTestCalculator");
    testLogger.info("logTestCalculator is created");
    testLogger.info("testCalculator.js, describe() log to logTestCalculator");

    it("addition test", function(){
      testLogger.info("testCalculator.js, describe(), it(), launch URL");        
      calculator.get("http://juliemr.github.io/protractor-demo/");

      testLogger.info("testCalculator.js, describe(), it(), sending first value 2");       
      calculator.enterFirstNumber('2');

      browser.sleep(2000);

      testLogger.info("testCalculator.js, describe(), it(), sending second value 3");    
      calculator.enterSecondNumber('3');

      testLogger.info("testCalculator.js, describe(), it(), sending operand MULTIPLICATION");
      calculator.enterOperator("MULTIPLICATION");

      browser.sleep(2000);

      testLogger.info("testCalculator.js, describe(), it(), sending click on Go! button");    
      calculator.clickingGo();
  
    
      testLogger.info("testCalculator.js, describe(), it(), verify result");    
      expect("6").toEqual(calculator.getResult("6").getText());
      browser.sleep(2000);
  });
});
```

file: calculator.js

```
const log4jsConfig = require("../../helpers/logger/log4jsConfig.js");
    
let homepage = function(){
    var testLogger = log4jsConfig.createLogFile("logCalculator");
    testLogger.info("logCalculator is created");
    testLogger.info("calculator.js, describe() log to logCalculator");

    this.myConsoleLog = function(){
        console.log("at myConsoleLog()");
    };

    this.get = function(url){
        testLogger.info("calculator.js, get");
        browser.get(url);
        browser.sleep(3000);
    };

    this.enterFirstNumber = function(value1){
        testLogger.info("calculator.js, enterFirstNumber");
        element(by.model("first")).sendKeys(value1);
    };

    this.enterSecondNumber = function(value2){
        testLogger.info("calculator.js, enterSecondNumber");
         element(by.model("second")).sendKeys(value2);
    };

    this.enterOperator = function(oper){
        testLogger.info("calculator.js, enterOperator");
        element(by.model("operator")).$('[value='+ oper).click();
    };

    this.clickingGo = function(){
       testLogger.info("calculator.js, clickingGo");
        element(by.css('[ng-click="doAddition()"]')).click();
    };

    this.getResult = function(result){
        testLogger.info("calculator.js, getResult");
        var retVal = element(by.cssContainingText(".ng-binding", result));
        return retVal;
    };    
};

module.exports = new homepage();
```

And here is where log4js logs to different log files.  It starts logging the first two lines then somehow for the rest of test execution, it gets logged to new log file.
For an example, these two log files that got split:
"**logCalculator.2020-07-29-12-34-19.log**"
"**logCalculator.2020-07-29-12-34-25.log**"

this log file "logCalculator.2020-07-29-12-34-19.log", has:
```
[2020-07-29T12:34:19.687] [INFO] logCalculator - logCalculator is created
[2020-07-29T12:34:19.688] [INFO] logCalculator - calculator.js, describe() log to logCalculator
```

this log file "logCalculator.2020-07-29-12-34-25.log", has:
```
[2020-07-29T12:34:25.843] [INFO] logCalculator - calculator.js, get
[2020-07-29T12:34:25.846] [INFO] logCalculator - calculator.js, enterFirstNumber
[2020-07-29T12:34:25.848] [INFO] logCalculator - calculator.js, enterSecondNumber
[2020-07-29T12:34:25.849] [INFO] logCalculator - calculator.js, enterOperator
[2020-07-29T12:34:25.850] [INFO] logCalculator - calculator.js, clickingGo
[2020-07-29T12:34:25.850] [INFO] logCalculator - calculator.js, getResult
```

**Comment by nomiddlename** [comment]
I think the problem is because you're specifying `pattern` in your multiFile configuration. The pattern you're using rotates files based on the time, in this case splitting files every second.

**Comment by rosethub** [comment]
> I think the problem is because you're specifying `pattern` in your multiFile configuration. The pattern you're using rotates files based on the time, in this case splitting files every second.

Oh wow! thank you so much.  I thought that pattern is for appending date and time to the log file name because i don't want the log file to overwrite old logs if the test executed it again.  Not sure if this will work, but I will pass the date as parameter to createLogFile();
`var testLogger = log4jsConfig.createLogFile("logTestCalculator" +  dateTime);`

Again thank you so much for the solution.

**Comment by foresthub** [comment]
Oh wow! thank you so much. I thought that pattern is for appending date and time to the log file name because i don't want the log file to overwrite old logs if the test executed it again. Not sure if this will work, but I will pass the date as parameter to createLogFile();

`var testLogger = log4jsConfig.createLogFile("logTestCalculator" + dateTime);`

Again thank you so much for the solution.
