### ISSUE TITLE
dateFile  Appender  daysToKeep  not rolling by days

### ISSUE THREAD

**Issue by wangduanduan** [log4js-node/log4js-node#1035]
> daysToKeep - integer (default 0) - if this value is greater than zero, then files older than that many ***days*** will be deleted during log rolling.

when the pattern is not `.yyyy-MM-dd`, the daysToKeep not work as doc says.

for example. when pattern is `.yyyy-MM-dd-hh-mm`,  the daysToKeep is not control the old log Rolling by days, just keep the logs backups  not more than daysToKeep.

```
log4js.configure({
    appenders: {
      well: {
        type: 'dateFile',
        filename: logFileName,
        pattern: '.yyyy-MM-dd-hh-mm',
        compress: true,
        daysToKeep: 3
      },
      console: { type: 'console' }
    },
    categories: {
      well: { appenders: [ 'well' ], level: 'debug'},
      default: {appenders: ['console'], level: 'debug'}
    }
})
```

log files

```
-rw-r--r--  1 dd  staff   855B Aug  1 14:59 well.log
-rw-r--r--  1 dd  staff   197B Aug  1 14:39 well.log.2020-08-01-14-38.gz
-rw-r--r--  1 dd  staff   323B Aug  1 14:45 well.log.2020-08-01-14-39.gz
-rw-r--r--  1 dd  staff   140B Aug  1 14:59 well.log.2020-08-01-14-45.gz
```

**Comment by beita1** [comment]
I also found this issue, do you have some new progress?

**Comment by peteriman** [comment]
Related to #1080.

**Comment by beita1** [comment]
已收到，谢谢

**Comment by LmonZero** [comment]
I want to split it both by day and by size, and I should

**Comment by lamweili** [comment]
@LmonZero

> I want to split it both by day and by size, and I should

Yes, you can. And it is either through file Appender or dateFile Appender.

> ### File Appender
> Note that, from version 4.x of log4js onwards, the file appender can take any of the options for the [dateFile appender](https://log4js-node.github.io/log4js-node/dateFile.html) as well. So you could roll files by both date and size.  
_(source: https://log4js-node.github.io/log4js-node/file.html)_

```js
const log4js = require("log4js");
log4js.configure({
  appenders: {
    everything: {
      type: "file",
      filename: "testFile.log",
      pattern: "yyyy-MM-dd-hh",
      maxLogSize: 20
    },
  },
  categories: {
    default: { appenders: ["everything"], level: "debug" },
  },
});
const logger = log4js.getLogger();
logger.debug("hello world");
```

> ### DateFile Appender
> Note that, from version 4.x of log4js onwards, the file appender can take any of the options for the [file appender](https://log4js-node.github.io/log4js-node/file.html) as well. So you could roll files by both date and size.
> _(source: https://log4js-node.github.io/log4js-node/dateFile.html)_

```js
const log4js = require("log4js");
log4js.configure({
  appenders: {
    everything: {
      type: "dateFile",
      filename: "testDateFile.log",
      pattern: "yyyy-MM-dd-hh",
      maxLogSize: 20
    },
  },
  categories: {
    default: { appenders: ["everything"], level: "debug" },
  },
});
var logger = log4js.getLogger();
logger.debug("hello world");
```

**Comment by lamweili** [comment]
@LmonZero Does it resolve for you?

**Comment by LmonZero** [comment]
yes
