### ISSUE TITLE
log4js internal debug messages

### ISSUE THREAD

**Issue by kirkpensalvo** [log4js-node/log4js-node#1040]
I'm currently getting the log4js internal debug messages, for example:

log4js:configuration Calling pre-processing listeners (1) +1ms
  log4js:configuration Configuration pre-processing finished. +0ms
  log4js:configuration Calling configuration listeners (8) +0ms
...

I assume this is a configuration setting somewhere, but I've looked everywhere and searching is near impossible without getting results for using log4js. Can anyone help me turn these off?

**Comment by rnd-debug** [comment]
@kirkpensalvo [debug](https://www.npmjs.com/package/debug) is probably globally enabled somewhere in your code. Check their docs (in particular for `debug.disable()` and `debug.enable(modules where you want to use debug)`):
https://github.com/visionmedia/debug#set-dynamically

**Comment by kirkpensalvo** [comment]
Thanks @rnd-debug but no joy. I'm not using debug directly and even when I include and call disable, I'm still getting debug messages. Interesting that only log4js-node produces the messages.

**Comment by rnd-debug** [comment]
@kirkpensalvo Sorry, cannot reproduce. More precisions (used config, log4js version), ideally a small example would be appreciated.

**Comment by kirkpensalvo** [comment]
LOL. If I could find you configs or a sample I could probably fix it. Doesn't happen in deployed code, so it is some config setting local to my machine. Version 6.3.0 of log4js btw.

**Comment by nomiddlename** [comment]
@kirkpensalvo check your environment variables as well - from memory debug looks for "DEBUG" in your env.

**Comment by kirkpensalvo** [comment]
@nomiddlename Yes, I suspect that's the issue, was hoping for more details. For instance, my env has the following: DEBUG=*,-babel*,-*:debug,-*:*:debug,-*:*:*:debug,-*:*:*:*:debug,-*:*:*:*:*:debug

Which of those is causing the issue?

**Comment by nomiddlename** [comment]
Beats me. Try adding `,-log4js:*` to the end of your DEBUG env var. That should turn off the log4js messages specifically. Alternatively, since it looks like your env var is just excluding debug messages remove the whole thing to turn it all off.

**Comment by kirkpensalvo** [comment]
@nomiddlename OK, so unsetting DEBUG gets rid of the internal debug messages. Still don't know what set it or which value was being used, but know what to look for now. Thanks for your input!
