### ISSUE TITLE
layout  time format

### ISSUE THREAD

**Issue by junbao520** [log4js-node/log4js-node#1048]
Do you support formatted output UTC time?
for example now 2020:9:24 9:53:10  I want to outpu 2020:9:24 1:53:10 ，but i dot know how to config  layout

  pattern: 'level=%p ts=%d{yyyy-MM-ddThh:mm:ss.SSSZ} module=%c host=%h %m'

**Comment by rnd-debug** [comment]
@junbao520 Check custom layouts [here](https://log4js-node.github.io/log4js-node/layouts.html). In particular:`pattern` and `tokens`.
```
const log4js = require("log4js");
log4js.configure({
  appenders: { out: { type: 'console', layout: {
      type: 'pattern',
      pattern: '%d{yyyy:MM:dd hh:mm:ss} OR %x{customDate} %m',
      tokens: {
        customDate: function(logEvent) {
          // modify as you want the timestamp for example getting it in the local time zone
          return logEvent.startTime.toLocaleString();
        }
      }
    }}},
  categories: { default: { appenders: ["out"], level: "trace" } }
});
const logger = log4js.getLogger("out");
logger.trace("my message");                       // 2020:09:27 05:13:08 OR 9/27/2020, 5:13:08 AM my message

```

**Comment by junbao520** [comment]
thank you very much ! I get it
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rnd-debug"<notifications@github.com&gt;; 
发送时间: 2020年9月27日(星期天) 下午3:15
收件人: "log4js-node/log4js-node"<log4js-node@noreply.github.com&gt;; 
抄送: "等待。情缘"<757114760@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [log4js-node/log4js-node] layout  time format (#1048)





 
@junbao520 Check custom layouts here. In particular:pattern and tokens.
 const log4js = require("log4js"); log4js.configure({   appenders: { out: { type: 'console', layout: {       type: 'pattern',       pattern: '%d{yyyy:MM:dd hh:mm:ss} OR %x{customDate} %m',       tokens: {         customDate: function(logEvent) {           // modify as you want the timestamp for example getting it in the local time zone           return logEvent.startTime.toLocaleString();         }       }     }}},   categories: { default: { appenders: ["out"], level: "trace" } } }); const logger = log4js.getLogger("out"); logger.trace("my message");                       // 2020:09:27 05:13:08 OR 9/27/2020, 5:13:08 AM my message
