### ISSUE TITLE
Module not found: Error: Can't resolve 'cluster'

### ISSUE THREAD

**Issue by AsteriskZuo** [log4js-node/log4js-node#1050]
ref: https://github.com/log4js-node/log4js-node/issues/920

I confirm the above question, but it still exists.
I use Typescript in VUE: 
`yarn add log4js`  // add depend plugin
`yarn serve` // build demo project
tip: 
```
 WARNING  Compiled with 2 warnings                                                                                                                                                                                              2:15:09 PM  
 warning  in ./node_modules/log4js/lib/appenders/index.js  
Critical dependency: the request of a dependency is an expression  
 warning  in ./node_modules/log4js/lib/clustering.js  
Module not found: Error: Can't resolve 'cluster' in '/.../node_modules/log4js/lib'  
```

I try to modify the clustering.js source code.
```
//try {  
  //cluster = require("cluster"); //eslint-disable-line  
//} catch (e) {  
  debug("cluster module not present");  
  disabled = true;  
//}  
```
So the compile will not report an error. But there are other problems.
Cluster is the product of 2011, can you not use it? It is 2020, you are too lazy.

**Comment by nikita-karatun** [comment]
Stumbled upon the same problem with Ionic 5.0.0 and Angular 10.0.0.

**Comment by SnowZhang0215** [comment]
`WARNING`  Compiled with 2 warnings                                                                                                               下午1:07:17

 warning  in ./node_modules/log4js/lib/appenders/index.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/log4js/lib/clustering.js

Module not found: Error: Can't resolve 'cluster' in '/myapp/node_modules/log4js/lib'`

I have the same problem,and my app can not work

**Comment by Ken-Scofield** [comment]
how to resolve this problem?

**Comment by peteriman** [comment]
Wait a second. This is a warning, not an error.
Does it still produce a bundle?

**Comment by peteriman** [comment]
See https://github.com/log4js-node/log4js-node/issues/1069#issuecomment-1030761383 and https://github.com/log4js-node/log4js-node/issues/1265#issuecomment-1141379770

**Comment by lamweili** [comment]
Closed due to extended period of inactivity.
