### ISSUE TITLE
There is a way to write in multiple files with different level?

### ISSUE THREAD

**Issue by Turiddru** [log4js-node/log4js-node#1064]
Hi!
I'm trying to write my logs in different files with different log levels.

Here is my config file:
{
    "appenders": {
        "fileErrors": { "type": "file", "filename": "log/errors.log", "maxLogSize": 5242880, "backups": 20  },
        "fileMain": { "type": "file", "filename": "log/main.log", "maxLogSize": 5242880, "backups": 20 }
    },
    "categories": {
        "default": {
                    "appenders": ["fileMain"],
                    "level": "DEBUG",
                    "enableCallStack": true
                },
        "error": {
                    "appenders": ["fileErrors"],
                    "level": "WARN"
                }
    }
}

var logger = log4js.getLogger(); //this is using the default category, but I want to log to ALL categories
logger.debug('debug log');
logger.error('error log');

I want to write error messages to errors.log and all messages to main.log.
Is it possible? How can I achieve this?

Thanks.

**Comment by peteriman** [comment]
You can use the [logLevelFilter](https://log4js-node.github.io/log4js-node/logLevelFilter.html).

```javascript
const log4js = require('log4js');

log4js.configure({
  appenders: {
    fileMain: { type: 'file', filename: 'main.log' },
    fileErrors: { type: 'file', filename: 'errors.log' },
    errorFilter: { type: 'logLevelFilter', appender: 'fileErrors', level: 'error' }
  },
  categories: {
    default: { appenders: ['errorFilter', 'fileMain' ], level: 'debug' }
  }
});

const logger = log4js.getLogger();
logger.info('info test');
logger.error('error test');
logger.warn('warn test');
```
