### ISSUE TITLE
No appenders could be found for logger (org.jboss.logging). Please initialize the log4j system properly.

### ISSUE THREAD

**Issue by munchkindev** [log4js-node/log4js-node#1065]
Getting the following warning each time I start the backend:
```
 [ERROR] default - log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
I've configured the appenders like the following in my Node.js Backend:
```
log4js.configure({
  appenders: { fileAppender: { type: 'file', filename: './logs/logfile.log', }, console: { type: 'console' }, network: { type: 'tcp', host: '10.0.0.1', port: '10000' }, layout: {type: 'pattern', pattern: '%n'} },
  categories: { default: { appenders: environment.logger, level: 'info' } }
});
```

What did I do wrong?

**Comment by peteriman** [comment]
From your logs, the backend is a Java JAR file, and not Node.js.
log4j is a Java logging framework. It is probably because `log4j.xml` or `log4j.properties` is not present.

log4`j` and log4`js` are two different things.

It has got nothing to do with log4js nor Node.js in this case.
