### ISSUE TITLE
Various fs related errors from graceful-fs

### ISSUE THREAD

**Issue by udithishara** [log4js-node/log4js-node#1069]
I'm trying to get log4js working with Nuxt, after installing and spinning up dev environment, getting below error

```
ERROR in ./node_modules/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in '/home/USER/APP_NAME/node_modules/graceful-fs'
ERROR in ./node_modules/log4js/lib/log4js.js
Module not found: Error: Can't resolve 'fs' in '/home/USER/APP_NAME/node_modules/log4js/lib'
ERROR in ./node_modules/log4js/lib/appenders/fileSync.js
Module not found: Error: Can't resolve 'fs' in '/home/USER/APP_NAME/node_modules/log4js/lib/appenders'
ERROR in ./node_modules/streamroller/node_modules/fs-extra/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/home/USER/APP_NAME/node_modules/streamroller/node_modules/fs-extra/lib'
ERROR in ./node_modules/streamroller/node_modules/jsonfile/index.js
Module not found: Error: Can't resolve 'fs' in '/home/USER/APP_NAME/node_modules/streamroller/node_modules/jsonfile'
```

**Comment by Ken-Scofield** [comment]
l try used " extend(config,{isDev,isServer}){config.fs = 'empty'}" in  nuxt.config.js build property, but get other warning.

**Comment by peteriman** [comment]
[fs](https://nodejs.org/api/fs.html) is Node.js native file-system handler.
I'm not so sure how can you import that into Nuxt.

**Comment by peteriman** [comment]
[fs](https://nodejs.org/api/fs.html) is Node.js native file-system handler.

I'm not so sure how can you import that into Nuxt. 
I don't think you can use it on client-side.

Perhaps, you should be looking at https://github.com/stritti/log4js instead.

**Comment by peteriman** [comment]
I'm not sure if this would help, but worth a try.

### nuxt.config.js
```diff
    build: {
      extend (config, { isDev, isClient }) {
+       config.node: {
+         fs: 'empty'
+       }
      }
    }
```

_(src: https://nuxtjs.org/docs/features/configuration/#extend-webpack-config)_
_(src: https://nuxtjs.org/docs/configuration-glossary/configuration-build/#extend)_
_(src: https://v4.webpack.js.org/configuration/node/#other-node-core-libraries)_

**Comment by peteriman** [comment]
@udithishara, does the above comment resolve your issue?

**Comment by peteriman** [comment]
@udithishara @Ken-Scofield 

Does the above comment resolve your issue?

**Comment by lamweili** [comment]
Closed due to extended period of inactivity.
