### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by npomfret** [log4js-node/log4js-node#1073]
I see in the [docs](https://log4js-node.github.io/log4js-node/file.html) that when streaming to a file, we can get events to tell us to stop/start because the in-memory buffer is full.

is it possible to increase the size of that buffer?

**Comment by peteriman** [comment]
You should be able to specify the size of that buffer using `highWaterMark`. 
Give it a try and close this issue if it resolves for you.

> - `highWaterMark` [<number>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type) Buffer level when [stream.write()](https://nodejs.org/docs/latest/api/stream.html#writablewritechunk-encoding-callback) starts returning `false`. Default: `16384` (16 KB)  
>

The docs (for [file](https://log4js-node.github.io/log4js-node/file.html) and [dateFile](https://log4js-node.github.io/log4js-node/dateFile.html)) mentioned that any other configuration parameters will be passed to the underlying [streamroller](https://github.com/nomiddlename/streamroller) implementation (see also [node.js core file streams](https://nodejs.org/docs/latest/api/stream.html#implementing-a-writable-stream)). 

---

From the test cases:

https://github.com/log4js-node/log4js-node/blob/7a16cfbef16937d043f7657e5ab61de6f56a494a/test/tap/pause-test.js#L18-L26

https://github.com/log4js-node/log4js-node/blob/7a16cfbef16937d043f7657e5ab61de6f56a494a/test/tap/pause-test.js#L53-L61

**Comment by peteriman** [comment]
@npomfret, have you tried?

**Comment by peteriman** [comment]
@npomfret, have you tried?
