### ISSUE TITLE
Error: EACCES: permission denied when use nodemon

### ISSUE THREAD

**Issue by noharajokerz** [log4js-node/log4js-node#1077]
I use Log4Js write log 2 place ie. console and file . I try create Utility file for some function call. I  setting like 

```
log4js.addLayout('oneline', function(config) {
           //... setting layout
  });

log4js.configure({
    appenders: { 
        console: { 
            type: 'stdout',
            layout: { type: 'oneline'} 
        },
        wlog: { 
            type: 'dateFile',
            filename: 'log/application.log',
            pattern: '.yyyy-MM-dd',
            layout: { type: 'oneline'},
            mode: 777,
            compress: true,
            alwaysIncludePattern: true,
            daysToKeep: 2,
            keepFileExt: true
        }
    },
    categories: { default: { appenders: [ 'console','wlog' ], level: 'info' } }
  });


let logger = (categoryName) =>{
    let logger = log4js.getLogger(categoryName); 
}
```

While I develop my API I use nodemon for support my comfortable. **Anyway If i edit another file and save of course !! nodemon will re-run. But there is Error shown like** 

```
Error: EACCES: permission denied, open 'log/application.2021-05-09.log'
Emitted 'error' event on DateRollingFileStream instance at:
    at WriteStream.<anonymous> (xxxxxx/node_modules/streamroller/lib/RollingFileWriteStream.js:237:12)
```

Are there some advice for solve my problem ? 

Thank you and Best regards.

**Comment by tsvico** [comment]
> The leading zero in the mode argument is very important. It's an octal number, not decimal - use not just , or even better use . See the node.js file modes docs for more details.`0644` `644` `0o644`

https://github.com/log4js-node/log4js-node/issues/893#issuecomment-501043156

**Comment by peteriman** [comment]
As @tsvico has mentioned, @noharajokerz is missing a leading zero in the mode configuration.

Since @noharajokerz has provided `777`, please use octal `0777` or `0o777` or use decimal `511` instead.

**Comment by noharajokerz** [comment]
Thank for helpful answer.
