### ISSUE TITLE
Doesn't work with React-Native. Is it possible to fix that?

### ISSUE THREAD

**Issue by casmeiron** [log4js-node/log4js-node#1087]
Hi,

I'm coming from JAVA and I love log4j library so it was very nice to see this 'port' to nodejs. Unfortunately it seems it doesnt work for react-native, problem with dependencies like *fs*, *path*, etc.

Do you guys have any plan to support react-native?

Thanks!

**Comment by lamweili** [comment]
Closed due to extended period of inactivity.
