### ISSUE TITLE
What does level 'MARK' mean?

### ISSUE THREAD

**Issue by CBW2007** [log4js-node/log4js-node#1092]
The weight value of level 'mark' is much bigger than any other levels'.So what does the meaning of it?Is it just a level for 
very important information?

**Comment by peteriman** [comment]
MARK is higher than FATAL.

> ALL < TRACE < DEBUG < INFO < WARN < ERROR < FATAL < MARK < OFF - note that OFF is intended to be used to turn off logging, not as a level for actual logging, i.e. you would never call logger.off('some log message'))

source: https://log4js-node.github.io/log4js-node/api.html
