### ISSUE TITLE
Couldn't change the timezone

### ISSUE THREAD

**Issue by brontosentinel** [log4js-node/log4js-node#1093]
I was trying to change the timezone of the logs. Our server is in different country, so we don't need local time. 
I tried date pattern. Even tried solution from issue #1025 
Nothing works for me. Someone please guide me on this issue.
Thanks in advance.

**Comment by peteriman** [comment]
There are 2 solutions, both using [Layouts -> Pattern format](https://log4js-node.github.io/log4js-node/layouts.html):
1. to use [date-format](https://github.com/nomiddlename/date-format) library formatting which will always show local time.
You can configure it to show local time with timezone for clarity.
    > **%d** date, formatted - default is **ISO8601**, format options are: 
    > **ISO8601**, **ISO8601_WITH_TZ_OFFSET**, **ABSOLUTE, DATE**, 
    > or any string compatible with the [date-format](https://github.com/nomiddlename/date-format) library. e.g. **%d{DATE}**, **%d{yyyy/MM/dd-hh.mm.ss}**

2. to use tokens to manually override
    > **%x{\<tokenname\>}** add dynamic tokens to your log. Tokens are specified in the tokens parameter.

```javascript
const log4js = require('log4js');
log4js.configure({
  appenders: { 
    defaultAppender: { 
      type: 'stdout', 
      layout: { 
        type: 'basic'                                        // default format
      } 
    },
    dateformatAppender: {
      type: 'stdout', 
      layout: { 
        type: 'pattern', 
        pattern: "[%d{ISO8601_WITH_TZ_OFFSET}] [%p] %c - %m" // using date-format local time with timezone
      } 
    },
    tokenAppender: { 
      type: 'stdout', 
      layout: { 
        type: 'pattern',
        pattern: '[%x{myTime}] [%p] %c - %m',                // using tokens
        tokens: {
          myTime: function(logEvent) {
            return logEvent.startTime.toISOString();
          }
        }
      }
    }
  },
  categories: { 
   default: { appenders: ['defaultAppender'], level: 'trace' },
   dateformat: { appenders: ['dateformatAppender'], level: 'trace' },
   token: { appenders: ['tokenAppender'], level: 'trace' }
  }
});

const defaultLogger = log4js.getLogger('default');
const dateFormatLogger = log4js.getLogger('dateformat');
const tokenLogger = log4js.getLogger('token');

defaultLogger.debug('Cheese is too ripe!');
// [2022-01-16T02:48:15.122] [DEBUG] default - Cheese is too ripe!

dateFormatLogger.debug('Cheese is too ripe!');
// [2022-01-16T02:48:15.124+0800] [DEBUG] dateformat - Cheese is too ripe!

tokenLogger.debug('Cheese is too ripe!');
// [2022-01-15T18:48:15.126Z] [DEBUG] token - Cheese is too ripe!
```

**Comment by peteriman** [comment]
@brontosentinel There are 2 solutions, both using [Layouts -> Pattern format](https://log4js-node.github.io/log4js-node/layouts.html):
1. to use [date-format](https://github.com/nomiddlename/date-format) library formatting which will always show local time.
You can configure it to show local time with timezone for clarity.
    > **%d** date, formatted - default is **ISO8601**, format options are: 
    > **ISO8601**, **ISO8601_WITH_TZ_OFFSET**, **ABSOLUTE, DATE**, 
    > or any string compatible with the [date-format](https://github.com/nomiddlename/date-format) library. e.g. **%d{DATE}**, **%d{yyyy/MM/dd-hh.mm.ss}**

2. to use tokens to manually override
    > **%x{\<tokenname\>}** add dynamic tokens to your log. Tokens are specified in the tokens parameter.

```javascript
const log4js = require('log4js');
log4js.configure({
  appenders: { 
    defaultAppender: { 
      type: 'stdout', 
      layout: { 
        type: 'basic'                                        // default format
      } 
    },
    dateformatAppender: {
      type: 'stdout', 
      layout: { 
        type: 'pattern', 
        pattern: "[%d{ISO8601_WITH_TZ_OFFSET}] [%p] %c - %m" // using date-format local time with timezone
      } 
    },
    tokenAppender: { 
      type: 'stdout', 
      layout: { 
        type: 'pattern',
        pattern: '[%x{myTime}] [%p] %c - %m',                // using tokens
        tokens: {
          myTime: function(logEvent) {
            return logEvent.startTime.toISOString();
          }
        }
      }
    }
  },
  categories: { 
   default: { appenders: ['defaultAppender'], level: 'trace' },
   dateformat: { appenders: ['dateformatAppender'], level: 'trace' },
   token: { appenders: ['tokenAppender'], level: 'trace' }
  }
});

const defaultLogger = log4js.getLogger('default');
const dateFormatLogger = log4js.getLogger('dateformat');
const tokenLogger = log4js.getLogger('token');

defaultLogger.debug('Cheese is too ripe!');
// [2022-01-16T02:48:15.122] [DEBUG] default - Cheese is too ripe!

dateFormatLogger.debug('Cheese is too ripe!');
// [2022-01-16T02:48:15.124+0800] [DEBUG] dateformat - Cheese is too ripe!

tokenLogger.debug('Cheese is too ripe!');
// [2022-01-15T18:48:15.126Z] [DEBUG] token - Cheese is too ripe!
```
