### ISSUE TITLE
layout: multiple calls to same function

### ISSUE THREAD

**Issue by konser80** [log4js-node/log4js-node#1100]
I need my own layout, it's OK. I'm re-formatting message, re-colouring, adding time difference in ms, etc.
Also I want to separate files: trace, debug (main) and errors. And a console, of course.

```
function configureLogger(minlevel = LOGLEVEL) {

  const layout = { type: 'pretty' };
  log4js.addLayout('pretty', () => formatLog4JS);

  log4js.configure({
    appenders: {
      console: { layout, type: 'stdout' },

      tracefile: { layout, type: 'dateFile', filename: 'log/trace.log', pattern: '.yyyy-MM-dd-hh', keepFileExt: true, daysToKeep: 7 },
      debugfile: { layout, type: 'dateFile', filename: 'log/debug.log', pattern: '.yyyy-MM-dd', keepFileExt: true, daysToKeep: 30 },
      errorfile: { layout, type: 'dateFile', filename: 'log/error.log', pattern: '.yyyy-MM-dd', keepFileExt: true },

      show: { type: 'logLevelFilter', appender: 'console', level: minlevel },
      savedebug: { type: 'logLevelFilter', appender: 'debugfile', level: 'debug' },
      saveerror: { type: 'logLevelFilter', appender: 'errorfile', level: 'warn' },
    },
    categories: {
      default: { appenders: ['show', 'tracefile', 'savedebug', 'saveerror'], level: 'trace' }
    }
  });

  const logger = log4js.getLogger();
  return logger;
}
```

This code works well, no errors.

BUT my layout function ```formatLog4JS``` executes multiple times for the each event. To show console, to save to trace file, to main file and to errors file. It runs FOUR times per log event.

Is it possible to create smth like a... 'universal' or 'default' layout? So it will be executed just once per event?

**Comment by peteriman** [comment]
The issue here is that each appender is in its own silo. 
Thus, `console`, `tracefile`, `debugfile`, `errorfile` will all parse into `layout`, resulting in `layout` being called 4 times.

It would require some re-work to ensure that the `layout` keeps its own array list of appenders.
The flow would also have to be changed from appenders->layout to layout->appenders.

**Comment by konser80** [comment]
no, no, sorry. Layout should be different for different levels. It's OK. I'd like to close my issue.
