### ISSUE TITLE
Problem with log4js configuration

### ISSUE THREAD

**Issue by ljilik** [log4js-node/log4js-node#1102]
c:\Users\lilik\proxy\node_modules\log4js\lib\configuration.js:31
      throw new Error(`Problem with log4js configuration: (${util.inspect(config, { depth: 5 })})`
      ^

```
Error: Problem with log4js configuration: ({
  appenders: [
    { type: 'console' },
    {
      type: 'dateFile',
      filename: 'log/proxy.log',
      pattern: '-yyyy-MM-dd',
      category: '[PROXY]'
    }
  ]
})
```

Example:
```
log4js.configure({
	
  appenders: [
    { type: 'console' },
    { type: 'dateFile', filename: 'log/proxy.log', pattern: '-yyyy-MM-dd', category: '[PROXY]' }
  ]
})
var logger = log4js.getLogger('[PROXY]')
```

**Comment by nomiddlename** [comment]
Your config is invalid and I think you've chopped off the end of the error message which would have said something about missing a `categories` property from your config. Categories are separate to appenders. See https://log4js-node.github.io/log4js-node/api.html, and an example: https://github.com/log4js-node/log4js-node/blob/master/examples/log-to-files.js
