### ISSUE TITLE
i want to delete log files myself, what should i do?

### ISSUE THREAD

**Issue by iguxiaobei** [log4js-node/log4js-node#1111]
I want to delete log files myself, What should i do?

I use electron, and I want to start a intervel task to delete the log files myself, but It seems like that i have no permission to do this. first time, I can delete old logs, but second time, I can't delete new files.

**Comment by peteriman** [comment]
1. How are you deleting the log files? Do you have the code for it? 
2. Which OS?
3. You mean you can delete old log files but not the current (hot) log file?

**Comment by iguxiaobei** [comment]
> 1. How are you deleting the log files? Do you have the code for it?
> 2. Which OS?
> 3. You mean you can delete old log files but not the current (hot) log file?

1. just fs.unlinkSync(path);
2. windows 7
3. yes

eg:

1. I start a program (electron program), this program generates 3 files. 2022-01-01.log  2022-01-02.log  2022-01-03.log
2. I need delete  2022-01-01.log and 2022-01-02.log.
3. first time, I can delete this two files, but, 2022-01-01.log file still exists, and it can't be open, when I exit this electron program, 2022-01-01.log disapear...
4. before I exit this electron program, I can read 2022-01-01.log file in directory, but when i use fs.stat(path[, options], callback) to get  2022-01-01.log file's infomation, I got an error...

**Comment by peteriman** [comment]
1. What is your `log4js` version?
2. Do you have the code snippet of how you configure the appender pattern?
    (so that I can check for the rolling configuration)

**Comment by peteriman** [comment]
This seems to be similar to https://github.com/log4js-node/log4js-node/issues/711#issuecomment-1057794078. 
In Windows, when a file is deleted, the file will remain but in a "zombie-state" till the handlers are closed or when NodeJS exits.

Is there a use-case as to why you would need to manually delete those files when `log4js` can be configured for rollover?

---

In any case, `log4js` does not hold onto the previous log files once they are rolled over. 
Thus, you should not be experiencing this issue.

```javascript
const log4js = require('log4js');
log4js.configure({
  appenders: {
    'out': { type: 'stdout' },
    'everything': { 
      type: 'dateFile', 
      filename: 'logs/trace.log',
      pattern: 'yyyy-MM-dd-hhmmss',
      keepFileExt: true,
      numBackups: 30 // total 31 files (1 hot + 30 backups)
    }
  },
  categories: {
    default: { appenders: [ 'out', 'everything' ], level: 'debug'}
  }
});

const logger = log4js.getLogger();
let count = 1;
let timer = setInterval(() => {
  logger.warn("testing", count);

  let dirList = fs.readdirSync("logs");
  console.log("[current] dirList in logs:", dirList);

  if (count >= 5) { // spam 5 times
   clearInterval(timer);

   // existing files
   logger.warn("testing", count, "- deleting");
   const fileToDelete = path.join("logs", dirList[0]);
   console.log("file to delete:", fileToDelete);

   // delete 1 old file
   fs.unlinkSync(path.join("logs", dirList[0]));
   dirList = fs.readdirSync("logs");
   console.log("[deleted] dirList in logs:", dirList);
  }

  count++;
}, 1000);
```
![image](https://user-images.githubusercontent.com/29530649/156870432-4e0f225d-df14-4b2f-b80a-0fed0dc49ef3.png)

**Comment by iguxiaobei** [comment]
> This seems to be similar to [#711 (comment)](https://github.com/log4js-node/log4js-node/issues/711#issuecomment-1057794078). In Windows, when a file is deleted, if there are existing handlers, the file will remain in a "zombie-state" till the handlers are closed or when NodeJS exits.
> 
> Is there a use-case as to why you would need to manually delete those files when `log4js` can be configured for rollover?
> 
> In any case, `log4js` does not hold onto the previous log files once they are rolled over. Thus, you should not be experiencing this issue. I successfully deleted in my code snippet below:
> 
> ```js
> const log4js = require('log4js');
> log4js.configure({
>   appenders: {
>     'out': { type: 'stdout' },
>     'everything': { 
>       type: 'dateFile', 
>       filename: 'logs/trace.log',
>       pattern: 'yyyy-MM-dd-hhmmss',
>       keepFileExt: true,
>       numBackups: 30 // total 31 files (1 hot + 30 backups)
>     }
>   },
>   categories: {
>     default: { appenders: [ 'out', 'everything' ], level: 'debug'}
>   }
> });
> 
> const logger = log4js.getLogger();
> let count = 1;
> let timer = setInterval(() => {
>   logger.warn("testing", count);
> 
>   let dirList = fs.readdirSync("logs");
>   console.log("[current] dirList in logs:", dirList);
> 
>   if (count >= 5) { // spam 5 times
>    clearInterval(timer);
> 
>    // existing files
>    logger.warn("testing", count, "- deleting");
>    const fileToDelete = path.join("logs", dirList[0]);
>    console.log("file to delete:", fileToDelete);
> 
>    // delete 1 old file
>    fs.unlinkSync(path.join("logs", dirList[0]));
>    dirList = fs.readdirSync("logs");
>    console.log("[deleted] dirList in logs:", dirList);
>   }
> 
>   count++;
> }, 1000);
> ```
> 
> ![image](https://user-images.githubusercontent.com/29530649/156870476-d69436a2-7b50-4cf6-99ac-6e734cb2b068.png)

i think it's the same problem...

i want put the log file to server, and the server read log file content,and save content to elk.so i want delete files when the files have put to server...

**Comment by peteriman** [comment]
@iguxiaobei Which version of `log4js` are you using? Please test with minimally `log4js@^6.4.0`.

This issue would also occur (on Windows) in log4js <= 6.3.0 if `log4js.configure()` is called multiple times. In those versions, when `log4js.configure()` is called multiple times, multiple handlers are created for the same files without closing. When the last configuration attempts a rollover on the file, it will be blocked as the file handlers from previous configurations are still holding onto the file. In that case, the only effective way would be to exit NodeJS. That was patched in PR https://github.com/log4js-node/log4js-node/pull/1113 from `log4js@^6.4.0`.

---

To delete the files programmatically via NodeJS on Windows, you have to ensure all file handlers are closed.

If you are using `log4js` and on Windows, 
- for the old log files or files that have been rolled over (`log.1`, `log.2`, etc.), there are no opened handlers.
  -  no problem using a custom code to read, save to elk and delete.
- for the hot log file, there is currently an open handler.
  - no problem using custom code to read, save to elk.
  - for delete, after executing `unlink` or similar, Windows will not delete the file due to the opened handler.
    - Windows will only delete the file after the handler has been closed.
      - `log4js` will always hold onto the hot file (to write logs) until `log4js.shutdown()` or NodeJS exits.
    - This is a Windows-specific behaviour that does not happen on Linux.

If you really want to, albeit destructive, you can call `log4js.shutdown(() => {})` with your read/save/delete code in the callback and re-configure `log4js` once done.

```javascript
log4js.shutdown(() => {
  // read/save/delete code here
  log4js.configure(options);
});
```

**Comment by peteriman** [comment]
@iguxiaobei, does the comment above resolve your issue?

**Comment by iguxiaobei** [comment]
> @iguxiaobei, does the comment above resolve your issue?

i think it has resolved，thank you，i will close this issue.
