### ISSUE TITLE
Disable coloured output?

### ISSUE THREAD

**Issue by simon-lang** [log4js-node/log4js-node#112]
Hi. Thanks for great library. Exactly what I need. When I'm debugging the coloured output writing to my console is very helpful. However, in production I am using [forever](https://github.com/nodejitsu/forever) which takes all std out and writes it to a log file instead. As such, my log files look like this:

`[32m[2013-02-04 09:53:26.736] [INFO] console - [39mhello 'world'`

I'm assuming those odd escape characters are the colouring for terminal. 

I realise log4js allows you to specify a file to write to, but I am happy with the way forever is currently doing it.

Is there any way I can disable this colouring for production? I looked in the docs but couldn't find anything.

Edit: in case it wasn't clear, I am using `log4js.replaceConsole()`

**Comment by cfogelberg** [comment]
+1 chrisbartley's comment

**Comment by yurivict** [comment]
What is the point of having the special option that prevents colors printed onto the file? Why not just do this automatically in all cases?
