### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [log4js-node/log4js-node#1123]
Hey there!

I belong to an open source security research community, and a member (@ranjit-git) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by nomiddlename** [comment]
Thanks for bringing this up. I've raised a PR to add this in.

**Comment by JamieSlome** [comment]
@nomiddlename - thanks for the support here. You should have just received an e-mail about 10 minutes ago! Otherwise, you can view the report directly here:

https://huntr.dev/bounties/f0af1223-2cea-4df7-a2e4-57bd2bead103/

It is private and only accessible to maintainers with repository write permissions.
