### ISSUE TITLE
Wrong TS types in 6.4.0?

### ISSUE THREAD

**Issue by glasser** [log4js-node/log4js-node#1155]
Hi. My project doesn't directly use log4js but we do want to make sure that a `logger` argument we take is compatible with `log4js` objects, so [our test suite](https://github.com/apollographql/apollo-server/blob/16adb42ef5427d6b311fd1462667451d33bdf99c/packages/apollo-server-core/src/__tests__/logger.test.ts#L114-L145) sets up log4js and sends a message through it (via our ApolloServer object) and tests that it works.

Renovate picked up the 6.4.0 release but [this test file doesn't compile](https://app.circleci.com/jobs/github/apollographql/apollo-server/114688?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) with the changes to your TypeScript types in v6.4.0.

I honestly don't understand log4js well enough to be sure, but it looks like the issue is specific to the types, not an actual change to your JS code.

Specifically, we call:

```
    log4js.configure({
      appenders: {
        custom: {
          type: {
            configure: () => (loggingEvent: log4js.LoggingEvent) =>
              sink(loggingEvent),
          },
        },
      },
      categories: {
        default: {
          appenders: ['custom'],
          level: LOWEST_LOG_LEVEL,
        },
      },
    });
```

According to your types file, the `configure` function is a `(config: Config, layouts: LayoutsParam) => AppenderGenerator`, and AppenderGenerator is `(layout: LayoutFunction, timezoneOffset?: string) => AppenderFunction`, and `AppenderFunction` is `(loggingEvent: LoggingEvent) => void`.

This is one more layer of "function" than the code above that previously worked for us: the outer `() =>` is the `(config, layouts) =>` type, and the inner `(loggingEvent) =>` function is an AppenderFunction, but we were not writing an AppenderGenerator in the middle.

OK, I said.  This seemed like an odd backwards-incompatibility to put out in a minor release, but sure.  I added another `() =>` after the first `() =>` above... and my test failed.

I reverted that change and instead added an `as any` somewhere... and my test passed.

So... I don't really know much about log4js. But it seems like what happened here is that v6.4.0 did *not* actually change your API as implemented in JS, but that the TypeScript changes introduced an intermediate function that isn't actually part of code.

Specifically it seems like maybe `AppenderGenerator` isn't a real thing and that `AppenderModule` should be declared as

```
export interface AppenderModule {
  configure: (config: Config, layouts: LayoutsParam) => AppenderFunction;
}
```

Am I missing something?

**Comment by glasser** [comment]
I think this was introduced in https://github.com/log4js-node/log4js-node/pull/1079 FWIW.

**Comment by peteriman** [comment]
Hi, our test cases passed as it didn't cover the typescript aspect. I concur with you that it might be something to do with the types and not the code.

I don't use typescript, so I would need to rely on users like you to help me with it. If you have the solution ready, would you mind making a PR? 

I'll try to take a look at it when I have the time, and perhaps you can help me with running the tests before the next release? That'll be awesome.

**Comment by glasser** [comment]
Thanks, I filed a PR. It makes your existing TS compilation tests pass (they were failing before actually) with a combination of test and typing changes.
