### ISSUE TITLE
No info shown at https://www.npmjs.com/package/log4js

### ISSUE THREAD

**Issue by thernstig** [log4js-node/log4js-node#1157]
The README content does not seem to be displayed there, which I assume you want?

**Comment by peteriman** [comment]
I used to have the same problem previously with some other packages. Not sure if it's an npm overloaded issue.
For me, I do have the README.md displayed. Perhaps you can try again shortly after and see if it still blank for you?

![image](https://user-images.githubusercontent.com/29530649/150562934-16a678e1-09bc-452d-b0e1-65f3ff9e6545.png)

**Comment by thernstig** [comment]
@peteriman It works now indeed, so it was probably an npm.com hiccup as you say.
