### ISSUE TITLE
Log4js not able to run/import when using PM2

### ISSUE THREAD

**Issue by izakfhy** [log4js-node/log4js-node#1176]
Hi,

I was testing out using log4js in one of my sample scripts (following the documentation on the log4js website) 

![image](https://user-images.githubusercontent.com/23104041/151360379-d6134f55-5a76-4fb6-999e-e7eefb1f0c62.png)

However, when I am running the script with PM2, I am getting the following error
`9|test  | TypeError: Cannot read property 'name' of undefined
9|test  |     at exports.fromCallback (/var/www/temp/test/node_modules/universalify/index.js:15:26)
9|test  |     at Object.<anonymous> (/var/www/temp/test/node_modules/fs-extra/lib/fs/index.js:57:27)
9|test  |     at Module._compile (module.js:635:30)
9|test  |     at Object.Module._extensions..js (module.js:646:10)
9|test  |     at Module.load (module.js:554:32)
9|test  |     at tryModuleLoad (module.js:497:12)
9|test  |     at Function.Module._load (module.js:489:3)
9|test  |     at Module.require (module.js:579:17)
9|test  |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
9|test  |     at require (internal/module.js:11:18)`

However, when I tried to execute directly with "node test.js" it is working fine.

May I seek your assistance for this issue please?

Log4js version: 6.4.1
PM2 version: 5.1.2

Thank you

**Comment by peteriman** [comment]
Error is similar to #1186.

What is your Nodejs version? 

`fs.realpath.native` (used by `fs-extra` via `universalify` is only available in NodeJS >=9.2.0
_(src: https://nodejs.org/dist/latest-v16.x/docs/api/fs.html#fsrealpathnativepath-options-callback)_

**Comment by izakfhy** [comment]
ahh you are right, there were 2 node binaries (v8.9 and v10) in the server and pm2 was using v8.9 to run the services. 
After removing the older node version, the issue is resolved.

Thank you!
