### ISSUE TITLE
6.4.0 introduced a breaking type change through #1117

### ISSUE THREAD

**Issue by simhnna** [log4js-node/log4js-node#1178]
Not sure if you're following semver or not, but this change broke our code.

Any chance we can maybe go to `_log(level: Level | string, data: any)` and internally converting strings to Level?

**Comment by peteriman** [comment]
In any case, you should be using `log`. Would using `log` suffice?
https://github.com/log4js-node/log4js-node/blob/2d52eb484bb548d5a10ca55280c7606d02bcbaf9/types/log4js.d.ts#L346
https://github.com/log4js-node/log4js-node/blob/2d52eb484bb548d5a10ca55280c7606d02bcbaf9/lib/logger.js#L71-L80

**Comment by peteriman** [comment]
Hi, it's been close to 2 weeks, any follow ups?

**Comment by peteriman** [comment]
Hi @simhnna, it's been close to 2 weeks, any follow ups?

**Comment by peteriman** [comment]
The `Logger` class has both `log()` and `_log()`.
You probably have to refactor your logger to use `log()` instead of `_log()`.

**Comment by peteriman** [comment]
The `Logger` class has both `log()` - public and `_log()` - internal.
You probably have to refactor your logger to use `.log()` instead of `._log()`.

**Comment by peteriman** [comment]
The `Logger` class has both `log()` - public and `_log()` - internal.
You probably have to refactor your logger to use `.log()` instead of `._log()`.

I'll leave this issue open for now and check back with you again after 2 weeks.

**Comment by peteriman** [comment]
`._log()` is an internal API. Please migrate over to `.log()`. 
There are differences between `.log()` and `._log()` as shown in the example below that might help you.

```javascript
const log4js = require("log4js");
log4js.configure({
  appenders: {
    normal: { type: 'stdout' }
  },
  categories: {
    default: { appenders: ['normal'], level: 'info' }
  }
});
const logger = log4js.getLogger();

logger.info("hello"); // String
// [2022-03-09T01:13:38.129] [INFO] default - hello

logger.log("info", "hello"); // String, String
// [2022-03-09T01:13:38.135] [INFO] default - hello

logger._log("info", "hello"); // String, String
// [2022-03-09T01:13:38.139] [info] default - h e l l o

const Level = require("log4js/lib/levels");
logger._log(Level.INFO, ["hello"]); // Level, String[]
// [2022-03-09T01:13:38.149] [INFO] default - hello
```
![image](https://user-images.githubusercontent.com/29530649/157289987-b0fcc441-fe6f-4f52-924e-e2247c53d4c3.png)

**Comment by peteriman** [comment]
@simhnna, did you managed to refactor?

**Comment by lamweili** [comment]
@simhnna?

**Comment by lamweili** [comment]
> yeah. I refactored this. But then again [126e286](https://github.com/log4js-node/log4js-node/commit/126e286c1a56892f3962a5621e46c8ddf4b41510) was also a change that removed an exported type.
> 
> I'm currently pinning log4js due to such changes

@simhnna, which is the removed exported type in 126e286c1a56892f3962a5621e46c8ddf4b41510?
I see `BaseLayout` being renamed to `BasicLayout` (which shouldn't affect anything) and changes to comments. 🤔

**Comment by simhnna** [comment]
I mean the missing BaseLayout. Renaming something is like removing it. I have log4js defined as a peer dependency (`^6.0.0`) and such changes break our builds if anyone pulls in the latest version

**Comment by lamweili** [comment]
@simhnna, I see. Perhaps you should also rename `BaseLayout` to `BasicLayout` as part of the refactoring, so that you can update to have bugfixes.

Of course, you can also stick with the pinned version if it solves the problem for you. 

Can we close this issue?

**Comment by lamweili** [comment]
> If you want you can close the issue

@simhnna, can we close the issue?

**Comment by lamweili** [comment]
Closed due to extended period of inactivity.
