### ISSUE TITLE
Jest test suite failed to run with v6.4.1

### ISSUE THREAD

**Issue by jianlong90** [log4js-node/log4js-node#1186]
Jest test suites failed to run after upgrading log4js to v6.4.1 that uses steamroller.
```
    Test suite failed to run

    TypeError: Cannot read property 'name' of undefined

      at Object.<anonymous>.exports.fromCallback (node_modules/streamroller/node_modules/universalify/index.js:15:26)
      at Object.<anonymous> (node_modules/streamroller/node_modules/fs-extra/lib/fs/index.js:57:27)
      at Object.<anonymous> (node_modules/streamroller/node_modules/fs-extra/lib/index.js:5:6)
```

**Comment by jianlong90** [comment]
Below is the log4js configuration. The main project source code is working fine. However, when running Jest test cases, the unit tests failed to run. 
```
configure({
  appenders: {
    log: { type: 'stdout', layout: { type: 'jsonLayout', separator: ' ' } }
  },
  categories: {
    default: { appenders: ['log'], level: isJest ? 'error' : 'info' }
  }
});
```

**Comment by peteriman** [comment]
Strange. `stdout` appender does not use `streamroller`.
Do you have more of the stacktrace?

**Comment by peteriman** [comment]
Please bear with me while I attempt to debug the issue.

Strange. `stdout` appender does not use `streamroller`.
https://github.com/log4js-node/log4js-node/blob/master/lib/appenders/stdout.js

1. Do you have more of the stacktrace? Or would you have a more complete code snippet? 
2. Which version of NodeJS is the test running on? 

---

From the stacktrace:
```javascript
at Object.<anonymous>.exports.fromCallback (node_modules/streamroller/node_modules/universalify/index.js:15:26)
```

```javascript
15:      }, 'name', { value: fn.name })
```
_(src: https://github.com/RyanZim/universalify/blob/a853a4aedc63c69fcdc62b77643d75b0d162a098/index.js#L15)_

---

Drilling deeper to next stacktrace:
```javascript
  at Object.<anonymous> (node_modules/streamroller/node_modules/fs-extra/lib/fs/index.js:57:27)
```
```javascript
57:    exports.realpath.native = u(fs.realpath.native)
```
_(src: https://github.com/jprichardson/node-fs-extra/blob/7edcb16a06e041826af3303f961866bf3b243dae/lib/fs/index.js#L57)_

---

`fs.realpath.native` is only available in Node.JS >=9.2.0
_(src: https://nodejs.org/dist/latest-v16.x/docs/api/fs.html#fsrealpathnativepath-options-callback)_

**Comment by peteriman** [comment]
I managed to replicate it by using an older version of NodeJS (pre 9.2.0).
Running just `const log4js = require('log4js');` would have triggered it.

![image](https://user-images.githubusercontent.com/29530649/153185301-c759ecdb-8166-4b20-b04b-3527ff876e8b.png)

However, I am unsure if this is your issue. 
Please get back with your findings. Thanks!

**Comment by jianlong90** [comment]
The node version I am using is 14.18.1. 

Realised that running the test cases individually is working fine. However, if multiple test suites were run together, the first test suite executes fine but the subsequent test suites will get the error message from streamroller.

**Comment by chattersley** [comment]
We are getting the same issue. On Windows it works fine but when we attempt to run the tests in Linux it fails. We are using node 12. Issue is easier to replicate when you run tests in band, `npm run test -- --runInBand`.

  ● Test suite failed to run

    TypeError: Cannot read property 'name' of undefined

      at Object.<anonymous>.exports.fromCallback (node_modules/streamroller/node_modules/universalify/index.js:15:26)
      at Object.<anonymous> (node_modules/streamroller/node_modules/fs-extra/lib/fs/index.js:57:27)
      at Object.<anonymous> (node_modules/streamroller/node_modules/fs-extra/lib/index.js:5:6)

**Comment by peteriman** [comment]
@chattersley Which version of NodeJS 12 specifically (so I can replicate with exact version)?
You are not using Jest, are you?

**Comment by jianlong90** [comment]
@peteriman, in the /streamroller/node_modules/fs-extra/lib/js/index.js, I've add a condition check before `exports.realpath.native = u(fs.realpath.native)`. 

```
if (typeof fs.realpath.native === 'function') {
  exports.realpath.native = u(fs.realpath.native)
}
```

After adding this condition, all the test cases executed successfully.

**Comment by chattersley** [comment]
> @chattersley
> 
> 1. Which version of NodeJS 12 specifically (so I can replicate with exact version)?
> 2. Are you using Jest as well?

Apologies, that would help! We are using jest.

node - v12.22.7
npm - 8.1.4
jest - 27.5.1

**Comment by chattersley** [comment]
> if (typeof fs.realpath.native === 'function') {
>   exports.realpath.native = u(fs.realpath.native)
> }

I can confirm that condition fixes the issue.

**Comment by peteriman** [comment]
Agree that the check will prevent the error from happening, but it doesn't solve the root cause.
The root cause is why did the `fs.realpath.native` got removed in subsequent test cases that triggers the error.

For the addition of the check, unfortunately, we are not the author of the `fs-extra` library.

This was the PR that removed the check (only support NodeJS >9.2.0 onwards)
https://github.com/jprichardson/node-fs-extra/pull/887/files

Give me some time to troubleshoot the root cause before downgrading `fs-extra`.

@chattersley I'm not a user of Jest. Do I just `npm install jest` (or similar) and run `npm run test -- --runInBand`?

**Comment by chattersley** [comment]
> if (typeof fs.realpath.native === 'function') {
>   exports.realpath.native = u(fs.realpath.native)
> }
You'll need a script in package.json, and some tests!
`"test": "jest"`

**Comment by peteriman** [comment]
Ok, I can add that to my `package.json`.

For the tests, do I need a set of brand new test cases specifically for Jest or can I reuse the ones in the test folder?

**Comment by chattersley** [comment]
> Ok, I can add that to my `package.json` for debugging purpose. For the tests, do I need a set of brand new test cases specifically for Jest or can I reuse the ones in the [test](https://github.com/log4js-node/log4js-node/tree/master/test) folder?

Not sure if they need to be jest tests or not I'm afraid. I'm having a closer look now. Somewhere fs.realpath.native is getting trashed. If I comment out the exports in node_modules/streamroller/lib/index.js it starts to work fine. Printing out fs.s.realpath.native on each test run shows it to be populated in the first set of jest tests but in subsequent tests is undefined.

**Comment by peteriman** [comment]
@chattersley Yup, my suspicion is somewhere `fs.realpath.native` got removed or something based on the description so far. 

I haven't been able to try to reproduce it yet.

Fixing that issue will resolve the root cause altogether.

**Comment by chattersley** [comment]
> @chattersley Yup, my suspicion is somewhere `fs.realpath.native` got removed or something based on the description so far.
> 
> I haven't been able to try to reproduce it yet.
> 
> Fixing that issue will resolve the root cause altogether. Let me know if you have further findings while I try to find time for this.

I have "fixed" the issue on the repo our side, where it is failing. I tried updating one of our other repos and it didn't error!

This is rather long-winded but:

We have some mocks in a private npm namespace. A couple of these were mocked in the __mocks__ folder in the root of the project. One did not have a physical file but was mocked locally. Including that file, completely blank, fixes the issue. Must be something to do with how jest is initialising the mocks. I would hold on trying to reproduce this, it seems like an edge case.

I'll try and reproduce it for you tonight.

**Comment by peteriman** [comment]
@chattersley Thanks, it does seem like a mock issue with Jest. I'll wait for your further findings.

Perhaps you can share exactly what you did, so @jianlong90 can try to fix it on his side.

**Comment by chattersley** [comment]
> @chattersley Thanks, it does seem like a mock issue with Jest. I'll wait for your further findings.
> 
> Perhaps you can share exactly what you did, so @jianlong90 can try to fix it on his side.

I've had a good go at reproducing this issue in a sanitised project but can't seem to trip it in the same way.

@jianlong90 not sure if you have a mocks folder. Try and create a file for all the name-spaced dependencies. For example I had @mycompany as a private namespace, going to a private npm repo. We had one file that was being mocked locally but didn't have a physical file in the mocks/@mycomany folder. I created a completely blank file and it no longer fails.

**Comment by jianlong90** [comment]
@chattersley my project does not have any namespace dependencies. My project runs the spec.ts files which directly import local files. All mocks were defined in the spec.ts files as well.

I have also tried leaving only two of the spec.ts files and cleared off other test files but I am still hitting the same error.

**Comment by jianlong90** [comment]
An update on my issue. It was another package that was causing the issue (aws-xray-sdk).

As `aws-xray-sdk` doesn't work in local environment, it will log an error out to console. After adding a conditional import for the package, my test cases executed successfully.
