### ISSUE TITLE
How can I config one single appender to log in files as well as console?

### ISSUE THREAD

**Issue by data756** [log4js-node/log4js-node#1190]
I have one requirement in which i have to generate my logs into file as well as console. How can we do that?

**Comment by chhiring90** [comment]
"Standard Output Appender" will print log in console. Add the `type: 'stdout'` in the appender that will configure it.
```
configure({
  appenders: {
    cheese: { type: 'file', filename: 'cheese.log' },
    print: { type: 'stdout' },
  },
  categories: { default: { appenders: ['cheese', 'print'], level: 'debug' } },
});
```
For more info check out the documentation [here](https://log4js-node.github.io/log4js-node/stdout.html).
In case you want to check the [demo](https://stackblitz.com/edit/node-uabdnz?embed=1&file=cheese.log).
