### ISSUE TITLE
connect-logger with custom log function

### ISSUE THREAD

**Issue by issacg** [log4js-node/log4js-node#120]
There's an odd issue that I'm running into working with the connect-logger module.  I'm using a custom function to generate my log format, but I've noticed that the function signatures are different in the stock connect logger middleware and the connect-logger middleware.

The stock connect logger defines a custom format function as function(tokens, request, response) but connect-logger calls the custom function with just (request, response)

It seems pretty trivial to fix this, but I'm not sure if there are people with live code that will break if the format changes, so the first step to "fixing" this (if it indeed is unintentional and needs a "fix") is to decide how to do so safely; just having an open issue or an issue which says "this will not be fixed" might be a help for developers who run into this in the future.

**Comment by nomiddlename** [comment]
I'm going to close this, because it's been over 6 years and nobody else has commented that they have encountered this issue (also, I have no idea if anyone still uses connect).
