### ISSUE TITLE
log file generated has permission issue in ^6.4.0

### ISSUE THREAD

**Issue by lakshmikanthadn** [log4js-node/log4js-node#1213]
The log file generated does NOT have permmsions to read by any other users/applications.
This is happening in v6.4.x but works in v6.3.0

Breaking In v6.4.x
![image](https://user-images.githubusercontent.com/8288416/158347184-940f3173-d2e6-4adb-9d41-bec060307d4a.png)

Works In v6.3.x
![image](https://user-images.githubusercontent.com/8288416/158347432-3a03cdfd-a59a-4c85-a18c-7d0ea74ccd90.png)

Our log shipper is broken. For now we have reverted back to v6.3.0.

**Comment by peteriman** [comment]
## Security Advisory https://github.com/log4js-node/log4js-node/security/advisories/GHSA-82v2-mx6x-wq7q
For security, the **default** file permission from v6.4.1 onwards has changed from `0644` to `0600`.
It is to prevent unauthorised users from reading logs that may contain sensitive information.

--------

In your case, the log is created by `root` (implies your running node is under `root`) and thus, only accessible by `root`.
Only applications using `root` can access it. Applications using other accounts will not be able to access it.

1. Either you run other applications using the `root` account, or
2. Manually specify the permission to be used through the `mode` options as listed in the [docs](https://log4js-node.github.io/log4js-node/file.html):
    ```javascript
    const log4js = require('log4js');
    log4js.configure({
      appenders: {
        everything: { type: 'file', filename: 'all-the-logs.log', mode: 0o644 }
      },
      categories: {
        default: { appenders: [ 'everything' ], level: 'debug' }
      }
    });
    
    const logger = log4js.getLogger();
    logger.debug('I will be logged in all-the-logs.log');
    ```

**Comment by peteriman** [comment]
Does it resolve your issue? Please close the issue if it does.

**Comment by peteriman** [comment]
Does it resolve your issue? Please close the issue if it does.

**Comment by peteriman** [comment]
This is related to #1141.

In hindsight, probably should have used 7.x.x instead.
I have updated the changelog (https://github.com/log4js-node/log4js-node/commit/7010a7d93aaf31b01d6aed9c943720a1f2c44083) to have a more indicative warning now we are unable to go back in time.

My mistake.
