### ISSUE TITLE
How can we filter by user-agent?

### ISSUE THREAD

**Issue by quocvu** [log4js-node/log4js-node#1214]
I might not always care about logging activities produced by the web crawlers. Does anyone have an example of how to accomplish this?
Thanks

**Comment by lamweili** [comment]
Hi, you can now do it with this [enhancement ](https://github.com/log4js-node/log4js-node/pull/1279) by @eyoboue, using `nolog` in `connectLogger`.
Detailed documentation at https://log4js-node.github.io/log4js-node/connect-logger.html.

```js
var express = require("express");
var useragent = require('express-useragent');

var log4js = require("log4js");
log4js.configure({
  appenders: {
    console: { type: "console" },
    file: { type: "file", filename: "cheese.log" },
  },
  categories: {
    cheese: { appenders: ["file"], level: "info" },
    default: { appenders: ["console"], level: "info" },
  },
});
var logger = log4js.getLogger("cheese");

var app = express();
app.use(useragent.express());
app.use(
  log4js.connectLogger(logger, {
    level: "auto",
    format: ":method :url",
    nolog: (req, res) => req.useragent.platform.isBot, // do your own filtering for crawlers via `req.useragent`
  })
);

app.get("/", function (req, res) {
  res.send(req.useragent);
});
app.listen(5000);
```

**Comment by quocvu** [comment]
thank you @lamweili.  That worked for me and I was able to filter out the entry which logs the HTTP endpoint being called.  However, I want to also filter out all log entries associated with that execution.  For example, let's say the bot hit the page https://myhost.com/foo/page1 and when rendering that page, I could get logs from other modules such as my ORM lib.  It seems this approach only filters events from express.  Any tip would be very appreciated
