### ISSUE TITLE
Logs not flushing to file on process.exit

### ISSUE THREAD

**Issue by stormherz** [log4js-node/log4js-node#122]
Problem, described in pull request https://github.com/nomiddlename/log4js-node/pull/65, logging something to file appender and ending process right after results in missing logs.

**Comment by despairblue** [comment]
@nomiddlename does this also flush to loggly? I was trying to find a way to flush messages to loggly before exiting, and it seems the only viable solution is `setTimeout`.

**Comment by nomiddlename** [comment]
The Loggly appender doesn't register a shutdown function, which is probably the issue there.

**Comment by despairblue** [comment]
@nomiddlename would you welcome a PR?
