### ISSUE TITLE
logger not write into the file from the catch block

### ISSUE THREAD

**Issue by GolDiV** [log4js-node/log4js-node#1222]
I want to log errors on try catch construct using log4js. I have next code:
```
let log4js = require('log4js')
log4js.configure({
  appenders: {
    asterisk: {type: 'file', filename: 'filename'},
    out: {type: 'stdout'},
  },
  categories: {default: {appenders: ['asterisk', 'out'], level: 'all'}}
})
const logger = log4js.getLogger('asterisk')
async function myFunc() {
  try {
    let tmp = await someFunc()
  }
  catch (err) {
    logger.error(err)
    process.exit(1)
  }
}
myFunc()
```
When an error occurs, I see it in the console, but it is not written to the file. If I use logger outside try..catch block then everything works fine. What could be the problem?

**Comment by nomiddlename** [comment]
The problem is in the process.exit - this causes node to exit before the logger.error call (which is asynchronous behind the scenes) has written to the file.

**Comment by GolDiV** [comment]
It works fine! Thank you.

**Comment by GolDiV** [comment]
Sorry, but I hurried. 
If I make 
```
await logger.error(err)
process.exit()
```
it work fine, but if I make
```
await logger.error(err)
await logger.info('Bye bye')
process.exit()
```
the first logger write to file, but the second logger not write.

**Comment by peteriman** [comment]
The methods `logger.<level>` does not return a `Promise`.

It would work if you do the following:
```javascript
logger.error(err);
logger.info('Bye bye');
log4js.shutdown(() => process.exit(1));
```

**Comment by GolDiV** [comment]
Now it's work perfectly! Thank you.
