### ISSUE TITLE
Hello, I would like to ask a question.

### ISSUE THREAD

**Issue by mongolming** [log4js-node/log4js-node#1226]
I want to upgrade log4js from 3.0.6 to 6.4.4, what problems should I pay attention to? thanks.

**Comment by peteriman** [comment]
Hmm, I'm not exactly sure about the history of the migration paths.
Probably take a look at the [migration guide](https://log4js-node.github.io/log4js-node/migration-guide.html)?

It does seem like there are not many API differences between v3 to v6. But I may be wrong.

**Comment by lamweili** [comment]
Closed due to extended period of inactivity.
