### ISSUE TITLE
[bug] Build with typescript

### ISSUE THREAD

**Issue by aitimate** [log4js-node/log4js-node#1265]
![image](https://user-images.githubusercontent.com/47878132/170989202-9a50ea88-c485-4bd7-afe2-7870ee2e9caa.png)

webpack.config.js
```
    resolve: {
        extensions: ['.tsx', '.ts', '.js'],
        fallback: {
            "fs": false
        }
    }
```

**Comment by peteriman** [comment]
Try adding the following:

webpack.config.js
```
    resolve: {
        extensions: ['.tsx', '.ts', '.js'],
        fallback: {
            "fs": false,
            "cluster": false
        }
    }
```

**Comment by lamweili** [comment]
@nil-one Let me know if you are still experiencing issues.

**Comment by lamweili** [comment]
@nil-one?

**Comment by lamweili** [comment]
@nil-one?

**Comment by amicoderozer** [comment]
> Try adding `"cluster": false` and see if it helps?
> ## webpack.config.js
> 
> ```js
>     resolve: {
>         extensions: ['.tsx', '.ts', '.js'],
>         fallback: {
>             "fs": false,
>             "cluster": false
>         }
>     }
> ```

For me this fixed it!

**Comment by lamweili** [comment]
Closed due to extended period of inactivity.
