### ISSUE TITLE
Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by gyjcode** [log4js-node/log4js-node#1270]
When I use it in Vue, I get the following error

![image](https://user-images.githubusercontent.com/45870098/174431617-9c73984b-b930-4281-a1bb-e89f51b2d872.png)

**Comment by peteriman** [comment]
Looks like you're trying to use log4js to use in a browser.

**Comment by peteriman** [comment]
Looks like you're trying to use `log4js` to use in a browser.

**Comment by lamweili** [comment]
You might need to use `browserify` for `log4js` on the browser. 
Do a search on the issue list for `browserify` and you should get some help.

**Comment by lamweili** [comment]
Did that resolve your issue?

**Comment by gyjcode** [comment]
yeah, thanks for your help.

**Comment by lamweili** [comment]
Mind sharing what was the solution for others?

**Comment by lamweili** [comment]
Thanks to @aellerton who came up with PR #1374 which resolved the issue.
Will be released in `log4js@6.8.1`.

**Comment by lamweili** [comment]
Thanks to @aellerton who came up with PR #1374 which resolved the issue.
Will be released in `log4js@6.9.0`.
