### ISSUE TITLE
windows already occupied log files cannot be compressed?

### ISSUE THREAD

**Issue by Z-WangYe** [log4js-node/log4js-node#1286]
The log log file generated on the windows system is 7z or winRar reports that the file is occupied, but the log file and folder can be deleted.How to solve it

**Comment by lamweili** [comment]
Sorry but I have difficulty understanding what you are trying to say.

**Comment by lamweili** [comment]
Sorry but I have difficulty understanding what you are trying to say.
I tried to run your demo. 


In [`log4js.config.json`](https://github.com/Z-WangYe/test-log/blob/7ea131150905e44a09c9bf564e77a7a9c0fc5a25/log4js.config.json), it is rolling by days and/or 126976 bytes, without compression.
Based on your [index.js](https://github.com/Z-WangYe/test-log/blob/7ea131150905e44a09c9bf564e77a7a9c0fc5a25/index.js), you are logging once per second for 10 seconds. It won't be sufficient to trigger any rolling to see any issues.

**Comment by lamweili** [comment]
This is continued in #1287.
