### ISSUE TITLE
Categoris use console appenders always return OFF level

### ISSUE THREAD

**Issue by jianzhou520** [log4js-node/log4js-node#1289]
log4js.configure({
      pm2: true,
      appenders: {
        console: {
          type: 'console',
        },
      },
      categories: {
        default: { appenders: ['console'], level: 'all' },
      }
}

// level always OFF
console.log(log4js.getLogger().level)

**Comment by lamweili** [comment]
I guess there is no more issue since you closed it. 
I tested and it works fine.

## Input:
```js
const log4js = require('log4js');
log4js.configure({
  appenders: {
    console: {
      type: 'console',
    },
  },
  categories: {
    default: { appenders: ['console'], level: 'all' },
  }
});

// level always OFF
console.log(log4js.getLogger().level)
```

## Output:
```
Level { level: 5e-324, levelStr: 'ALL', colour: 'grey' }
```
