### ISSUE TITLE
[FEATURE] add Filename similar to `logger.trace()` to logs in console & file

### ISSUE THREAD

**Issue by Creative-Difficulty** [log4js-node/log4js-node#1291]
[This question](https://stackoverflow.com/questions/13410754/i-want-to-display-the-file-name-in-the-log-statement)  on StackOverFlow describes it pretty well.
Is this also possible with log4js?

**Comment by Creative-Difficulty** [comment]
Thanks for the quick reply! Is there any way I could only print the file name and not the line?

**Comment by lamweili** [comment]
As documented in [Pattern format](https://log4js-node.github.io/log4js-node/layouts.html), you can form your format specifiers from the list of available specifiers.
