### ISSUE TITLE
Setting log level/appender

### ISSUE THREAD

**Issue by macpie** [log4js-node/log4js-node#131]
Hello,

I am trying to set a level per appender. It says in some of the examples that you can add a level option to an appender but it doesn't seem to work. I might be doing it wrong too.

Here is my code:

```
    var log4js = require('log4js'),
        config = {
            'appenders': [
                {
                    'type': "file",
                    'filename': "log/paybackme.log",
                    'level': "warn"
                },
                {
                    'type': "console",
                    'level': "trace"        
                }
            ],
            'replaceConsole': true,
        };
    log4js.configure(config);
    var log = log4js.getLogger();
```

Thank you!

**Comment by KahiroKoo** [comment]
The link is 404 now.

**Comment by nomiddlename** [comment]
Try this: https://github.com/nomiddlename/log4js-node/blob/master/test/vows/with-logLevelFilter.json

**Comment by KahiroKoo** [comment]
Thanks @nomiddlename . So, if I want to assign a special level to a appender, I should set it's type  as 'logLevelFilter', and  add a appender with real output type in it. Is it right?

**Comment by dfernandezm** [comment]
It is 404 the link

**Comment by nomiddlename** [comment]
Try this: https://github.com/nomiddlename/log4js-node/blob/v1.1.1/test/vows/with-logLevelFilter.json

**Comment by guptanidhi** [comment]
Category attribute is not working in appenders.
