### ISSUE TITLE
Doesn't install, compile or run in properly

### ISSUE THREAD

**Issue by radiantone** [log4js-node/log4js-node#1310]
WARNING  Compiled with 3 warnings                                                                                                                                           7:57:28 AM

 warning  in ./node_modules/log4js/lib/appenders/index.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/log4js/lib/appenders/index.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/log4js/lib/clustering.js

Module not found: Error: Can't resolve 'cluster' in '... app/node_modules/log4js/lib'

**Comment by lamweili** [comment]
Are you running in Node.js? Would need more information on your environment.

**Comment by lamweili** [comment]
You are not using it in Node.js but in Nuxt/Vue/webpack? 

In any case, it's a warning and not an error.
A bundle should still be produced. 

You might want to see #1050 for possible solutions (which sadly no one ever got back on).

**Comment by radiantone** [comment]
I am using it in node. It's a Vue app, and of course, it does get bundled. It causes serious exception and the app doesn't load at all, so it doesn't work.

**Comment by lamweili** [comment]
Yup, it's not running on backend in vanilla Node.js. Refer to #1050 (last comment if I recall correctly) to specify the details for the webpack and get back with your findings.

**Comment by lamweili** [comment]
Yup, it's not running on backend in vanilla Node.js. Refer to #1050 (comment) (last comment if I recall correctly) to specify the details for the webpack and get back with your findings.

**Comment by lamweili** [comment]
Did that resolve your issue?

**Comment by lamweili** [comment]
@radiantone Did that resolve your issue?

**Comment by lamweili** [comment]
@radiantone?

**Comment by lamweili** [comment]
@radiantone?

**Comment by lamweili** [comment]
Closed due to extended period of inactivity.
