### ISSUE TITLE
Passing logger between files

### ISSUE THREAD

**Issue by Creative-Difficulty** [log4js-node/log4js-node#1311]
So I would like to pass my logger between different `.js` files after initialising it. I tried `export const logger = log4js.getLogger("default");`, but I have to configure it after initialising it:
```js
//...
const logger = log4js.getLogger("default");
const LoggerConfig = await initLogger(); //<—— My custom function, which returns a valid logger config
log4js.configure(LoggerConfig)
//...
```
And then the "exported" instance doesn't get configured.
Am I missing something? Is there any way to do this? In the original log4j you can easily do this if your method is `public`.
Thanks for any help!

**Comment by lamweili** [comment]
Can we have a more complete code snippet, namely, the placement of the `export` portion?

> `export const logger = log4js.getLogger("default");`

I believe this is an invalid syntax.

**Comment by lamweili** [comment]
I tested and it works.

Perhaps you can provide a more complete code snippet, namely, the placement of the `export` portion?
You can strip it down further and hard-code the `loggerConfig` if you wish, to minimize complexity for a simple test.

On the other hand, I believe this is an invalid syntax:
> `export const logger = log4js.getLogger("default");`

**Comment by Creative-Difficulty** [comment]
Oh, Sorry. My Bad. I have multiple loggers and oversaw something. Thanks for the quick help, though!
