### ISSUE TITLE
Issues installing log4js-node using npm

### ISSUE THREAD

**Issue by bapoorva** [log4js-node/log4js-node#1315]
Hi,

I am trying to install [shiny-server](https://github.com/rstudio/shiny-server) for my  [R shiny app](https://github.com/rstudio/shiny). I got an error that log4js is a missing dependency. I tried to install it using `npm install log4js` and Im getting the following error

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/jcheng5/sockjs-client.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-24T19_40_43_252Z-debug.log
```

In fact im getting this error for anything I try to install using npm. How do i fix the github issue.

**Comment by lamweili** [comment]
> In fact im getting this error for anything I try to install using npm. How do i fix the github issue.

I believe this is your npm issue since it occurs for anything you try to install

It does look like sockjs-client or your login credentials (private/public key) is invalid.

I'm sorry but there's nothing much we can do here at `log4js`.
