### ISSUE TITLE
log4js log rotation is not working

### ISSUE THREAD

**Issue by curious-user** [log4js-node/log4js-node#1320]
using  "log4js": "6.3.0",

when max log size is reached then , gz is created and new file is created but that has same old logs and new logs are not getting added ,  and on terminating the application the new log file gets deleted and only gz file exists with only logs that were in old file so all new logs are not logged.
What should I do?

**Comment by lamweili** [comment]
Hi, your code snippet is incomplete:
- the `log4js.configure()` portion is missing.
- is the filename indeed `''` (empty)?

**Comment by lamweili** [comment]
Hi, your code snippet is incomplete:
- the `log4js.configure()` portion is missing.
- is the filename indeed `''` (empty)?

I tested with a proper `log4js.configure()` and a filename and it works without issue on `log4js@6.3.0`.

**Comment by lamweili** [comment]
Hi, your code snippet is incomplete:
- the `log4js.configure()` portion is missing.
- is the filename indeed `''` (empty)?

I tested with a proper `log4js.configure()` and a filename and it works without issue on `log4js@6.3.0`.
You should have up to 6 files by default (1 active file and 5 backup `.gz` files).

You might want to try setting the following individually before mixing them together:
- `maxLogSize: 1` to test for the rolling by size
   \>=6 messages, you should get 6 files
- `datePattern: yyyy-MM-dd-hh-mm-ss` to test for rolling by date
   1 message per second for >=6 seconds, you should get 6 files

**Comment by lamweili** [comment]
```js
var log4js = require('log4js')

var fileType = 'file';
var datePattern = '.yyyy-MM-dd-hh-mm-ss'; // edited to every second
var layoutPattern = '[%d{ISO8601}] [%p] [%c]- %m';

function getLogConfig() {
  return {
    type: fileType,
    filename: 'testLogging', // edited to testLogging.log
    pattern: datePattern,
    maxLogSize: 1,           // edited to roll everytime it's logged (1 byte)
    compress: false,
    layout: {
      type: 'pattern',
      pattern: layoutPattern,
    },
  };
}

// added missing portions
log4js.configure({
  appenders: {
    out: getLogConfig(),
  },
  categories: { default: { appenders: ["out"], level: "info" } },
})

var logger = log4js.getLogger();
setInterval(function() {
  for (var i = 1; i < 10; i++) {
    logger.info(`testing ${i}`);
  }
}, 1000)
```

This works.

**Comment by lamweili** [comment]
The follow code works:

```js
var log4js = require('log4js');

var fileType = 'file';
var datePattern = '.yyyy-MM-dd-hh-mm-ss'; // edited to every second
var layoutPattern = '[%d{ISO8601}] [%p] [%c]- %m';

function getLogConfig() {
  return {
    type: fileType,
    filename: 'testLogging', // edited to testLogging.log
    pattern: datePattern,
    maxLogSize: 1,           // edited to roll everytime it's logged (1 byte)
    compress: false,
    layout: {
      type: 'pattern',
      pattern: layoutPattern,
    },
  };
}

// added missing portions
log4js.configure({
  appenders: {
    out: getLogConfig(),
  },
  categories: { default: { appenders: ["out"], level: "info" } },
})

var logger = log4js.getLogger();
setInterval(function() {
  for (var i = 1; i < 10; i++) {
    logger.info(`testing ${i}`);
  }
}, 1000);
```

**Comment by lamweili** [comment]
@curious-user Any updates?

**Comment by lamweili** [comment]
Let me know if you are still experiencing issues.

**Comment by lamweili** [comment]
@curious-user Let me know if you are still experiencing issues.
