### ISSUE TITLE
Maxlogsize and compress cannot be configured together

### ISSUE THREAD

**Issue by Abbyzhoum** [log4js-node/log4js-node#1324]
Hi, I had a problem！

My log service requirement is to write files every hour, the maximum file size is 10Mb, and compression is supported. When I use maxlogsize and compress, I found a problem. Compressing old files also deletes old files, but the time is still Within this hour, the service reports an error.

### Here is my config file:
```
{
    appenders: {
        dateFile: {
            type: 'dateFile',
            filename: `./logs/${hostName}/logs/client`,
            pattern: 'yyyy-MM-dd-hh.log',
            maxLogSize: 20 * 1024 * 1024,   // 20 MB
            compress: true,    
            daysToKeep: 30, 
            encoding: "utf-8",
            alwaysIncludePattern: true  
        },
        out: {
            type: 'stdout'  
        }
    },
    categories: {
        default: { appenders:  ['out', 'dateFile'] , level: config.logLevel },
    }
}
```

If there is another way, please let me know？
Thanks.

![微信图片_20220923152846](https://user-images.githubusercontent.com/38661489/191911204-86bd953a-07f9-4d35-953c-6a74013fd9fb.png)
![微信图片_20220923152843](https://user-images.githubusercontent.com/38661489/191911208-98b4ca22-23dc-4998-813d-d66504bd731e.png)
![微信图片_20220923152837](https://user-images.githubusercontent.com/38661489/191911211-28ffc6c1-d630-42da-9c98-222187962d78.png)

**Comment by lamweili** [comment]
Hi @Abbyzhoum, did you manage to resolve it?
Do you mind sharing what happened?

**Comment by lamweili** [comment]
@Abbyzhoum?

**Comment by lamweili** [comment]
@Abbyzhoum?
