### ISSUE TITLE
Coloured pattern

### ISSUE THREAD

**Issue by DevLomoSE** [log4js-node/log4js-node#1337]
#question
is there any way to configure a custom pattern and add/make it colored output?

**Comment by lamweili** [comment]
Please refer to the [Pattern format](https://log4js-node.github.io/log4js-node/layouts.html).
`%[` and `%]` will start and end a coloured block.

The default is `%[[%d] [%p] %c - %]%m` (coloured in console) which translates to:
`[2022-07-15T00:41:10.199] [WARN] default - hello` <-- Every character before the word `hello` is in yellow.
`[2022-07-15T00:41:10.199] [ERROR] default - world` <-- Every character before the word `world` is in red.

For a custom pattern, such as to include the file name, you have to first `enableCallStack` or `logger.useCallStack = true;`.

Specifying the pattern `%[[%d] [%-5p] [%f{3}:%l:%o] %c - %]%m` (coloured in console) translates to:
`[2022-07-15T00:50:15.223] [WARN ] [parent1\parent2\test.js:16:8] default - hello`
`[2022-07-15T00:50:15.223] [ERROR] [parent1\parent2\test.js:17:8] default - world`

```js
const log4js = require('log4js');
log4js.configure({
  appenders: {
    out: {
      type: "stdout",
      layout: {
        type: "pattern",
        pattern: "%[[%d] [%-5p] [%f{3}:%l:%o] %c - %]%m"
      }
    }
  },
  categories: {
    default: { appenders: ["out"], level: "info", enableCallStack: true }
  }
});

const logger = log4js.getLogger();
logger.warn("hello");
logger.error("world");
```

**Comment by DevLomoSE** [comment]
My bad, thanks for the help.

pattern: "%[ %d  [%p] ^[35m[%z]^] %[ --- [%M] %f{3}:%l  : %]%m"

```
2022-10-12T18:19:40.185  [INFO] [79790] --- [<anonymous>] app/scripts/Server.js:98  : BeautyMe app started at: http://localhost:8001
```

it will make [79790] output as CYAN. this type of combination was what i looking for.

**Comment by lamweili** [comment]
I tried your pattern: `pattern: "%[ %d [%p] ^[35m[%z]^] %[ --- [%M] %f{3}:%l : %]%m"`

I got something like this and it doesn't output the `[3144]` as `CYAN`.
<img src="https://user-images.githubusercontent.com/29530649/195498160-b6844ec0-da41-4d10-bffa-6b6c735c6d67.png" width="600px"></img>

@DevLomoSE, does your provided pattern work for you? 
Or do you mean the current `log4js-node` doesn't support the feature?

**Comment by DevLomoSE** [comment]
it worked for me, 
the appender config is:
```
appenders: {
    out: {
        type: "file",
        filename: "file.log",
        layout: {
            type: "pattern",
            pattern: "%[ %d  [%p] ^[[35m[%z]^[] %[ --- [%M] %f{3}:%l  : %]%m"
        }
    }
},
```

and i got this:
![image](https://user-images.githubusercontent.com/42560919/195500889-254863f0-acb9-498b-80b7-0f7a80e62e4f.png)
