### ISSUE TITLE
multiFile with timeout param would cause crash

### ISSUE THREAD

**Issue by tjpgt** [log4js-node/log4js-node#1352]
code:
```javascript
const log4js = require('log4js');

const extension = '.log';
log4js.configure({
  appenders: {
    multi: {
      type: 'multiFile', base: '.', property: 'categoryName', extension,
      maxLogSize: 60, timeout: 1000,
      layout: { type: 'messagePassThrough' }
    }
  },
  categories: {
    default: { appenders: ['multi'], level: 'debug' }
  }
});

const logger=log4js.getLogger('test');
setInterval(()=>{
    logger.log(new Date())
},1000)
```
After a while, I got error and  crash:

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, stat '/home/ccw/test/testlog4js/test.log.1'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/ccw/test/testlog4js/test.log.1'
}

```

log4js version: 6.7.1

And if you make the timeout in log4js config and the timeout in setInterval different, it would not crash.

**Comment by lamweili** [comment]
The `streamroller` library has been updated from `3.1.3` to `3.1.4` which fixes this issue.
No release is required on `log4js-node` as it uses `streamroller@^3.1.3`, which should automatically update to `3.1.4`.

Please let me know if the issue persists or if it resolves the issue. Thanks!

**Comment by tjpgt** [comment]
> The `streamroller` library has been updated from `3.1.3` to [`3.1.4`](https://github.com/log4js-node/streamroller/blob/v3.1.4/CHANGELOG.md) which fixes this issue. No release is required on `log4js-node` as it uses `streamroller@^3.1.3`, which should automatically update to [`3.1.4`](https://github.com/log4js-node/streamroller/blob/v3.1.4/CHANGELOG.md).
> 
> Please let me know if the issue persists or if it resolves the issue. Thanks!

It would not crash now. But, there is another problem...

Using my code above, after a while, I expect it should generate 5 or 6 log file. For example, test.log, test.log.1, test.log.2 ... test.log.5. But what actually happens is, it randomly deletes the log file, only keeps the test.log, test.log.1(and maybe some other files).

like:

![image](https://user-images.githubusercontent.com/29495241/209740219-f866f2b2-5fc0-445a-ab13-d1484cfd6e13.png)

**Comment by lamweili** [comment]
Would you mind filing another issue for this?

**Comment by tjpgt** [comment]
> Would you mind filing another issue for this?

ok, here it is: https://github.com/log4js-node/log4js-node/issues/1354
