### ISSUE TITLE
Module "log4js" has no default export

### ISSUE THREAD

**Issue by Julius-Babies** [log4js-node/log4js-node#1356]
Hi, I installed log4js via `npm i log4js` and tried importing it into my TypeScript file (`import log4js from "log4js";`). The example doesn't work for me, it gives me this error:

```
Module '"/home/user/test/node_modules/log4js/types/log4js"' has no default export
```

Did I something wrong or is it an issue with the package?

Thank you!

**Comment by lamweili** [comment]
Please refer to the [TypeScript section under README.md](https://github.com/log4js-node/log4js-node/blob/cb5e44e30332a1df21baca7d38344fe6c3f24b6a/README.md#typescript).

**Comment by lamweili** [comment]
Please refer to the [TypeScript section under README.md](https://github.com/log4js-node/log4js-node/blob/cb5e44e30332a1df21baca7d38344fe6c3f24b6a/README.md#typescript).

You should be able to run the following code from there.
I added the stdout appender for visibility in the terminal.

<img src="https://user-images.githubusercontent.com/29530649/210613055-59803dba-5ed6-42ee-94a5-b42da3418207.png" width="600" />

**Comment by lamweili** [comment]
@Julius-Babies, any updates?

**Comment by lamweili** [comment]
@Julius-Babies, any updates?

For simplicity, you can download this: [`test.zip`](https://github.com/log4js-node/log4js-node/files/10424230/test.zip)
Unzip and run the following commands within the folder:
```
npm i
npx ts-node test.ts
```

**Comment by lamweili** [comment]
See https://github.com/log4js-node/log4js-node/issues/1360#issuecomment-1386534910

**Comment by lamweili** [comment]
Hi @Julius-Babies, did it resolve the issue?

**Comment by lamweili** [comment]
@Julius-Babies?
