### ISSUE TITLE
Cannot find module log4js with TypeScript

### ISSUE THREAD

**Issue by 2277509846** [log4js-node/log4js-node#1360]
Use the import method to import log4js, execute the tsc command, and the error "Cannot find module 'log4js'" will be reported, but the compiled js file can run normally.

error TS2792: Cannot find module 'log4js'
index.ts:
`import log4js from "log4js";
// log4js.configure({
//   appenders: { cheese: { type: "file", filename: "cheese.log" } },
//   categories: { default: { appenders: ["cheese"], level: "error" } }
// });

const logger = log4js.getLogger();
logger.level = "debug";
logger.debug("Some debug messages");`
![image](https://user-images.githubusercontent.com/52586868/213095409-7e3e8ebf-c476-411b-9add-204a4ef8f8cd.png)

**Comment by lamweili** [comment]
It seems that `ts-node` is works for runtime. But `tsc` fails to build.

You can download this: [`test.zip`](https://github.com/log4js-node/log4js-node/files/10424230/test.zip)
Unzip and run the following commands within the folder:
```bash
npm i
```

```bash
npx ts-node test.ts # works
```
```bash
npx tsc test.ts     # fails
```

Switching to `import * as log4js from 'log4js';` resolves the issue.

**Comment by lamweili** [comment]
It seems that `ts-node` is works for runtime. But `tsc` fails to build.

You can download this: [`test.zip`](https://github.com/log4js-node/log4js-node/files/10442622/test.zip)
Unzip and run the following commands within the folder:
```bash
npm i
```
```bash
npx ts-node test.ts # works
```
```bash
npx tsc test.ts     # fails
```

Switching to `import * as log4js from 'log4js';` resolves the issue.

**Comment by 2277509846** [comment]
How to write the tsconfig.json file so that tsc can find log4js.d.ts. This is the tsconfig.json file:
{
  "compilerOptions": {
    /* Language and Environment */
    "target": "es2020",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    /* Modules */
    "module": "es2020",                                /* Specify what module code is generated. */
    "outDir": "./dist",                                   /* Specify an output folder for all emitted files. */
    "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */
    /* Type Checking */
    "strict": true,                                      /* Enable all strict type-checking options. */
    "skipLibCheck": true
  }
}
![image](https://user-images.githubusercontent.com/52586868/213104906-391899c3-0925-4c27-8067-cadeb4135d58.png)

**Comment by lamweili** [comment]
I have included your `tsconfig.json` into [`replaced.zip`](https://github.com/log4js-node/log4js-node/files/10443393/replaced.zip).
Unzip and run the following commands within the folder:
```bash
npm i
npx tsc
```

**Comment by 2277509846** [comment]
It seems that these two configuration options cause the error.
{
  "compilerOptions": {
  "target": "nodenext",// cause error
  "module": "nodenext",// cause error
  "outDir": "./dist",
  "esModuleInterop": true,
  "forceConsistentCasingInFileNames": true,
  "strict": true,
  "skipLibCheck": true
  }
}

**Comment by lamweili** [comment]
After removing the comments in `tsconfig.json`, both `es2020` and `es2015` (for `target` and `module`) have errors.

**Comment by lamweili** [comment]
After removing the comments in `tsconfig.json`, both `es2020` and `es2015` (for `target` and `module`) have errors. 

You will need to add `"moduleResolution": "node"`.

es2015
-
```diff
  {
    "compilerOptions": {
      "target": "es2015",
      "module": "es2015",
      "outDir": "./dist",
      "esModuleInterop": true,
      "forceConsistentCasingInFileNames": true,
+     "moduleResolution": "node",
      "strict": true,
      "skipLibCheck": true
    }
  }
```

es2020
-
```diff
  {
    "compilerOptions": {
      "target": "es2020",
      "module": "es2020",
      "outDir": "./dist",
      "esModuleInterop": true,
      "forceConsistentCasingInFileNames": true,
+     "moduleResolution": "node",
      "strict": true,
      "skipLibCheck": true
    }
  }
```

**Comment by 2277509846** [comment]
My problem has been solved. Thank you very much
