### ISSUE TITLE
logs can't be written to logfile

### ISSUE THREAD

**Issue by yviansu** [log4js-node/log4js-node#1371]
I configure `logger` in `A.ts`, when I run `logger.info('xx)` in `A.ts`, the `xx` will be both written to console and file.
However, when I import the logger from `A.ts` to `B.ts`, when I run `logger.info('yy')` in `B.ts`, the `yy` will be only written to console. 

Why is this happening? And How to fix this?

The config is:
```
appenders: {
        console: {
            type: 'console',
        },
        file: {
            type: 'dateFile',
            filename: `${logDirPath}/output.log`,
            alwaysIncludePattern: true,
            pattern: 'yyyy-MM-dd',
            keepFileExt: true,
            numBackups: 3,
        },
        errorFile: {
            type: 'dateFile',
            filename: `${logDirPath}/error.log`,
            alwaysIncludePattern: true,
            numBackups: 3,
            keepFileExt: true,
        },
    },
    categories: {
        default: {
            appenders: ['console', 'file'],
            level: 'debug',
        },
    },
```

**Comment by lamweili** [comment]
Can you zip and upload the sample project here?
You can remove all the other non-relevant portions.

**Comment by yviansu** [comment]
Thanks for your quick reply, I have remove non-relevant codes and created a new repo: https://github.com/yviansu/logSample.git

In this repo, After running `npm run build`, when I run `node build/src/entry.js`, I can only see the logs in console, and nothing will be put into log file.

I guess this is because I throw an error after invoking `Logger.xx`, Will the reason for errors be this？

**Comment by lamweili** [comment]
You are catching the thrown error and doing a `process.exit(1)`. 
It kills off the Node.js process, while it might be still trying to write to the hard-disk.

**Comment by lamweili** [comment]
You are catching the thrown error and doing a `process.exit(1)`. 
It kills off the Node.js process that is still trying to write to the hard disk.
