### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'native')

### ISSUE THREAD

**Issue by MUmeshKumar** [log4js-node/log4js-node#1372]
Hi,

When i try to import log4js in my app.js i'm getting following error -

**Uncaught TypeError: Cannot read properties of undefined (reading 'native')**
    at ./node_modules/log4js/node_modules/fs-extra/lib/fs/index.js (index.js:107:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/log4js/node_modules/fs-extra/lib/index.js (index.js:6:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object.<anonymous> (RollingFileWriteStream.js:2:1)
    at ./node_modules/log4js/node_modules/streamroller/lib/RollingFileWriteStream.js (RollingFileWriteStream.js:338:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/log4js/node_modules/streamroller/lib/index.js (index.js:2:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object.<anonymous> (file.js:3:1)
    at ./node_modules/log4js/lib/appenders/file.js (file.js:154:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object.<anonymous> (index.js:17:1)
    at ./node_modules/log4js/lib/appenders/index.js (index.js:182:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/log4js/lib/log4js.js (log4js.js:27:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (appenders sync:9:1)
    at ./src/App.js (App.js:332:1)

My setup configuration -
**React - 17.0.2
Node - v16.19.0
npm - 8.19.3
log4js - 6.8.0**

I see version of **fs-extra** mentioned in the **log4js/package.json is ^11.1.0** but in the log4js/node_modules/fs-extra/package.json says **8.1.0**
<img width="841" alt="image" src="https://user-images.githubusercontent.com/125536990/222688986-fa835e1b-f28c-48a0-a631-bd67cea32203.png">

Even after modifying the fs-extra module with the latest version 11.1.0, still error persists.

I also have seen similar error in Angular(https://github.com/log4js-node/log4js-node/issues/1225) followed the steps you mentioned. still facing same problem.
Can you please let me know what could be the possible reason for this error? 

Thanks for your help in advance!

Best regards,
-Umesh

**Comment by lamweili** [comment]
> **Uncaught TypeError: Cannot read properties of undefined (reading 'native')**
> at ./node_modules/log4js/node_modules/fs-extra/lib/fs/index.js (index.js:107:1)

Seems to point at the following [if statement](https://github.com/jprichardson/node-fs-extra/blob/8.1.0/lib/fs/index.js#L107).
```js
// fs.realpath.native only available in Node v9.2+
if (typeof fs.realpath.native === 'function') {
  exports.realpath.native = u(fs.realpath.native)
}
```

Then again, it's really hard to figure out what's wrong. 
Are you trying to use it on a browser?

**Comment by MUmeshKumar** [comment]
> And seems to say your fs.realpath === undefined, therefore unable to reach native 

yes, fs.realpath is undefined
> Are you trying to use it on a browser?

After importing i tried to load the app in Chrome browser

> Any issues with your webpack.config.js?

No issues with webpack.config.js.

**Comment by lamweili** [comment]
Are you trying to use file appender in a browser? That won't work. #849 #968

**Comment by MUmeshKumar** [comment]
I have not used any file appenders, i'm getting error as soon after importing log4js to the app

React - 17.0.2
Node - 16.19.0
npm - 8.19.3
log4js - 6.8.0

This issue can be reproduced with below steps -

1. npx create-react-app my-app
2. if you get compile issu from graceful-fs module then follow below steps
     1. Degrade react-script from 5.x to 4.0.3
     2. Remove package-lock.json
     3. npm install
3. import log4js in App.js

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/125536990/223042751-4399801f-1837-4d4b-8b99-780c9256c67d.png">


<img width="754" alt="image" src="https://user-images.githubusercontent.com/125536990/223043181-50ec17d3-6503-4a80-96f0-ce315e7e2fb4.png">

**Comment by lamweili** [comment]
I don't think you can use `log4js` in a browser (#1270 & #1288), it's not meant to be.
You might need to use `browserify` for `log4js` on the browser.

There was PR #1023 in the works at the end of #968 but unfortunately, it stopped.

**Comment by lamweili** [comment]
I don't think you can use `log4js` in a browser (#1270 & #1288), it's meant to be used on server-side.
You might need to use `browserify` for `log4js` on the browser.

There was PR #1023 in the works at the end of #968 but unfortunately, it stopped.

**Comment by lamweili** [comment]
Thanks to @aellerton who came up with PR #1374 which resolved the issue.
Will be released in `log4js@6.8.1`.

**Comment by lamweili** [comment]
Thanks to @aellerton who came up with PR #1374 which resolved the issue.
Will be released in `log4js@6.9.0`.

**Comment by MUmeshKumar** [comment]
Thanks for the latest version. It solved the above issue. But with the latest version i'm facing different issue. 
<img width="660" alt="image" src="https://user-images.githubusercontent.com/125536990/223394801-1d6e0295-c4ee-4795-b7d3-f320da7f5b30.png">
<img width="660" alt="image" src="https://user-images.githubusercontent.com/125536990/223395044-ff25d9ae-02fb-48d1-a2ca-9ed087a77daf.png">


Can you please help?

Thanks,
-Umesh

**Comment by aellerton** [comment]
Are you able to share your log4js config by any chance?

Can you also do "console.log(appenderModule)" somewhere in there?

**Comment by lamweili** [comment]
@MUmeshKumar?

**Comment by MUmeshKumar** [comment]
Sorry for the late reply.

I used below log4js config -
log4js.configure({
  appenders: { abc: { type: "file", filename: "abc.log" } },
  categories: { default: { appenders: ["abc"], level: "error" } },
});

When i checked "appenderModule" we are getting empty object.

I understand from the previous PR, we cannot use any appenders in the browser. Is there any other way to log?

**Comment by lamweili** [comment]
I believe it is because of `file` appender. The browser doesn't come with Node.js libraries, so it cannot write to a log file.

You should be able to use `console` instead.

**Comment by lamweili** [comment]
I believe it is because of `file` appender. The browser doesn't come with Node.js libraries, so it cannot write to a log file.

You should be able to use `console` instead:

```
log4js.configure({
  appenders: { abc: { type: "console", filename: "abc.log" } },
  categories: { default: { appenders: ["abc"], level: "error" } },
});
```

Try it and see if it works.

**Comment by MUmeshKumar** [comment]
Sure. Thanks for the reply @lamweili @aellerton

**Comment by lamweili** [comment]
@MUmeshKumar, is your issue now resolved? Is it working now?

**Comment by aellerton** [comment]
Try the 'basic' layout with console, i.e.

{ type: "console", layout: { type: "basic" } }

Let us know?

**Comment by MUmeshKumar** [comment]
I've tried this - Logs are printing in browser console and no file has been created 
```
log4js.configure({
  appenders: { abc: { type: "console", filename: "abc.log" } },
  categories: { default: { appenders: ["abc"], level: "error" } },
});
```
Same goes with `{ type: "console", layout: { type: "basic" } }` logs are printing fine in browser console

**Comment by lamweili** [comment]
Yup, because a browser does not have Node.js libraries to write to a file.

As for the layout type, it defaults to `colouredLayout` if not specified.
I can't remember if colours work in the browser console. @MUmeshKumar, maybe you can let us know?

Nevertheless, setting it to `basic` (if any compatibility concerns) will strip off colours.

**Comment by MUmeshKumar** [comment]
You are right, setting layout to basic strips off the colours -
Without basic setting -
<img width="650" alt="image" src="https://user-images.githubusercontent.com/125536990/224238487-75961084-6e0e-4b58-8dd0-791528087b5b.png">

With basic setting -
<img width="650" alt="image" src="https://user-images.githubusercontent.com/125536990/224238203-4d57ce30-9a9f-44ce-8b45-5d9902d43124.png">

**Comment by lamweili** [comment]
@MUmeshKumar Is everything fine now?

**Comment by MUmeshKumar** [comment]
Yes. Thanks for clearing out the queries. @lamweili
