### ISSUE TITLE
defaultParseCallStack can't parse the stack

### ISSUE THREAD

**Issue by amakarev** [log4js-node/log4js-node#1377]
Hello.
I noticed that my extension stopped working. 
I found that the defaultParseCallStack returns null, which results in an error.
Here is the commit that led to it:
https://github.com/log4js-node/log4js-node/commit/7922e8257806811666c1d4cf6774b4426276ea16
Everything works with the old regular expression
An expression that fails to parse with the new regex:
`"\tat c:\\repos\\vscode-inner\\frameworks.ide.vscode.extensions.oneapi-devcloud-connector\\out\\extension.js:28:16 "`

**Comment by lamweili** [comment]
Can I confirm that it begins with a tab and ends with a space?

**Comment by lamweili** [comment]
Can I confirm that it begins with a tab and ends with a space? Which version of Node.js?

**Comment by lamweili** [comment]
Ok, fixing it right away.

**Comment by lamweili** [comment]
Released in `log4js@6.9.1`.

**Comment by amakarev** [comment]
Thank you!

**Comment by lamweili** [comment]
It should be out on npm now. Let me know if it resolves your issue.
