### ISSUE TITLE
backups day count not working as it as

### ISSUE THREAD

**Issue by sathish869** [log4js-node/log4js-node#1396]
This is what my config of log4js is

const log4jsConfig =
{
    appenders: {
        stdout: { type: "stdout", layout: layout },
        dailylog: {
            type: "dateFile",
            mode: 0o664,
            filename: logFilePath,
            pattern: ".yyyy-MM-dd",
            backups: 8,
            compress: true,
            layout: {
                type: "pattern",
                pattern: "%d %p %c - %m%n"
            }
        }
    },
    categories: {
        default: {
            appenders: ["dailylog"],
            level: originalLogLevel
        }
    }
};

The problem is I am expecting 1 hot file(Current log file) and 8 backup files, but i am getting the only one back up file , then the 3rd day it is overwritten automatically, what is the issue actually ??

**Comment by lamweili** [comment]
Should `numBackups` instead of `backups` for `dateFile` appender. 

_(src: https://log4js-node.github.io/log4js-node/dateFile.html) _

**Comment by lamweili** [comment]
For `dateFile` appender, options key should be `numBackups` instead of `backups`.

_(src: https://log4js-node.github.io/log4js-node/dateFile.html)_

**Comment by sathish869** [comment]
Thank you so much, it working as expected
