### ISSUE TITLE
"maxLogSize" BUG: overwrite currently archived files

### ISSUE THREAD

**Issue by Wonder233** [log4js-node/log4js-node#1398]
maxLogSize will only generate a gz archive file. If the maximum log size is reached later, the previous archive will be covered.
for example:
```
smh: {
    type: 'dateFile',
    filename: path.join(logPath, './smh.log'),
    compress: true,
    keepFileExt: true,
    maxLogSize: 10 * 1024,
    layout: {
      type: 'pattern',
      pattern: '[%d{yyyy-MM-dd hh:mm:ss.SSS}] [%p] %m',
    },
  },
``` 
![log4js](https://github.com/log4js-node/log4js-node/assets/8199240/dcc405bf-8cb8-4aed-98fd-d6d756528a0e)

nodejs: v16.14.0
log4js: 6.9.1

**Comment by lamweili** [comment]
This is the correct behavior.


You need to configure `numBackups` which is defaulted to `1` (excludes hot file). 

_(src:
https://log4js-node.github.io/log4js-node/dateFile.html)_

**Comment by Wonder233** [comment]
Sorry, I didn't see it, thank you for your answer
