### ISSUE TITLE
Used together with PM2, the log did not enter the corresponding file

### ISSUE THREAD

**Issue by maoweifan** [log4js-node/log4js-node#1406]
My project was launched through PM2
for example `pm2 start index.js --name server`

```js
const log4js = require("log4js");

const loggerFactory = (category) => {
    const logger = log4js.getLogger(category);
    logger.level = "debug";
    return logger;
}

const logger = loggerFactory('debug');

logger.log('i am log message')
logger.debug('i am debug message')
logger.info('i am info message')
logger.warn('i am warn message')
logger.error('i am error message')

console.log('console.log')
console.debug('console.debug')
console.info('console.info')
console.warn('console.warn')
console.error('console.error')
```

The problem is:
When PM2 starts, it will take over the log files on the console and input them into the PM2 management point log. I used this method, and when PM2 starts, two files will be generated for the project

```shell 
cd ~/.pm2/logs
```

<img width="214" alt="image" src="https://github.com/log4js-node/log4js-node/assets/51221758/0b63acdc-28c5-4e5e-90f3-03b7ffe9e63d">

But only `console.warn` and `console.error` are written to chat `server-error.log`
<img width="472" alt="image" src="https://github.com/log4js-node/log4js-node/assets/51221758/3268a168-a000-4bf6-b023-c624558582dd">

All others have been written to `server-out.log`
<img width="944" alt="image" src="https://github.com/log4js-node/log4js-node/assets/51221758/8a2f94e3-51b4-4fc1-840d-5d68dd8a1f24">

All logs of log4js have been written to `server-out.log`, and what I want is that the behavior of log4js is also the same as that of `console`, writing warnings and errors to `server-error.log` in pm2. So, what should I do?

**Comment by maoweifan** [comment]
What I want
```js
log4js.debug -> pm2 out.log
log4js.log(log4js.info) -> pm2 out.log

log4js.warn -> pm2 error.log
log4js.error -> pm2 error.log
```

**Comment by lamweili** [comment]
Can you provide your `log4js` configuration?

**Comment by lamweili** [comment]
Hi, `log4js` follows the `log4j` logging level convention. It is hierarchical which is quite an industry standard.
`ALL < TRACE < DEBUG < INFO < WARN < ERROR < FATAL < MARK < OFF`

Hence, if your level is set to `debug`, you will see everything above `debug`.
That includes `info`, `warn`, `error`, `fatal`, `mark`, `off`.

You can read more here:
https://log4js-node.github.io/log4js-node/api.html

Vertical header displays the level of the log event.
Horizontal header shows the logging level configuration.
![image](https://github.com/log4js-node/log4js-node/assets/29530649/c64015ca-638f-4dbc-9fbc-8799adc4987f)
_(src: https://www.javatpoint.com/log4j-logging-levels)_

**Comment by lamweili** [comment]
Hi, `log4js` follows the `log4j` logging level convention. It is hierarchical which is quite an industry standard.
This is also the same implementation in browsers; log level filtering under `Developer tools (F12)`.

`ALL < TRACE < DEBUG < INFO < WARN < ERROR < FATAL < MARK < OFF`

Hence, if your level is set to `debug`, you will see everything above `debug`.
That includes `info`, `warn`, `error`, `fatal`, `mark`, `off`.

You can read more here:
https://log4js-node.github.io/log4js-node/api.html

Vertical header displays the level of the log event.
Horizontal header shows the logging level configuration.
![image](https://github.com/log4js-node/log4js-node/assets/29530649/c64015ca-638f-4dbc-9fbc-8799adc4987f)
_(src: https://www.javatpoint.com/log4j-logging-levels)_

**Comment by lamweili** [comment]
PM2, however, is different. It has only 4 types of log levels (`debug`, `info`, `warn`, `error`) and 3 types of files:

- `error_file` only contains `warn` and `error`
- `out_file` only contains `debug` and `info`
- `log_file` contains everything (`debug`, `info`, `warn`, `error`)

Field | Type | Example | Description
-- | -- | -- | --
error_file | (string) |   | error file path (default to $HOME/.pm2/logs/<app name>-error-<pid>.log)
out_file | (string) |   | output file path (default to $HOME/.pm2/logs/<app name>-out-<pid>.log)
log_file | (string) |   | file path for both output and error logs (disabled by default)

_(src: https://pm2.keymetrics.io/docs/usage/log-management)_

So, if you want to achieve the kind of PM2 log level implementation, you would need to use `logLevelFilter` appender.
In that, you can specify the `level` (minLevel) and the `maxLevel`.
https://log4js-node.github.io/log4js-node/logLevelFilter.html
