### ISSUE TITLE
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by sunhx-shx** [log4js-node/log4js-node#1412]
please instead use _headers of getHeaders. other wise terminal will appears the waring  ->    DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

more details can read here:     https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames

for perfect code experience,  Thank You!!

<img width="929" alt="截屏2024-01-15 16 46 41" src="https://github.com/log4js-node/log4js-node/assets/77148584/d4f1c77d-aa63-4097-9a93-70bd4ea35e2f">

**Comment by lamweili** [comment]
Which part? PR is welcomed!

**Comment by lamweili** [comment]
Which part causes this? Can you run `node --trace-deprecation` to get the stacktrace?

**Comment by lamweili** [comment]
Which part causes this? I did a global search for `_headers`, and I didn't find anything. 
This doesn't seem like coming from `log4js`.

1. Can you give a sample zip file to replicate the issue?
2. Can you run `node --trace-deprecation` to get the stack trace?

**Comment by sunhx-shx** [comment]
> Which part causes this? I did a global search for `_headers`, and I didn't find anything. This doesn't seem like coming from `log4js`.
> 
> 1. Can you give a sample zip file to replicate the issue?
> 2. Can you run `node --trace-deprecation` to get the stack trace?

@lamweili        Sorry, I found that I used the _headers attribute in my code, which has nothing to do with log4js，thanks for your reply  😄

**Comment by lamweili** [comment]
Would you mind closing this issue? Thanks!
