### ISSUE TITLE
How to support scrolling by file date and file size simultaneously

### ISSUE THREAD

**Issue by xianping-yan** [log4js-node/log4js-node#1419]

**Comment by lamweili** [comment]
> Note that, from version 4.x of log4js onwards, the file appender can take any of the options for the [file appender](https://log4js-node.github.io/log4js-node/file.html) as well. So you could roll files by both date and size.

https://log4js-node.github.io/log4js-node/dateFile.html

```js
var log4js = require('log4js');

var fileType = 'file';
var datePattern = 'yyyy-MM-dd-hh-mm-ss'; // roll every second
var layoutPattern = '[%d{ISO8601}] [%p] [%c]- %m';

function getLogConfig() {
  return {
    type: fileType,
    filename: 'testLogging',
    pattern: datePattern,
    maxLogSize: 200, // to roll everytime at 200 bytes
    compress: false,
    layout: {
      type: 'pattern',
      pattern: layoutPattern,
    },
  };
}

// added missing portions
log4js.configure({
  appenders: {
    out: getLogConfig(),
  },
  categories: { default: { appenders: ["out"], level: "info" } },
})

var logger = log4js.getLogger();

// rolling by size during first 10 seconds
for (var i = 1; i < 10; i++) {
  logger.info(`testing ${i}`); // this msg is about ~100 bytes (with timestamp prefix etc)
}

// try rolling by time (after first 10 seconds)
var timeRoll = setTimeout(function() {
  setInterval(function() {
    logger.info(`testing`);
  }, 1000);
}, 10000);
```

**Comment by xianping-yan** [comment]
![image](https://github.com/log4js-node/log4js-node/assets/35319481/34d46443-3d9c-449e-b646-3bea11a610e2)
Thank you for your answer. Perhaps the document needs to be updated because the maxLogSize field is missing in 'dataFile'. I saw from the source code that this parameter is usable and verified to be feasible.

**Comment by lamweili** [comment]
It's part of the file appender configuration.
![image](https://github.com/log4js-node/log4js-node/assets/29530649/41bd8f08-cb4f-4fc0-93ce-c8ecb26a69e1)

But I agree, maybe it needs to be clearer.

**Comment by xianping-yan** [comment]
Thank you. The issue has been resolved
