### ISSUE TITLE
fileSync appender with DateRolling ?

### ISSUE THREAD

**Issue by rndmania** [log4js-node/log4js-node#227]
I found the fileSync appender that synchronous logging version in the appender directory.
It seems to support rolling by file size.
but  i want rolling by date 

Are you have a plan to support that function?

**Comment by Smurf-IV** [comment]
This will be sorted via #297 (sorry found that one first)
So this can be closed

**Comment by nomiddlename** [comment]
Closing this because you can use the file flags to turn on the 'guaranteed write' flavour of synchronous logging now. (See the node.js file docs for details)
