### ISSUE TITLE
Does log4js  layout pattern have any conversion characters for Method and Line number on the lines of log4j

### ISSUE THREAD

**Issue by SHARMASH** [log4js-node/log4js-node#245]
I would like to be able to do something like:

"layout": { 
        "type": "pattern",
        "pattern" : "%d|%-5p|%c{1}.%M[%L] %m%n"
      } 
so that the log messages also show me the method and line number. Is there a different option for method name and Line number that I'm missing?

**Comment by robdaems** [comment]
+1

**Comment by MatthewRalston** [comment]
Can one of the developers revisit this from the "trace" code? This is actually an awesome feature, common in many other log4j style loggers.

**Comment by nomiddlename** [comment]
Will possibly be fixed by PR #580

**Comment by nomiddlename** [comment]
Anybody looking at this issue would probably be interested in https://www.npmjs.com/package/log4js-extend - take a look, see if it does what you want.

**Comment by nomiddlename** [comment]
This will be fixed by PR #879

**Comment by nomiddlename** [comment]
Line number support (finally) added in log4js@4.3.0
