### ISSUE TITLE
Synchronous dateFile appenders

### ISSUE THREAD

**Issue by nokawaii** [log4js-node/log4js-node#297]
Hey,

same issue like "Is it possible to force flush the buffered logs? #159" here. Is it possible to add a synchronous appender for dateFiles too?

Many thanks for your reply!

**Comment by Smurf-IV** [comment]
I have done this, and will be creating a pull request as soon as I have the test cases done.

**Comment by Smurf-IV** [comment]
Found earlier reference #227

**Comment by Smurf-IV** [comment]
https://github.com/nomiddlename/log4js-node/pull/373

**Comment by nomiddlename** [comment]
Closing this because you can use the file flags to turn on the 'guaranteed write' flavour of synchronous logging now. (See the node.js file docs for details)
