### ISSUE TITLE
mailgun-js constructor not called in mailgun appender.

### ISSUE THREAD

**Issue by ninformations** [log4js-node/log4js-node#380]
It seems mailgun constructor is not called in mailgun appender.

`var mailgun = require('mailgun-js')({apiKey: api_key, domain: domain});`
[https://github.com/nomiddlename/log4js-node/blob/master/lib/appenders/mailgun.js](https://github.com/nomiddlename/log4js-node/blob/master/lib/appenders/mailgun.js)

hence, breaking on sending request.

**Comment by nomiddlename** [comment]
This should be fixed in 0.6.36

**Comment by nomiddlename** [comment]
I'm going to assume this was fixed by the change in 0.6.36

**Comment by WahajTeksyo** [comment]
const formData = require('form-data');
const Mailgun = require('mailgun.js');
 const mailgun = new Mailgun(formData);
            const mg = mailgun.client({username: 'api', key: 'Api' || 'key-yourkeyhere'});
            mg.messages.create('sandbox-123.mailgun.org', {
                from: "Excited User <mailgun@sandbox-123.mailgun.org>",
                to: ["test@gmail.com"],
                subject: "Hello",
                text: "Testing some Mailgun awesomness!",
                html: "<h1>Testing some Mailgun awesomness!</h1>"
            })
            .then(msg => console.log(msg)) // logs response data
            .catch(err => console.error(err)); // logs any error
            
  I use this method and when I hit submit I get error ( Mailgun is not a constructor ).

**Comment by lamweili** [comment]
@WahajTeksyo, I believe this has got nothing to do with `log4js-node`.
From what I see, it's a vanilla code with [`mailgun.js`](https://www.npmjs.com/package/mailgun.js).
