### ISSUE TITLE
Rolling file appender should keep extension

### ISSUE THREAD

**Issue by rlk833** [log4js-node/log4js-node#450]
The rolling file appender should keep the extension on the end.

Currently:

- stdout.log
- stdout.log.1
- stdout.log2

It would be nicer if it was:

- stdout.log
- stdout.1.log
- stdout.1.log

The reason is when browsing the file, many systems have trouble choosing the correct editor when it ends in a number. If they ended in the original extension the file associations of the system would work normally. The way it is now I have to intervene and select an editor/browser every time I click on one of the rolled files.

Thanks.

**Comment by allisonshaw** [comment]
@nomiddlename, any movement on this issue?

It is troublesome that the extension is changed and the file association is lost.

**Comment by nomiddlename** [comment]
Sorry, I've been working on pm2 support and changes to the multiprocess appender lately. There's only one of me, and I don't get much time to spend on this. I'd be happy to see a pull request for this though, I don't think it would be a big change. It'd have to default to the current behaviour, with a config option to change the placement of the extension.

**Comment by nomiddlename** [comment]
Thanks to @cula there's now a flag in the streamroller lib for keeping the extension. I'll update log4js' dependency and get this pushed to NPM soon.

**Comment by nomiddlename** [comment]
Published to npm in v2.3.8 - add the `keepFileExt: true` option to your file appender config and it should work. Let me know if this resolves your issue.

**Comment by nomiddlename** [comment]
I'm going to assume the new flag resolved your issue. Please re-open if this is not the case.
