### ISSUE TITLE
finding log4js.json

### ISSUE THREAD

**Issue by ghost** [log4js-node/log4js-node#47]
Hi,

I'm using etherpad-lite (https://github.com/Pita/etherpad-lite) which uses node.js and log4js-node. Due to some problem with socket code, I got a very large logfile and I realized that it was time to set up log rotation. I started to look into how this was done with log4js and I found that there is built-in logrolling, I just need to configure it. 

Great. So since the application isn't configuring this anywhere, I followed the directions and created a log4js.json file with the following content straight from the example:

```
{
  "appenders": [
    {
      "type": "file",
      "filename": "/var/log/etherpad-lite/etherpad-lite.log",
      "maxLogSize": 1024,
      "backups": 3,
      "pollInterval": 15
    }
  ]
}
```

and then I puzzled over where I was supposed to put it. The documentation says the CWD is the first place looked, so I tried to figure out where exactly the CWD was. I decided the most logical place was the CWD of the node process, so I put it there (based on the value from /proc/<pid>/cwd). It didn't seem to fire there. My current log file is larger than 1024 (by the way, what unit is that? bytes? megabytes?), so I expected it to rotate, but it didn't do anything. I plopped the log4js.json in various other locations that made less and less sense, including until I gave up.

Am I misunderstanding how this should work or is there a bug here?

thanks!

**Comment by Sadovnikov94** [comment]
@nomiddlename I have the same issue with maxLogSize. May be you can help?
`{`
`            type: "file",`
`           filename: __dirname + '/../data/' + "/smartHomeServer.log",`
`            layout: {`
`                type    : "pattern",`
`                pattern : "[%d{ISO8601}] %[%p {%x{ln}} -%]\t%m",`
`                maxLogSize: 20971520,`
`                backups: 1,`
`                tokens: {`
`                    ln : function() {`
`                        var errorStack =  (new Error).stack.split("\n");`
`                        var tempLocation = errorStack[$depth];`
`                        if ( typeof tempLocation !== 'undefined' && tempLocation ) {`
`                            return tempLocation.replace(/^\s+at\s+(\S+)\s\((.+?)([^\/]+):(\d+):\d+\)$/, ``function () {`
`                                return arguments[1] + ' ' + arguments[3] + ' line ' + arguments[4];`
`                            });`
`                        }`
`                    }`
`                }`
`            }`
`        }`

>
