### ISSUE TITLE
Type definition for configuration does not match with implementation and documentation

### ISSUE THREAD

**Issue by jimjaeger** [log4js-node/log4js-node#515]
I try to set the log4js configuration element as decribed in the documentation:
log4js.configure({
  appenders: { cheese: { type: 'file', filename: 'cheese.log' } },
  categories: { default: { appenders: ['cheese'], level: 'error' } }
});

but the type defitinion describes different format especially in the format of the IConfig elements ..
What is the correct format?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/log4js/index.d.ts
export function configure(filename: string, options?: any): void;
export function configure(config: IConfig, options?: any): void;

export interface IConfig {
  appenders: AppenderConfig[];
  levels?: { [category: string]: string };
  replaceConsole?: boolean;
}

**Comment by coderslagoon** [comment]
Same issue here, getting ugly ...

Wouldn't it make sense to have the latest typings onboard (rather than going DefinitelyTyped), given that keeping it isn't an issue for the maintainer?

**Comment by nomiddlename** [comment]
If someone is willing to make a PR with what I need to support TypeScript(? - I'm guessing here), then I'll include it. I don't use it myself. Looks like whatever is in DefinitelyTyped, which is nothing to do with me, has not been updated for version 2.x. You can always change your dependency to log4js@1.x  - that was the whole point of bumping the major version number to 2, because it includes breaking changes.

**Comment by nomiddlename** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18492

**Comment by nomiddlename** [comment]
I've pushed version 2.3.5 to NPM, which includes the type definition from this PR: https://github.com/nomiddlename/log4js-node/pull/553

Please take a look, and see if it solves your problem.

**Comment by xialeistudio** [comment]
DefinitelyTyped's log4js typescript definition only support for log4js@1.x
I also make a PR to DefinitelyTyped to support log4js@2.x[https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20383](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20383)

**Comment by nomiddlename** [comment]
Thanks for your help @xialeistudio

**Comment by xialeistudio** [comment]
@nomiddlename  Thanks,I used log4js for many nodejs projects,It's powerful!

**Comment by taoqf** [comment]
@xialeistudio it seems that there's no need to make pr to definitelytyped, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20518

**Comment by nomiddlename** [comment]
Please give v2.3.6 a try, the typescript definition has been updated.

**Comment by xialeistudio** [comment]
log4js1.x removed from DefinitelyTyped,but I make a log4js2.x pr.so it's conflict

**Comment by nomiddlename** [comment]
Closing this one, since the typescript definitions seem to be working ok.
