### ISSUE TITLE
log4js.shutdown() interrupts logstashUDP appender

### ISSUE THREAD

**Issue by tizzyapunkt** [log4js-node/log4js-node#520]
It seems, that calling log4js.shutdown() a few millis after logging with the logstashUDP appender causes the udp socket to close before the message has been sent.

Something like this (pasted from examples), without modifying the logstashUDP.js won't work:

```
const log4js = require('log4js');

log4js.configure({
  appenders: {
    console: {
      type: 'console'
    },
    logstash: {
      host: 'localhost',
      port: '7070',
      type: 'logstashUDP',
      logType: 'myAppType', // Optional, defaults to 'category'
      fields: {             // Optional, will be added to the 'fields' object in logstash
        field1: 'value1',
        field2: 'value2'
      },
      layout: {
        type: 'pattern',
        pattern: '%m'
      }
    }
  },
  categories: {
    default: { appenders: ['console', 'logstash'], level: 'info' }
  }
});

const logger = log4js.getLogger('myLogger');
logger.info('Test log message %s', 'arg1', 'arg2');
log4js.shutdown((err)=>console.log('shutdown: ', err))
```

I tried something hacky like this in the logstashUDP.js:
```
  log.shutdown = function (cb) {
    udp.send('test',null,null,9999,'0.0.0.0', (err) => {console.log('error: ', err); udp.close(cb);})
  };
```

This will send some dummy UDP before closing the socket to make sure that all former messages have been sent. 

As this is not a good solution, are there any suggestions on that? Unfortunately the dgram module does not provide an event for 'message has been sent' or something like that.

**Comment by nomiddlename** [comment]
Have you tried something like this?
```javascript
process.nextTick(() => {
  log4js.shutdown((err) => console.log('shutdown:', err));
});
```

**Comment by tizzyapunkt** [comment]
@nomiddlename 
I tried that right now and it doe's not work either. Might be because of process.nextTick callbacks will get fired before other I/O callbacks? 

I tried a simple timeout of 10 millis, that works but is quiet a dirty solution too.
```
setTimeout(log4js.shutdown, 10, (err) => console.log('shutdown:', err) )
```

What about closing the UDP socket in the logstashUDP module itself, eg as a callback for successful/non-successful message sending?

**Comment by nomiddlename** [comment]
I think the only way to do this is for the appender to register a callback for the `udp.send` function, and keep track of all the messages that haven't been acknowledged as sent - then to check that list in the appender's shutdown function.

**Comment by nomiddlename** [comment]
I'll work on a fix for this, but as it's an edge case and there's a workaround, it won't get done until after the changes I'm making for the multiprocess appender #518

**Comment by nomiddlename** [comment]
Bumping this to 2.6.0, so I can get 2.5.0 out of the door.

**Comment by nomiddlename** [comment]
Sorry, the fix for this got bumped due to some security issues that I had to look at.

**Comment by nomiddlename** [comment]
Closing this one, because it's covered by the issue in the logstashUDP project.
