### ISSUE TITLE
default appender 

### ISSUE THREAD

**Issue by juzhen21510** [log4js-node/log4js-node#537]
I am using the log4js 1.1.1.
if a log , and it's category matches no appender,  i want it show in the default appender, such as the console. but if a log matches a category, no need to show in the console. how can I config the configuration.

**Comment by nomiddlename** [comment]
I honestly can't remember how to do this in log4js 1.1.1 - I think you'd need to use the category filter maybe?

In log4js@2.x, it would be:
```javascript
log4js.configure({
  appenders: {
    console: { type: 'console' },
    logfile: { type: 'file', filename: 'somewhere.log' }
  },
  categories: {
    default: { appenders: [ 'console' ], level: 'debug' },
    someCategory: {appenders: [ 'logfile'], level: 'info' }
  }
});
```

**Comment by nomiddlename** [comment]
Closing this one - going to assume you managed to solve your problem.
