### ISSUE TITLE
log4js object in libraries

### ISSUE THREAD

**Issue by sharp-c** [log4js-node/log4js-node#539]
version: 1.1.1
project structure:
```javascript
projectA
       |
       index.js
       node_modules
                |
                log4js
                projectB
                         |
                         node_modules
                                      |
                                      log4js
```
problem:
I have a projectA which requires log4js and projectB as its dependency.
projectB use log4js as its dependency.

In projectB, I config log4js by calling:
```javascript
log4js.configure({
        appenders: [
            {
                type: 'file',
                filename: 'projectB.log',
                category: 'projectB'
            }
       ]
})
```
If I config log4js in projectA by calling:
```javascript
log4js.configure({
       appenders: [
              { type: "console",category:'lg' }
       ]
}),
```
then, projectB stop logging.
it seems log4js instance from projectB and log4js instance from projectA are exactly the same instance, so, after calling log4js.configure the second time, the previous configured appenders are replaced by the new one. 

I want my library has its own appenders and not effected by other codes, is there a way to add new appenders? please help!

**Comment by nomiddlename** [comment]
You probably want to make project B use [log4js-api](https://www.npmjs.com/package/@log4js-node/log4js-api) instead of log4js. That way project A can choose how the logging of project B should work. Or you can leave project B as it is, and duplicate the logging config in project A. 

I wrote log4js-api because I think dependencies/libraries should not decide how the main application logs things, but this might not fit what you're trying to do.

**Comment by nomiddlename** [comment]
@sharp-c did log4js-api solve your problem? If so, can I close this issue?

**Comment by sharp-c** [comment]
@nomiddlename sorry, log4js-api not work for me, what I want is add api to add new appenders, something like:
```js
log4js.configure({
       appenders: [
              { type: "console",category:'lg' }
       ]
})

log4js.add({
       appender: {type:"file", category:"abc"}
})
```
so that I can have chance to configure log4js the second time, but not replace the previous configured appenders.

**Comment by ericnewton76** [comment]
Along the lines of what @nomiddleman said, it’s actually not a good practice to configure the logger from your sub project. 

In your sub project, just call getLogger() and let the calling project decide how logging should be configured

**Comment by nomiddlename** [comment]
Closing this issue, because I don't think it's something I'm going to change.
