### ISSUE TITLE
Error assigning alwaysIncludePattern in dateFile Appender

### ISSUE THREAD

**Issue by frauss** [log4js-node/log4js-node#559]
I'm getting an exception when I try to configure log4js from a config object created using the config module (https://www.npmjs.com/package/config). When I use the following:

```
let logConfig = config.get("logging");
log4js.configure(logConfig);
```

I get the following exception:
```
.../node_modules/log4js/lib/appenders/dateFile.js:50
    config.alwaysIncludePattern = false;
                                ^

TypeError: Cannot assign to read only property 'alwaysIncludePattern' of object '#<Object>'

```

I can get around this by cloning the config object:

```
let logConfig = _.cloneDeep(config.get("logging"));
log4js.configure(logConfig);
```

Here's the config section I'm setting up:

```
  "logging": {
    "escapeValues": false,
    "appenders": {
      "stdout": {
        "type": "stdout",
        "layout": {
          "type": "pattern",
          "pattern": "%d{ISO8601_WITH_TZ_OFFSET}|%p|KeystoneAgentLogs|%m"
        }
      },
      "dateFile": {
        "type": "dateFile",
        "filename": "logs/KeystoneAgentLogProcessor.log",
        "pattern": "-yyyy-MM-dd",
        "compress": true,
        "daysToKeep": 7,
        "alwaysIncludePattern": false,
        "layout": {
          "type": "pattern",
          "pattern": "%d{ISO8601_WITH_TZ_OFFSET}|%p|KeystoneAgentLogs|%m"
        }
      }
    },
    "categories": {
      "default": {
        "appenders": ["stdout", "dateFile"],
        "level": "ALL"
      }
    }
  },
```

Thanks,
Fred

**Comment by victor0801x** [comment]
which version of log4js do u use? It seemed has fixed ≧ 2.3.3. u can see the closed issue #519

**Comment by frauss** [comment]
I'm using 2.3.4.

Looks like you had the same issue, is it working for you since 2.3.3? 

It looks like the fix applied is in the streamroller module but the problem code is actually in log4js.

**Comment by victor0801x** [comment]
I'm not sure. after that, I separate log4js configure in config/logger.js using module.exports. It's more convenient than json

**Comment by victor0801x** [comment]
since config.js use Object.defineProperty() and set writable : false, configurable: false
you can comment dateFile.js at line 49~51, until @nomiddlename fix

**Comment by nomiddlename** [comment]
You could also try this workaround: https://github.com/lorenwest/node-config/wiki/Environment-Variables#allow_config_mutations

**Comment by frauss** [comment]
Thanks for the pointer. I've got a couple of workarounds at this point.
