### ISSUE TITLE
File not creating

### ISSUE THREAD

**Issue by hangonsushant** [log4js-node/log4js-node#561]
This is my code for log4js configuration :- 

`const fs = require('fs');
const log4js = require('log4js');
const nodemailer = require('nodemailer');

log4js.configure({
			appenders: {
				'applog' : {
					type: 'file',
					filename: 'app-api-error-log.log',
					pattern: "-yyyy-MM-dd",
					alwaysIncludePattern: false,
					maxLogSize: 10485760,
					backups: 3,
					compress: true 
				}
			},
			appenders: {
			    'applog': {
			     	type: 'smtp',
			    	recipients: 'sushant@example.com',
			    	subject: 'Latest api error logs',
			    	sender: 'ptech@example.com',
			    	attachments: {
			        	enable: true,
			        	filename: 'app-api-error-log.log',
			        	message: 'See the attachment for the latest error logs'
			    	},
			    	sendInterval: 60,
		            transport: nodemailer.createTransport({
					   service: 'Gmail',
					   auth: {
					      user: 'dev@example.com',
					      pass: '123456'
					   }
					})
			    }
			},
			categories : {
				default: { 
					appenders: [ 'applog' ], level: 'ERROR'
				}
			}
		});

var logger = log4js.getLogger('applog');
module.exports = logger;`

But neither logfile created nor I'm getting an email regarding the error. Is there any error?

**Comment by nomiddlename** [comment]
Your configuration is wrong. I'm assuming you want two appenders, and for errors to go to both the file appender and the email one. Your config should look like this:
```javascript
log4js.configure({
  appenders: {
    applog: { type: 'file', filename: 'app-api-error.log', ... },
    email: { type: 'smtp', ... }
  },
  categories: {
    default: { appenders: [ 'applog','email' ], level: 'ERROR' }
  }
});
```
Note that there should only be one `appenders` property at the top level of the config object.

**Comment by hangonsushant** [comment]
Still log file not creating for the error logs

**Comment by hangonsushant** [comment]
const fs = require('fs');
const log4js = require('log4js');
const nodemailer = require('nodemailer');

log4js.configure({
			appenders: {
				logerror : {
					type: 'file',
					filename: 'app-api-error-log.log',
					pattern: "-yyyy-MM-dd",
					alwaysIncludePattern: false,
					maxLogSize: 10485760,
					backups: 3,
					compress: true 
				},
				mailerror: {
			     	type: 'smtp',
			    	recipients: 'sushant@example.com',
			    	subject: 'Latest api error logs',
			    	sender: 'test@example.com',
			    	attachments: {
			        	enable: true,
			        	filename: 'app-api-error-log.log',
			        	message: 'See the attachment for the latest error logs'
			    	},
			    	sendInterval: 60,
		            transport: nodemailer.createTransport({
					   service: 'Gmail',
					   auth: {
					      user: 'test@example.com',
					      pass: 'test123'
					   }
					})
			    }
			},
			categories : {
				default: { appenders: [ 'logerror','mailerror' ], level: 'ERROR'}
			}
		});

var logger = log4js.getLogger();
module.exports = logger;

in main .js 
var logger = require(./config/logger');
logger.error('this is test');

**Comment by nomiddlename** [comment]
Try running your application with the `DEBUG=log4js:*` environment variable set, that should produce a lot of debug information and maybe we can work out what's happening.

**Comment by nomiddlename** [comment]
I'm going to assume you fixed your problem. Please re-open if you still think there's a problem with log4js.

**Comment by hangonsushant** [comment]
Hi ,
sorry I was away from this project while a time, please can you open this issue again. Because I'm still facing this problem.

**Comment by hangonsushant** [comment]
This is log I get : 
![screen shot 2017-12-22 at 3 48 39 pm](https://user-images.githubusercontent.com/31472291/34294699-bf80e444-e72f-11e7-8c7e-2cacfad47cc6.png)
![screen shot 2017-12-22 at 3 48 46 pm](https://user-images.githubusercontent.com/31472291/34294700-bfbd6ebe-e72f-11e7-935a-725097e79c9b.png)

**Comment by hangonsushant** [comment]
@nomiddlename

**Comment by nomiddlename** [comment]
Are you running this in PM2 or something? Looks like there is some clustering going on there that you haven't mentioned before - from the logs you've got two worker processes but no master process that is listening for log messages from the workers.

**Comment by hangonsushant** [comment]
Yes I'm running my app using PM2

**Comment by nomiddlename** [comment]
If you're using PM2, have you followed the instructions on the [FAQ](https://log4js-node.github.io/log4js-node/faq.html)?
