### ISSUE TITLE
Automated test for typescript definition

### ISSUE THREAD

**Issue by nomiddlename** [log4js-node/log4js-node#570]
We need a way of making sure we don't break the typescript definitions again. I don't use typescript, so I'd be very happy to get some input from people who do. @taoqf @AmShaegar13 @xialeistudio 

Is just running the `types/test.ts` file and not getting any errors enough? I should be able to hook that into the travis build pretty easily.

**Comment by taoqf** [comment]
I think it will be enough if all tests are included in types/test.ts.

**Comment by xialeistudio** [comment]
yes,I commit a copy to [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped),
It passed the test

**Comment by pe8ter** [comment]
I submitted #710 which automatically verifies that the typings are strict on prepush. What this does not do is validate that the typings adhere to the library's actual functionality which cannot trivially be done without actually writing the library itself in TypeScript, so I don't know if the PR addresses the concern of this issue.

**Comment by nomiddlename** [comment]
Closing this one. The typescript test we have now is good enough.
