### ISSUE TITLE
[Bug] Memory usage keeps increasing

### ISSUE THREAD

**Issue by wei-hai** [log4js-node/log4js-node#573]
I am using version `2.3.2`, and I found that the memory usage increases fast as it generates more and more log files. I tried to delete those log files and the memory usage dropped to normal. So I think it would be better to fix this memory issue and add feature that limit the number of date files similar to what logrotate does.
The configuration:
```
log4js.configure({
  appenders: { default: { type: 'dateFile', filename: '/var/log/' + config.get('SUBSCRIPTION_NAME') + '.log' } },
  categories: { default: { appenders: ['default'], level: 'debug' } }
});
```

memory usage drops as date files are deleted:

<img width="1255" alt="screen shot 2017-10-23 at 1 53 12 pm" src="https://user-images.githubusercontent.com/2936715/31912691-94467092-b7f9-11e7-9c3b-93db9cf44732.png">

**Comment by nomiddlename** [comment]
Could you show me how you're calling log4js.configure, please? Are you calling it multiple times in your application, by any chance?

**Comment by wei-hai** [comment]
this is my logging.js:
```
'use strict';
const config = require('../config');
const log4js = require('log4js');
log4js.configure({
  appenders: { default: { type: 'dateFile', filename: '/var/log/' + config.get('SUBSCRIPTION_NAME') + '.log' } },
  categories: { default: { appenders: ['default'], level: 'debug' } }
});
module.exports = log4js.getLogger();
```

And I use it in cluster mode so yes it is called multiple times.

**Comment by nomiddlename** [comment]
When you say it generates more and more log files, does that mean that `config.get('SUBSCRIPTION_NAME')` changes? The configuration you've got there should just create one log file, that gets rotated once a day.

**Comment by wei-hai** [comment]
I mean more and more date files (1 file per day).

**Comment by nomiddlename** [comment]
Oh, ok - this is over a period of days or weeks then? Your docker container's memory increases with every date file created? Do you have a graph of memory usage over a week or two? How many log files did you have?

**Comment by nomiddlename** [comment]
Note that the date file appender supports the `daysToKeep` option to delete old log files - see the [docs](https://nomiddlename.github.io/log4js-node/dateFile.html)

**Comment by wei-hai** [comment]
Here is the graph of memory usage over the previous weeks.

<img width="1164" alt="screen shot 2017-10-23 at 2 41 11 pm" src="https://user-images.githubusercontent.com/2936715/31914633-470433f8-b800-11e7-8f2e-f93d21ddc84b.png">

**Comment by nomiddlename** [comment]
When you delete the files, do you restart your application? Next time you delete the files, can you run `lsof` to find out what is keeping those files in memory, please? Just to confirm it is definitely the application, not some other process. 

There's a few other things we can try as well - switching from dateFile to just file, or even just stdout. That way we can narrow down the problem to just the dateFile appender, file appenders or just logging in general.

**Comment by wei-hai** [comment]
I did restart the application when I deleted the files and I am sure the issue is in the application as there is no other application running on the server.

**Comment by nomiddlename** [comment]
I've done a little bit of testing, and I can see there's a small memory leak - although I can't reproduce what you see when deleting the files (when I do that the memory stays the same). I'll do some more investigation, to work out if it is just dateFile appender that does this.

**Comment by polkhovsky** [comment]
I'm having a similar issue. I'm running a data-intensive process with a lot of logging. The process itself finished, but the application is sitting, waiting for the log4js.shutdown to finish writing the log. The process ran for three hours, memory usage went up to 2.8Gb, and I've been sitting waiting for 30 minutes now watching the log file grow slowly. And I mean slowly, like 1-2Mb per minute or so.

**Comment by nomiddlename** [comment]
Hi @polkhovsky - did your data-intensive application do a lot of processing on the main thread without doing any I/O? Because output will be buffered by any node.js process if the main event loop never gets a chance to process. But saying that, output to the file should probably not take that long. How have you configured log4js? Are you using a file appender or stdout and redirecting to a file?

**Comment by polkhovsky** [comment]
There is a lot of processing (mongo queries) and I/O (streaming to the output file). The log file starts and continues to be populated as soon as the script runs. But it lags behind badly. 

Here are my configurations. I write two files - one general and one per extract. The token [SCRIPT_NAME] gets replaced before logger is initialized:
```
"log4js": {
    "appenders": {
      "out": {
        "type": "stdout"
      },
      "console": {
        "type": "console"
      },
      "app": {
        "type": "dateFile",
        "filename": "D:\\development\\DataExtract\\log.txt",
        "pattern": "yyyy-MM-dd",
        "keepFileExt": true
      },
      "extract": {
        "type": "dateFile",
        "filename": "D:\\development\\DataExtract\\[SCRIPT_NAME].txt",
        "pattern": "yyyy-MM-dd",
        "keepFileExt": true
      }
    },
    "categories": {
      "default": {
        "appenders": [
          "out", "console",
          "extract"
        ],
        "level": "info"
      }
    }
  }
```

**Comment by nomiddlename** [comment]
The console appender can cause high memory usage under load - could you try it without the console appender, please? Perhaps that is having a knock-on effect and slowing everything else down too. 

If that makes no difference the next thing to try would be to remove the file appenders and just redirect stdout to a file - that will help us work out if it is the file appenders being slow or if it is log4js in general.
