### ISSUE TITLE
Consider separate projects for optional dependencies (they now take > 22MB)

### ISSUE THREAD

**Issue by hansonw** [log4js-node/log4js-node#576]
As of v2.3.9, a clean `npm install` of log4js is now 25MB! However, once the `optionalDependencies` are ignored, the size goes down to a much more reasonable 2.4MB.

I see that this was originally posted in https://github.com/log4js-node/log4js-node/issues/429, but I'd like to re-open the issue (in light of the 10x size difference!)

I'm not sure which of the optional dependencies are the biggest offender, but they all seem like good candidates for separate appender packages (since it's so easy to plug them in 😄 )

I'd like to upgrade to using the v2 API / appenders in [facebook/atom-ide-ui](/facebook-atom/atom-ide-ui) and [facebook/nuclide](/facebook/nuclide) but doubling the dependency size is a blocker :(

**Comment by nomiddlename** [comment]
Looks like `optionalDependencies` doesn't work the way I thought it would. I thought it would throw an error if you had the wrong version of a dependency installed, but not complain if the dependency was not there at all. Originally I had `peerDependencies`, but that threw out weird errors as well and then got deprecated in npm 3. I think what I need is `optionalPeerDependencies`, as described in [this issue](https://github.com/npm/npm/issues/3066), but that doesn't exist.

Sounds like splitting out the appenders is the only way to fix this problem (25 Mb is crazy).

**Comment by hansonw** [comment]
Thanks @nomiddlename! I see you've re-opened the other issue so I'll close this one.
