### ISSUE TITLE
Document inconsistency about appender loading mechanism

### ISSUE THREAD

**Issue by momocow** [log4js-node/log4js-node#579]
Maybe some of documents require update.

[Appender loading mechanism](https://log4js-node.github.io/log4js-node/writing-appenders.html#loading-mechanism)
vs
[Other Appenders](https://log4js-node.github.io/log4js-node/appenders.html#other-appenders)

**Comment by nomiddlename** [comment]
The "Other Appenders" doc is the most accurate, thanks for picking that up.
