### ISSUE TITLE
Node FILE.js Error

### ISSUE THREAD

**Issue by SomeoneRandom1** [log4js-node/log4js-node#581]
Hello! I have been working on a project in the past few days and to be honest I am having a little bit of trouble.....
I am getting this error when running node site.js
 throw new Error(
        ^

Error: Problem with log4js configuration: ({ appenders:
   [ { type: 'console' },
     { type: 'file', filename: 'logs/site.log' } ] }) - must have a property "appenders" of type object.
    at tests.forEach (/home/bot/node_modules/log4js/lib/configuration.js:44:15)
    at Array.forEach (<anonymous>)
    at Configuration.throwExceptionIf (/home/bot/node_modules/log4js/lib/configuration.js:42:11)
    at new Configuration (/home/bot/node_modules/log4js/lib/configuration.js:205:10)
    at Object.configure (/home/bot/node_modules/log4js/lib/log4js.js:201:12)
    at Object.<anonymous> (/home/bot/site.js:10:8)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
root@CSGO1:/home/bot# ^C
root@CSGO1:/home/bot#     throw new Error(
-bash: syntax error near unexpected token `('

**Comment by nomiddlename** [comment]
You're using log4js v1.x configuration with log4js v2.x - see this [handy document](https://log4js-node.github.io/log4js-node/migration-guide.html)

**Comment by SomeoneRandom1** [comment]
So do I  just need to change the first part it talks about? The v1 to v2?

**Comment by nomiddlename** [comment]
You need to change your `log4js.configure` to something like this:
```javascript
log4js.configure({
  appenders: {
    out: { type: 'stdout' },
    file: { type: 'file', filename: 'logs/site.log' }
  },
  categories: {
    default: { appenders: ['out','file'], level: 'debug' }
  }
});
```

**Comment by SomeoneRandom1** [comment]
out: { type: 'console' },
                            ^

SyntaxError: Unexpected token ,
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
I got this after changing  [https://gyazo.com/2028374d5e1404aae25b7d28fcdf68e9](url)

**Comment by SomeoneRandom1** [comment]
Gyazo is a screenshot program by the way.

**Comment by nomiddlename** [comment]
In the screenshot, it looks like you've got an extra `}` on the last line.

**Comment by SomeoneRandom1** [comment]
Still getting the same problem.

**Comment by nomiddlename** [comment]
You're going to have to give me more to go on. Could you post a snippet of code that calls log4js please?

**Comment by nomiddlename** [comment]
Not a screenshot. Just paste the code into a comment.

**Comment by SomeoneRandom1** [comment]
log4js.configure({
  appenders: {
    out: { type: 'console' },
    task: {
      type: 'dateFile',
      filename: 'logs/site.log',
      pattern: '-dd.log',
      alwaysIncludePattern: true
    }
  },
  categories: {
    default: { appenders: [ 'out' ], level: 'info' },
    task: { appenders: [ 'task' ], level: 'info' }
  }
}

**Comment by nomiddlename** [comment]
you're missing ')' on the last line, I think.

**Comment by SomeoneRandom1** [comment]
When I add that it says logger is not defined

**Comment by nomiddlename** [comment]
You're probably missing a call to `log4js.getLogger("whatever category")` - it's hard to say without seeing your code. Anyway, this doesn't seem like a problem with log4js, and this isn't the right place to get general javascript help. I'm going to close this issue. Feel free to re-open if you're sure there is a problem with log4js itself.
