### ISSUE TITLE
cwd parameter ignored

### ISSUE THREAD

**Issue by EquinoxResearch** [log4js-node/log4js-node#584]
I probably missing something, but the cwd parameter to defined the root folder seems to be ignored.

This is my configuration file  :
```
{
  "appenders": {
    "console": {
      "type": "console"
    },
    "file": {
      "type": "file",
      "filename": "app.log",
      "maxLogSize": 20480,
      "backups": 3
    },
    "logLevel": {
      "type": "logLevelFilter",
      "level": "INFO",
      "appender": {
        "category": "service",
        "type": "file",
        "filename": "service.log",
        "maxLogSize": 20480,
        "backups": 3
      }
    }
  },
  "categories" : {
    "default": { "appenders": ["console", "file"], "level": "debug" }
  }
}
```
And the log4js usage : 

```
let log4js = require('log4js');
const appDir = process.env.APP_DIR_PATH;
let logDir = appDir +'/logs/';
log4js.configure(__dirname +"/config/log4js.json", {cwd: logDir});

var logger = log4js.getLogger();

logger.debug('set the root log to ', logDir);
```

But the logDir is totaly ignored. 

I'm using the 2.3.4 version on windows 10

This is the debug trace : 
og4js:main Configuration is { appenders: { stdout: { type: 'stdout' } },
  log4js:main   categories: { default: { appenders: [Object], level: 'OFF' } } } +0ms
  log4js:configuration Creating appender stdout +8ms
  log4js:configuration Loading module from  ./appenders/stdout +3ms
  log4js:configuration cluster.isMaster ? true +2ms
  log4js:configuration pm2 enabled ? undefined +0ms
  log4js:configuration pm2InstanceVar = NODE_APP_INSTANCE +0ms
  log4js:configuration process.env[NODE_APP_INSTANCE] = undefined +0ms
  log4js:configuration Creating category default +1ms
  log4js:main listening for cluster messages +0ms
  **log4js:main Loading configuration from D:\src\domus\agewell\context-manager-server/config/log4js.json +1ms**
  log4js:main Configuration is { appenders: 
  log4js:main    { console: { type: 'console' },
  log4js:main      file: 
  log4js:main       { type: 'file',
  log4js:main         filename: 'app.log',
  log4js:main         maxLogSize: 20480,
  log4js:main         backups: 3 },
  log4js:main      logLevel: { type: 'logLevelFilter', level: 'INFO', appender: [Object] } },
  log4js:main   categories: { default: { appenders: [Object], level: 'debug' } } } +0ms
  log4js:configuration Creating appender console +5ms
  log4js:configuration Loading module from  ./appenders/console +0ms
  log4js:configuration cluster.isMaster ? true +4ms
  log4js:configuration pm2 enabled ? undefined +0ms
  log4js:configuration pm2InstanceVar = NODE_APP_INSTANCE +0ms
  log4js:configuration process.env[NODE_APP_INSTANCE] = undefined +0ms
  log4js:configuration Creating appender file +1ms
  log4js:configuration Loading module from  ./appenders/file +0ms
  log4js:configuration cluster.isMaster ? true +50ms
  log4js:configuration pm2 enabled ? undefined +0ms
  log4js:configuration pm2InstanceVar = NODE_APP_INSTANCE +0ms
  log4js:configuration process.env[NODE_APP_INSTANCE] = undefined +0ms
  log4js:file Creating file appender ( app.log ,  20480 ,  3 ,  { type: 'file',
  filename: 'app.log',
  maxLogSize: 20480,
  backups: 3 } ,  undefined ) +0ms
  log4js:configuration Creating appender logLevel +4ms
  log4js:configuration Loading module from  ./appenders/logLevelFilter +1ms
  log4js:configuration cluster.isMaster ? true +0ms
  log4js:configuration pm2 enabled ? undefined +0ms
  log4js:configuration pm2InstanceVar = NODE_APP_INSTANCE +0ms
  log4js:configuration process.env[NODE_APP_INSTANCE] = undefined +0ms
  log4js:configuration Creating category default +1ms
  log4js:main listening for cluster messages +1ms
  log4js:main creating logger as master +0ms
  log4js:main configForCategory: searching for config for default +1ms
  log4js:main configForCategory: default exists in config, returning it +0ms
  log4js:logger Logger created (default, DEBUG, function sendLogEventToAppender(logEvent) {
  log4js:logger   if (!enabled) return;
  log4js:logger   debug('Received log event ', logEvent);
  log4js:logger   const appenders = appendersForCategory(logEvent.categoryName);
  log4js:logger   appenders.forEach((appender) => {
  log4js:logger     appender(logEvent);
  log4js:logger   });
  log4js:logger }) +0ms
  log4js:main configForCategory: searching for config for default +1ms
  log4js:main configForCategory: default exists in config, returning it +0ms
  log4js:logger sending log data (DEBUG) to appenders +2ms
  log4js:main Received log event  LoggingEvent {
  startTime: 2017-10-31T17:52:16.922Z,
  categoryName: 'default',
  data: 
   [ 'set the root log to ',
     'D:\\src\\domus\\agewell\\context-manager-server/logs/' ],
  level: Level { level: 10000, levelStr: 'DEBUG', colour: 'cyan' },
  context: {},
  pid: 13112 } +0ms
  log4js:main configForCategory: searching for config for default +6ms
  log4js:main configForCategory: default exists in config, returning it +0ms

**Comment by EquinoxResearch** [comment]
From the V2 the cwd seems to be ignored has mentionned in the the v2-changes.md file.

> - no cwd, reload options in config

How can I configure an absolute root path for all my loggers ?

**Comment by victor0801x** [comment]
You can require first, then pass to configure
```js
const conf = require(path/to/ur/config.json)
log4js.configure(conf)
```

**Comment by EquinoxResearch** [comment]
Thanks @victor0801x  for your response. I tried it and change nothing. The problem is not the loading of the log4js configuration file, it is the usage of the cwd parameter. The appender are created but the log files are not created in the folder passed to cwd.

It seems that since the v2 this parameter is no supported anymore. 
How can i change the root path of all file appender wich are configured with a relative path.
I dont' want to have to configure the appenders with an absolute path.

**Comment by nomiddlename** [comment]
Hi @EquinoxResearch - you're totally right, the `cwd` option (and the extra options, like `reload`, in general) were removed in v2.x. They made configuring log4js more complicated and the code difficult to maintain. I took the approach of pushing responsibility for things like that out to either other libraries or the user.

In your case, I would put my configuration into a module and do the prepending of the root path in javascript. For example:
```javascript
// log-config.js
const rootPath = '/var/log/stuff';
module.exports = {
  appenders: {
    file: { type: 'file', filename: path.join(rootPath, 'logfile.log' }
  },
  categories: {
    default: { appenders: ['file'], level:'info' }
  }
};

//main-app.js
const config = require('log-config');
log4js.configure(config);

```

**Comment by EquinoxResearch** [comment]
Hi @nomiddlename - Thank you for your suggestion. It works really well.

**Comment by nomiddlename** [comment]
Glad I could help you out.
