### ISSUE TITLE
Different dateFile appenders have the same output information.

### ISSUE THREAD

**Issue by Emiya0306** [log4js-node/log4js-node#587]
I configurate different dateFile appenders, and get one of them to output information. What I except is just one dateFile output information, but all of them did. Is this a bug? 

Reproduce repo link: [this](https://github.com/Emiya0306/log4js-dateFile-issue).

**Comment by ramicohen303** [comment]
in app.js line 20, you create a logger for the category 'http', but your configuration does not include this category, it only includes the default category. When a category is not found, default is assumed, which is why you get messages in both files.

Please add a category called http, include the http appender, and try again.

Rami

**Comment by Emiya0306** [comment]
```json
{
  "categories": {
    "http": {
      "appenders": ["http"],
      "level": "debug"
    },
    "system": {
      "appenders": ["system"],
      "level": "debug"
    },
    "controller": {
      "appenders": ["controller"],
      "level": "debug"
    },
    "default": {
      "appenders": ["http", "system", "controller"],
      "level": "debug"
    }
  }
}
```

Greate! I need to configurate categories just like this, it works. But one thing confuses me why I need configurate the "categories "to use appender's name and add this appender's name to "appenders" list? If the category name is not matched appender's name, it doesn't work. It's a little wired.

**Comment by ramicohen303** [comment]
There are two options to handle calls to non-existent categories:
1. Throw an error and make it very obvious you did something wrong, by breaking you application in runtime.
2. Gracefully fall back to default, requiring you to dig around and look for a solution.

The creator of this project chose option 2. Both options are valid, and I am sure we could make arguments for and against both. 

I will see if we could add a debug message to float this issue in a non-breaking manner.

**Comment by Emiya0306** [comment]
Yeah~ I see, thanks for your answer very much! 👍
