### ISSUE TITLE
Can I use log in a synchronous way

### ISSUE THREAD

**Issue by juzhen21510** [log4js-node/log4js-node#589]

**Comment by ramicohen303** [comment]
Yes, it depends on the appender. For example, check out the [file](https://log4js-node.github.io/log4js-node/file.html) and [fileSync ](https://log4js-node.github.io/log4js-node/fileSync.html) appenders.

**Comment by nomiddlename** [comment]
Going to assume that the fileSync appender did what you wanted to do, closing this one.
