### ISSUE TITLE
Move logstashUDP appender to its own project

### ISSUE THREAD

**Issue by nomiddlename** [log4js-node/log4js-node#596]
Part of #429 

1. Copy current appender to new project in log4js-node org.
1. Change new appender's name so no conflict with current appender.
1. Publish new appender to NPM.
1. Add deprecation message to current appender, pointing user to new appender, but continue to work.

When log4js v3 released:
1. Replace core appender with warning about removed appender, pointing to new one.
1. Remove rest of core appender.

**Comment by cula** [comment]
hi~  I'd like to try. 
Could u please open one repo for LogstashUDP appender in log4js-node to push the code?
I'll do as the GELF appender did.

**Comment by nomiddlename** [comment]
@cula - awesome, thanks. I've created the repo here: https://github.com/log4js-node/logstashUDP

**Comment by nomiddlename** [comment]
@cula - I've also added you to the log4js devs group, so you can push directly to the repo. With great power, comes great responsibility.

**Comment by cula** [comment]
thx

**Comment by cula** [comment]
I got error when I tried to push.
ERROR: Permission to log4js-node/logstashUDP.git denied to cula.
fatal: Could not read from remote repository.

It seems like I still have no right to push. So I create a [pull request](https://github.com/log4js-node/logstashUDP/pull/1)  here.

**Comment by nomiddlename** [comment]
Deprecated in PR #682

**Comment by cula** [comment]
I thought I finished this and I closed this issue. Please make a check.
Be kind to reopen this if there is anything wrong
