### ISSUE TITLE
fileSync appender does not support flags

### ISSUE THREAD

**Issue by k7sleeper** [log4js-node/log4js-node#603]
The `fileSync` appender does not support `flags`. So, it's not possible to clear the logfile at the beginning (see  #560).

**Comment by ramicohen303** [comment]
Confirming this is an issue. The fileSync adapter ignores the flags parameter. See fileSync.js, line 181. Calls to fs.appendFileSync never pass the options parameter.

I will work on this one.

**Comment by ramicohen303** [comment]
Merged, should be in the 2.3.12 release

**Comment by nomiddlename** [comment]
Published to NPM in version 2.13.12
