### ISSUE TITLE
typescript declaration file is not correct.

### ISSUE THREAD

**Issue by tangxinyao** [log4js-node/log4js-node#606]
**Environment**: node v8.2.1 Windows 10 64 bit
**Version**: log4js ^2.3.11
**description**:  Something happened when I tried to import the levels module in a .ts file. The code below works well when placed in a .js file. But when it comes to a .ts file, as declaration in .d.ts file is not right, tsc will think the levels module here must be a function, but it was really an object instead. I wish if you could fix the bug. 
```
import {levels} from 'log4js';
console.log(levels.WARN);
// [ts] Property 'WARN' does not exist on type 'typeof ".../node_modules/log4js/types/log4js"'.
// However, we all kown that levels did have a property called WARN here.
```

**Comment by ramicohen303** [comment]
Try console.log(levels['WARN']);

**Comment by ramicohen303** [comment]
Did my suggestion work for you? If not, please create a new issue, as I am closing this one.
