### ISSUE TITLE
Best way to show line number of logging line?

### ISSUE THREAD

**Issue by mrjcleaver** [log4js-node/log4js-node#61]
In log4js-node, is there a way to automatically show the file and line number that logs a message?

I found 

http://code.google.com/p/aost/source/browse/trunk/tools/firefox-plugin/trump/chrome/content/logger.js?r=858 - should I do something custom like this?

Sorry, I did look through existing tickets and documentation but my search came up no hits. It just seems like an obvious thing to want.

Best, Martin.

**Comment by dfernandezm** [comment]
Has anyone tackled a Pull Request using the module proposed by @nomiddlename ? I can try with my still basic Javascript.

**Comment by nomiddlename** [comment]
PR #580 should fix this

**Comment by nomiddlename** [comment]
Anybody looking at this issue would probably be interested in https://www.npmjs.com/package/log4js-extend

**Comment by nomiddlename** [comment]
This will be fixed by PR #879

**Comment by nomiddlename** [comment]
Line number support (finally) added in log4js@4.3.0
