### ISSUE TITLE
Logging of stdout from a long process

### ISSUE THREAD

**Issue by yiu31802** [log4js-node/log4js-node#613]
Hello,

I am replacing stdout to log4js in my project. I am having an issue with logging of time consuming processes;
```
// Current implementation
var sh = require('shelljs')
sh.exec("./long-process.sh", (code, stdout, stderr) => console.log(stdout))
// Log is printed as soon as a new print appears in the process.
```

When I try the same with log4js, somehow it does not work as expected
```
// New implementation which does not work properly
var config = {
  appenders: {
    bash: { type: 'file', filename: 'log/bash.log' } // tried with 'fileSync', no luck
  }, categories: {
    bash: { appenders: ['bash''], level: 'debug' }
}
log4js.configure(config)
var logger = log4js.getLogger("bash")
sh.exec("./long-process.sh", (code, stdout, stderr) => logger.info(stdout))
// Log is printed only after the process ends. I expect it prints simultaneously with the progress.
```
Thank you for your support in advance,

Junji

**Comment by nomiddlename** [comment]
According to the docs for `child_process.exec` (which is what shelljs uses under the hood), the callback is only supposed to be called when the process has exited and so you'll get the output as a string or a buffer. I'm not sure that it can work the way you describe in the first example, which would require the callback to be called before the process terminates.

**Comment by nomiddlename** [comment]
Hope my comment helped you out. I'm going to close this issue, but please reopen it if you need more help.

**Comment by yiu31802** [comment]
I am really sorry that I failed to reply promptly!

I remember that after re-test, you are right. Thank you for support!
