### ISSUE TITLE
setGlobalLogLevel in log4js v2

### ISSUE THREAD

**Issue by simondel** [log4js-node/log4js-node#617]
In our project we use `setGlobalLogLevel` to allow users to determine which logging should be shown and which logging should not be shown. I'm trying to upgrade to v2 of log4js but I noticed that `setGlobalLogLevel` is gone.

What is the prefered way to set the log level in log4js v2?

**Comment by nomiddlename** [comment]
Log4js no longer retains a reference to loggers, so there's no way to set the log level for all loggers. You can set the level for all loggers in a category by changing the level on an individual logger though. So if you're not setting individual category levels, then getting the default category logger (`log4js.getLogger()`) and setting its level would do the same thing. However if config exists for a more specific category than default, then that would take precedence.
```javascript
const log4js = require('log4js');
log4js.configure({
  appenders: {
    out: { type: 'stdout' },
    ... //other appenders
  },
  categories: {
    default: { appenders: ['out'], level: 'info' },
    specific: { appenders: ['out'], level:'error'}
  }
});

const defaultLogger = log4js.getLogger(); // initial level 'info'
const specificLogger = log4js.getLogger('specific'); // initial level 'error'
const somethingLogger = log4js.getLogger('something'); // initial level = default = 'info'

console.log(defaultLogger.level); // info
console.log(somethingLogger.level); // info
console.log(specificLogger.level); // error

defaultLogger.level = 'debug';

console.log(defaultLogger.level); // debug
console.log(somethingLogger.level); // debug
console.log(specificLogger.level); // error
```

**Comment by nomiddlename** [comment]
One thing to remember in the above is that those category levels are only shared within a process, so if you're using cluster or pm2 then setting the level for a category will only affect the loggers in that process.

**Comment by nomiddlename** [comment]
I'm going to close this issue. Please reopen it if you need more help.
