### ISSUE TITLE
default config doesn't work in browser

### ISSUE THREAD

**Issue by nbamford** [log4js-node/log4js-node#625]
in lib/log4js.js, this:
`const defaultConfig = {
  appenders: {
    stdout: { type: 'stdout' }
  },
  categories: {
    default: { appenders: ['stdout'], level: 'OFF' }
  }
};
`
Causes the error:
`Problem with log4js configuration: ({ appenders: { stdout: { type: 'stdout' } },
  categories: { default: { appenders: [ 'stdout' ], level: 'OFF' } } }) - appender "stdout" is not valid (type "stdout" could not be found)`

**Comment by nomiddlename** [comment]
Are you using webpack or something? You might want to give the workarounds mentioned here a try: https://github.com/log4js-node/log4js-node/issues/623
https://github.com/log4js-node/log4js-node/issues/466

**Comment by nomiddlename** [comment]
I hope the workarounds mentioned above helped you out. I'm going to close this issue, but please reopen it if you need more help.

**Comment by aniruddhadas9** [comment]
does it work with `angular cli` configuration or I have to do some extra configuration
