### ISSUE TITLE
log4js can't output log in internal debug console of VisualStudioCode

### ISSUE THREAD

**Issue by Mojicode** [log4js-node/log4js-node#628]
I use log4js in VSC，and i find it doesn't output any thing when I debug nodejs code

**Comment by nomiddlename** [comment]
Are you using the console appender?

**Comment by nomiddlename** [comment]
The default config in log4js is to use the stdout appender - looks like VSC has problems getting stdout output, but the newest version has a fix that you have to opt-in to using (scroll to the bottom of this long issue) https://github.com/Microsoft/vscode/issues/19750

Or switch to using the console appender, which you might have more luck with.

**Comment by Mojicode** [comment]
@nomiddlename thank you ! I add ["outputCapture": "std"] in my launch config reference from #19750 and the log4js works!
