### ISSUE TITLE
How to change log path ?

### ISSUE THREAD

**Issue by ivanallen** [log4js-node/log4js-node#632]
Hi,  My project path is "/home/allen/myproject/app.js".    I get the log path "/log/...." when start program in root path such as "node /home/allen/myproject/app.js", but I expect "/home/allen/myproject/log/...". How to do ? 

 I know that the version 1.1.1 can do it passed by parameter { cwd: "/home/allen/myproject/" }，but this feature was removed in version 2.4.1.

So, how to do it in lasted version?

**Comment by nomiddlename** [comment]
If you pass your config as an object to log4js, then you could do something like this:
```javascript
log4js.configure({
  appenders: { 
    file: { type: 'file', filename: path.join(__dirname, 'log/file.log') }
  },
  categories: { default: { appenders: ['file'], level: 'info' } }
});
```

**Comment by nomiddlename** [comment]
Hope this fixed your issue, I'm going to close this one now. Feel free to reopen it if you feel you need more help.
