### ISSUE TITLE
How to switch timestamps off

### ISSUE THREAD

**Issue by thedjfresh** [log4js-node/log4js-node#633]
Wasnt clear from docs how to do this 
im using 
 out: { type: 'stdout', layout: { type: 'messagePassThrough' } },
app: { type: 'file', filename: '/Users/blah/blah/blah.txt' }
to log to a specific path

But cant get the categories values into the string sucessfully and Message pass through when set like this is still giving me timestamps. Id like a completely clean output with no inserted data

**Comment by nomiddlename** [comment]
This works for me:
```javascript
const log4js = require('log4js');

log4js.configure({
  appenders: {
    out: { type: 'stdout', layout: { type: 'messagePassThrough' } }
  },
  categories: {
    default: { appenders: ['out'], level: 'info' }
  }
});

const logger = log4js.getLogger('thing');
logger.info('This should not have a timestamp');
```

**Comment by thedjfresh** [comment]
@nomiddlename thanks ill try it out!

**Comment by thedjfresh** [comment]
@nomiddlename theres no filepath there though?

**Comment by nomiddlename** [comment]
```javascript
log4js.configure({
  appenders: {
    out: { type: 'stdout', layout: { type: 'messagePassThrough' } },
    file: { type: 'file', filename: 'somefile.log', layout: { type: 'messagePassThrough' } }
  },
  categories: {
    default: { appenders: ['out','file'], level: 'info' }
  }
});
```
Something like that should work.

**Comment by thedjfresh** [comment]
Thankyou!
