### ISSUE TITLE
Letter T appearing between date and time

### ISSUE THREAD

**Issue by Stylesoftware** [log4js-node/log4js-node#634]
Hi,
I just upgraded to the latest 2.4.1 version from some version 6 months ago, and with %d im now getting a T instead of a space between the date and the time.

The README.md file shows:
`[2010-01-17 11:43:37.987] [DEBUG] [default] - Some debug messages`

My log shows:
`[2018-01-01T22:46:11.365] Loading event.log size`

Init:
```
function initLogging() {
	log4js.configure({	
		appenders: {
			'everything': { 
				type: 'file', 
				filename: 'html/event.log',
				layout: {
					type: 'pattern',
					pattern: "[%d] %m"
				} 
			},
			'out': { 
				type: 'console',
				layout: {
					type: 'pattern',
					pattern: "%[[%d]%] %m"
				} 
			}
		},
		categories: {
			'default': { appenders: [ 'everything','out' ], level: 'info' }
		}
	});
	logger = log4js.getLogger();
}
```

**Comment by ramicohen303** [comment]
This is actually a fix in a dependency (date-format). The timestamp is now in ISO 8601 format, which includes the T. See [this link](https://en.wikipedia.org/wiki/ISO_8601) for info.

**Comment by ramicohen303** [comment]
We should update the documentation to reflect this change.

**Comment by Stylesoftware** [comment]
Ahh I see.

**Comment by occultskyrong** [comment]
log4js@2.5.2 

Is there a configuration that can be changed ?

I just want the log format to be unified

**watch**

**Comment by nomiddlename** [comment]
Closing this one, feel free to re-open if you think your problem has not been solved.
