### ISSUE TITLE
connectLogger does not write log when socket is closed by peer

### ISSUE THREAD

**Issue by teazean** [log4js-node/log4js-node#637]
As the title shows

## Expected 

Log it when socket is closed by peer.

**Comment by nomiddlename** [comment]
I'm guessing this is because the connect-logger listens for the 'finish' event on the response before logging anything, but when the socket is closed the finish event is not emitted.

**Comment by teazean** [comment]
@nomiddlename yep, I found no listener for close event from connectLogger source file.

**Comment by colmaengus** [comment]
We resolved a similar issue by modifying the connectLogger to use the onFinished module instead of using res.on('finish')
