### ISSUE TITLE
unable to run the custom layout

### ISSUE THREAD

**Issue by vivekgs2007** [log4js-node/log4js-node#639]
I am trying to use the custom layout as per the doc ( https://log4js-node.github.io/log4js-node/layouts.html )

![image](https://user-images.githubusercontent.com/3347921/34665705-3fb773da-f487-11e7-82f0-4132789dbb3a.png)

steps followed:

1. npm install
2. created a custom.js file
3. added the code:
const log4js = require('log4js');

log4js.addLayout('json', function(config) {
  return function(logEvent) { return JSON.stringify(logEvent) + config.separator; }
});

log4js.configure({
  appenders: {
    out: { type: 'stdout', layout: { type: 'json', separator: ',' } }
  },
  categories: {
    default: { appenders: ['out'], level: 'info' }
  }
});

const logger = log4js.getLogger('json-test');
logger.info('this is just a test');
logger.error('of a custom appender');
logger.warn('that outputs json');
log4js.shutdown(() => {});

**Comment by vivekgs2007** [comment]
It worked By installing the exact version 2.4.1

**Comment by vivekgs2007** [comment]
Closing this

**Comment by vivekgs2007** [comment]
I have created a json custom layout but unable to save the file in json format.

```
log4js.addLayout('json', config => function (logEvent) {
  return JSON.stringify(logEvent) + config.separator;
});

log4js.configure({
  appenders: {
    out: { type: 'stdout', layout: { type: 'json', separator: ',' }},
    everything: { type: 'file', filename: 'apitrack.json',maxLogSize: 10485760, backups: 3, compress: true }
  },
  categories: {
    default: { appenders: ['out'], level: 'info' }
  }
});
```

**Comment by victor0801x** [comment]
```js
log4js.configure({
	appenders: {
		out: { type: "stdout", layout: { type: "json", separator: "," } },
		everything: {
			type: "file",
			filename: __dirname + "/apitrack.json",
			layout: { type: "json", separator: "," },
			maxLogSize: 10485760, backups: 3, compress: true
		}
	},
	categories: {
		default: { appenders: ["out", "everything"], level: "info" }
	}
});
```

**Comment by vivekgs2007** [comment]
Thanks @victor0801x . It solved the problem

**Comment by vivekgs2007** [comment]
closing this issue
