### ISSUE TITLE
multiple log4js instance

### ISSUE THREAD

**Issue by vivekgs2007** [log4js-node/log4js-node#643]
Hi,
I need the multiple log4js instances. Presently I am using the file appender for some cases and console output for some other cases. The code is ready. 

Whichever config is used last, It will overwrite the previous one.  So is there any way I can do the multiple config at a time.
```
log4js.addLayout('json', config => function (logEvent) {
        return JSON.stringify(logEvent) + config.separator;
    });

log4js.configure({
    appenders: {
        out: {type: "stdout", layout: {type: "json", separator: ","}},
        everything: {
            type: "multiFile",
            filename: './test.json',
            layout: {type: "json", separator: ","},
            maxLogSize: 10485760, backups: 3, compress: true
        }
    },
    categories: {
        default: {appenders: ["out", "everything"], level: "info"}
    }
});
```
and 

```
No Config for console output ( default one )
```

**Comment by nomiddlename** [comment]
You should only need to configure log4js once. You can direct output to different appenders by using categories for loggers.

**Comment by nomiddlename** [comment]
Closing this issue, assuming you managed to fix your problem using categories.

**Comment by mai1x9** [comment]
> You should only need to configure log4js once. You can direct output to different appenders by using categories for loggers.

@nomiddlename It is pathetic that log4js cannot be configured multiple times. There are some cases where log4js need to be declared multiple times. If its not possible then how can one dynamically add the new files and categories to log4js configure. I tried adding them but in vain. Any help would be grateful.
