### ISSUE TITLE
circular-json out of date

### ISSUE THREAD

**Issue by itsmylife** [log4js-node/log4js-node#644]
Please update circular-json dependency. It has v0.5.1 now. circular-json author fixed some bugs.

please see https://github.com/WebReflection/circular-json/commit/e76f8a8ceb43348ac4f4814c65e5d104a52c508e

**Comment by nomiddlename** [comment]
Thanks for letting us know.

**Comment by nomiddlename** [comment]
Updated dependency published to NPM in version 2.5.0

**Comment by itsmylife** [comment]
@nomiddlename Thanks!
