### ISSUE TITLE
[33m[2018-01-11T12:06:34.812] [WARN] default - [39mplunder

### ISSUE THREAD

**Issue by Veiintc** [log4js-node/log4js-node#646]
logfile:[2018-01-11T12:06:34.812] [WARN] default - plunder
but print in console: [33m[2018-01-11T12:06:34.812] [WARN] default - [39mplunder

**Comment by nomiddlename** [comment]
Looks like your console doesn't like the coloured output (that's what the `[33m` stuff is - trying to set colours. File appender uses basic layout by default, but stdout and console appenders use the coloured layout. Take a look at this page for details: [layouts](https://log4js-node.github.io/log4js-node/layouts.html)

**Comment by Veiintc** [comment]
think you
