### ISSUE TITLE
Types missing in 2.5.0

### ISSUE THREAD

**Issue by coderslagoon** [log4js-node/log4js-node#651]
No more "types" directory to be found in the package which made it to npm. On purpose, no more type goodness? :-)

**Comment by nomiddlename** [comment]
Thanks for picking that up so quickly - it's related to this change #631 

I'll add the types directory and push out a new version.

**Comment by brettneese** [comment]
Ooh, that was my fault, sorry about that. Didn't even think about it.

**Comment by coderslagoon** [comment]
No worries, thanks for quick response!

**Comment by nomiddlename** [comment]
Ok, should be ok now with version v2.5.1

**Comment by coderslagoon** [comment]
Works. Types are happy to be back again. Thank you.
