### ISSUE TITLE
How to transform log entry?

### ISSUE THREAD

**Issue by rightaway** [log4js-node/log4js-node#654]
If you pass some text or object to the log entry, how can you transform that entry? I'm looking to do something log `log.info(object)`, where instead of logging the whole object, I could create a new object by picking and transforming some of the properties of that object. That way I only need to define the transformation in one place, when instantiating log4js.

Otherwise everywhere I call the log function I would have to do

```js
const newObj = { a: object.value1, b: object.value2 }
log.info(newObj)
```

Instead of just calling log.info and having log4js take care of it.

**Comment by nomiddlename** [comment]
You probably want to write a custom layout function. See the [layouts](https://log4js-node.github.io/log4js-node/layouts.html) docs, in the section "Adding your own layouts".

**Comment by nomiddlename** [comment]
Closing this issue, assuming you managed to fix your problem.
