### ISSUE TITLE
Logstash appender object structure

### ISSUE THREAD

**Issue by rightaway** [log4js-node/log4js-node#655]
The `args` value should have a third option which would put `category` and `level` on the top level object, and put all user-defined fields into `fields`. I think it's a better approach because of consistency.

Every message logged from log4js contains `message`, `type`, `category`, `level`, so these should be on the top level object. Everything under `fields` should be things that change per log entry. So some log entries would have `user`, others would have `ip`, etc.

The `fields` option to `args` puts `category` and `level` under the `fields` property which isn't ideal because these are present on every log entry, mixing them up with application-specific fields.

**Comment by rightaway** [comment]
Even better if it would be possible to fully customize the object structure by providing a callback function that would take the inputs and return the object that gets sent to logstash. For example, I'd like to remove `@version` and `@timestamp` and `host`, and add `pid`, in addition to the changes in my message above. Having it fully customizable would be better than providing an `args` option, so I'd suggest allowing `args` to take a function in addition to a string.

**Comment by cula** [comment]
[Logstash JSON object supports more customizing](https://github.com/log4js-node/logstashUDP/issues/3)

**Comment by cula** [comment]
@rightaway 
`@version` should not be removed though it's not needed by u.
[refer to this issue](https://github.com/elastic/logstash/issues/3866)
