### ISSUE TITLE
log4js configuration problem

### ISSUE THREAD

**Issue by D3M3NTOS** [log4js-node/log4js-node#657]
/home/bot/node_modules/log4js/lib/configuration.js:43
        throw new Error(`Problem with log4js configuration: (${util.inspect(this.candidate, { depth: 5 })})` +
        ^

Error: Problem with log4js configuration: ({ appenders:
   [ { type: 'console' },
     { type: 'file', filename: 'logs/site.log' } ] }) - must have a property "appenders" of type object.
    at /home/bot/node_modules/log4js/lib/configuration.js:43:15
    at Array.forEach (native)
    at Configuration.throwExceptionIf (/home/bot/node_modules/log4js/lib/configuration.js:41:11)
    at new Configuration (/home/bot/node_modules/log4js/lib/configuration.js:203:10)
    at Object.configure (/home/bot/node_modules/log4js/lib/log4js.js:205:12)
    at Object.<anonymous> (/home/bot/site.js:36:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by nomiddlename** [comment]
You should probably take a look at the [migration guide](https://log4js-node.github.io/log4js-node/migration-guide.html) - looks like you're using log4js 1.x configuration with 2.x code.

**Comment by D3M3NTOS** [comment]
my code this, i dont know ...
var log4js = require('log4js');
log4js.configure({
	appenders: [
		{ type: 'console' },
		{ type: 'file', filename: 'logs/site.log' }
	]
});
var logger = log4js.getLogger();

**Comment by nomiddlename** [comment]
Maybe take a look at the examples in this repository, there's even an example in the Readme of the correct configuration. The code you've pasted above will only work for versions log4js 1.x or older.

**Comment by D3M3NTOS** [comment]
and how can I install an older version?

**Comment by nomiddlename** [comment]
you specify the version in your package.json file.

**Comment by D3M3NTOS** [comment]
where do I find ? package.json

**Comment by D3M3NTOS** [comment]
i use this comands : 
 cd /home/bot
    -npm install mysql
    -npm install log4js
    -npm install socket.io
    -npm install request
    -npm install fs
    -npm install md5
    -npm install sha256
    -npm install mathjs
    -npm install forever-monitor
    -npm install forever -g
    -npm install steamcommunity
    -npm install steam-totp
    -npm install steam-tradeoffers
    -npm install async
    -npm install engine.io
    -npm install express

**Comment by nomiddlename** [comment]
Ok, looks like you haven't done `npm init` to create a package.json file so never mind about that. Replace the `npm install log4js` with `npm install log4js@1` to install version 1.x

**Comment by nomiddlename** [comment]
This isn't a problem with log4js, so I'm going to close this issue.
