### ISSUE TITLE
attachment not working

### ISSUE THREAD

**Issue by AlanGuo** [log4js-node/log4js-node#658]
you guys messed up attachment and attachments.

![image](https://user-images.githubusercontent.com/727863/35906214-a7b9b376-0c24-11e8-91a4-5bbf8d9b7758.png)
![image](https://user-images.githubusercontent.com/727863/35906221-aed5fe26-0c24-11e8-90f2-9c6d1dd12375.png)

**Comment by nomiddlename** [comment]
Thanks for bringing this up. To be clear, this is a problem with the example code saying `attachments` when it should be `attachment`, right? I've fixed that now. 

If this is actually a problem with logs being sent as an attachment in the email not working, then please re-open this issue.
