### ISSUE TITLE
Log to stderr by default

### ISSUE THREAD

**Issue by hildjj** [log4js-node/log4js-node#66]
It's more typical for console logs to go to stderr than stdout, to avoid interfering with "real" output from (for example) a command-line tool.

**Comment by MichielDeMey** [comment]
This is actually not true. It might have changed in the latest releases, but Node will output all `console.log` messages to `stdout`.
https://nodejs.org/api/console.html#console_console_log_data

**Comment by k8w** [comment]
`console.error` not appear in stderr just now.
Would this be support ?

**Comment by nomiddlename** [comment]
Could you tell me what version of log4js you're using, please? And also how you're configuration log4js. That will help me understand your problem.

**Comment by k8w** [comment]
@nomiddlename 
I'm using log4js 1.1.1

```
log4js.configure({
    appenders: [
        {
            type: 'console'
        },
        {
            type: 'dateFile',
            filename: path.resolve(__dirname, 'logs/log'),
            pattern: '-yyyy-MM-dd',
            alwaysIncludePattern: true,
            daysToKeep: 15
        }
    ],
    replaceConsole: true
});
log4js.getLogger('console').setLevel('DEBUG');
```

**Comment by k8w** [comment]
And make log by `console.log` and `console.error`

**Comment by nomiddlename** [comment]
You want `console.log` messages to go to `stdout` and `console.error` messages to go to `stderr`?
I think this config will do what you want:
```javascript
log4js.configure({
appenders: [
        {
            type: 'logLevelFilter', level: 'TRACE', maxLevel: 'INFO', appender: { type: 'console' }
        },
        { type: 'logLevelFilter', level: 'ERROR', appender: { type: 'stderr' } },
        {
            type: 'dateFile',
            filename: path.resolve(__dirname, 'logs/log'),
            pattern: '-yyyy-MM-dd',
            alwaysIncludePattern: true,
            daysToKeep: 15
        }
    ],
    replaceConsole: true
});
```

**Comment by k8w** [comment]
@nomiddlename It works ~ Thanks ~
