### ISSUE TITLE
logstashUDP error: send EMSGSIZE

### ISSUE THREAD

**Issue by SHocker-Yu** [log4js-node/log4js-node#662]
error : send EMSGSIZE 192.168.11.13: 10001

how to fix it ?

**Comment by nomiddlename** [comment]
This error occurs when the UDP packet size is greater than the MTU (your log message is too large to fit into a single UDP packet). See the [node.js UDP documentation](https://nodejs.org/dist/latest-v8.x/docs/api/dgram.html#dgram_socket_send_msg_offset_length_port_address_callback) for more details. A possible fix would be to implement a custom layout that truncates any log message over a certain length.

**Comment by SHocker-Yu** [comment]
@nomiddlename 
Happy Chinese New Year!
sorry to reply you so late.Thanks for your answer,it's helpful for me.
