### ISSUE TITLE
use webpack pack server of node has a error

### ISSUE THREAD

**Issue by sx-spider** [log4js-node/log4js-node#667]
The Function `lib/loadAppenderModule`

I think should add a  `try...catch...`, because `require.main.filename` may is a `undefined`

so, After webpack packed

In path module, the `path.dirname` will call `assertPath` and if `path` is a `string` will throw error.

**Comment by ericnewton76** [comment]
Btw there’s something about webpack issues in another issue or pull request

**Comment by nomiddlename** [comment]
There's been a few changes in version 3.x to help support webpack. Please re-open this issue if you're still having problems.
