### ISSUE TITLE
How to use with gmail smtp service ?

### ISSUE THREAD

**Issue by krazylearner** [log4js-node/log4js-node#674]
Hi Guys,

`

        log4js.configure({
            appenders: { 
                dateFile : { type: 'file' , filename : path.join(logDirectory,'error.log') },
                email : { type:'smtp',recipients: 'anku*************@gmail.com',
                "transport": "SMTP",
                SMTP :  {
                    host : 'smtp.gmail.com',
                    port : '465',
                    secure: true,
                    "sender": "support@********.com",
                    auth: {
                        user:'support@*********.com' , // username
                        pass: '************'  // password
                    }
                }
            
            } 
            },
            categories: { 
                default: { appenders: ['dateFile'], level: 'debug' },
                app: { appenders: ['dateFile','email'], level: 'info'}
            }
        });

`
This code is not working . can you please give me example on how to use with gmail smtp ?

**Comment by nomiddlename** [comment]
When you say it isn't working, do you get any errors?

**Comment by krazylearner** [comment]
my bad i tried this code in separate file and it worked fine may be something wrong with my codebase .

Thanks for quick response 

bye tc
