### ISSUE TITLE
Docs don't specify that util.format is used to format messages

### ISSUE THREAD

**Issue by alex-sherwin** [log4js-node/log4js-node#675]
Having never used a node logger and trying to use this one, I could not find anywhere in the documentation anywhere or in any examples that explained what formatting placeholders were available (`%s`, `%d`, etc)

I basically gave up on this library simply because of that, giving me a bad impression for what I assumed to be a core feature.  While reading the winston docs they made explicit mention that formatting was done via `util.format`, so I came back here and found in the source that it seems the same is true in log4js as well

The docs should really make mention of this, without prior knowledge there's no point of reference that this would be the case

**Comment by nomiddlename** [comment]
Thanks for picking this up. I've never used the`util.format` placeholders in log messages, so the fact that it works is a happy accident of using `util.format` to print out objects nicely. It was never mentioned in the docs because I've never thought to try it.

**Comment by idenisovs** [comment]
@alex-sherwin Hi. You may find useful also the [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). If I remember correctly, in Node.js they are available since **v4.0.0** and it is a good alternative of `util.format`:
```javascript
var name = 'World';
log.info('Hello %s', name);
```
is equal to
```javascript
var name = 'World';
log.info(`Hello ${name}`);
```

**Comment by alex-sherwin** [comment]
One of the main benefits of placeholder style like via ‘util.format’ is deferred invocation of a given objects ‘toString()’ until it’s actually needed, as well as not doing string concatenation up front.

This is beneficial especially for debug/verbose logging that is not usually turned on.  This way you’re not wasting CPU cycles concatenating strings (either explicitly or via the new template literals) when the target logging level is not turned on.

This is a pretty conmon pattern, for example, with slf4j/logback in Java.

**Comment by idenisovs** [comment]
@alex-sherwin Ok, got it. Thank you for clarification!
