### ISSUE TITLE
Sync logs

### ISSUE THREAD

**Issue by hoscarcito** [log4js-node/log4js-node#681]
Hi! This might be a question than an issue.
I have a node process running on the server catching updates on the database and sending push notifications. If I define an append as a dateFile and the pattern: '-yyyy-MM' to group logs in months, is the log waiting till the next month to flush the file? Is there any other option to handle this?
Also, if my the process ends (CTRL+C) I lost all the logs, what can I do?

Thanks!

**Comment by nomiddlename** [comment]
It should always be writing to the log file, and you should not lose all the logs when your process ends. Maybe if you could share a snippet of code that reproduces the issue, I might be able to give you a bit more help?

**Comment by hoscarcito** [comment]
Yes, you are right. 
I was testing it with this ugly function making some delays and it is not working. But with setInterval works without problem.

The functions
```
function sleep(time, callback) {
    var stop = new Date().getTime();
    while(new Date().getTime() < stop + time) {
        ;
    }
    callback();
}

// Multiple sleeps like this one emulating users input
sleep(3000, function() {
   logger.error('Cheese is too ripe!');
});
```

Thank you for replying so promptly!

**Comment by nomiddlename** [comment]
Ah, yep - if you tie up the main loop the asynchronous I/O stuff never gets a chance to run.

**Comment by hoscarcito** [comment]
Exactly! Thanks for this tool. It's amazing!! 😆
