### ISSUE TITLE
log4js pulls in deprecated packages

### ISSUE THREAD

**Issue by kevinlyles** [log4js-node/log4js-node#686]
Running npm install log4js gives the following warnings:
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated buildmail@4.0.1: This project is unmaintained

**Comment by cula** [comment]
Thank u for the advice. 
Dependencies may be  updated at the release of the milestone 3.0.0.

**Comment by nomiddlename** [comment]
Fixed in log4js@3.0.0
