### ISSUE TITLE
Use yarn install karma 2, some log4js warnings outputted

### ISSUE THREAD

**Issue by wildtang** [log4js-node/log4js-node#692]
yarn install v1.5.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning karma > log4js > nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
warning karma > log4js > loggly > request > node-uuid@1.4.8: Use uuid module instead
warning karma > log4js > nodemailer > mailcomposer@4.0.1: This project is unmaintained
warning karma > log4js > nodemailer > socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
warning karma > log4js > mailgun-js > proxy-agent > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
warning karma > log4js > nodemailer > mailcomposer > buildmail@4.0.1: This project is unmaintained
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...

Will these warning should be resolved?

**Comment by nomiddlename** [comment]
Those are all optional appenders, so if you don't use them (and I don't think karma does), then they won't get loaded. We're working on moving them out to their own projects for version 3.x of log4js, so they should go away when that's ready.

**Comment by wildtang** [comment]
Thanks!

**Comment by nomiddlename** [comment]
Fixed in log4js@3.0.0
