### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ImRyanFeng** [log4js-node/log4js-node#695]
Is it possible to put
```
const log4js = require('log4js');
log4js.configure(...);
```
in a seperate file (example: Logger.js) so then i can just do
```
const Logger = require('./Logger.js');

let Log = Logger.getLogger(...);
Log.info(...);
```
in the file where i want to log things?
also is it possible to add customized logging colors with patterns?

**Comment by nomiddlename** [comment]
Sorry for taking so long to respond, you've probably worked all this out yourself by now. Yes, you can definitely load log4js from a common module. And you can customise the logging colours, and use colours in the pattern layout.
