### ISSUE TITLE
Outdated optional dependencies => High Severity security issues (snyk)

### ISSUE THREAD

**Issue by maugenst** [log4js-node/log4js-node#699]
When checking dependencies on possible security issues using snyk I get High Severity security issues since the referenced mailgun-js is referenced in version ^0.7.0 is quiet outdated. 

Using npm < 6.0.0 will still install the optional dependency even though --no-optional is passed. And using `npm i --no-optional` (6.0.0+) leads to 
```
└─┬ log4js@2.5.3
  └─┬ UNMET OPTIONAL DEPENDENCY mailgun-js@0.7.15
    └── UNMET OPTIONAL DEPENDENCY proxy-agent@2.0.0 
```

So, what about using mailgun-js in the latest version? Any objections?
Thanks & BR, Marius

**Comment by jimmywarting** [comment]
dup of #630 ?

**Comment by nomiddlename** [comment]
The work to move the mailgun appender into its own project has already been done, and will be released in v3 of log4js. That should fix the dependency problems. I'm going to close this issue, as it is a duplicate, but thanks for raising it.

**Comment by wind13** [comment]
But how can we fix the issue before the 3.0.0 release?

Because now npm version still in v2.5.3

**Comment by nomiddlename** [comment]
if you're using a recent version of npm, try using the `--no-optional` parameter to npm install

**Comment by maugenst** [comment]
Didn't work, at least for me. Can anyone confirm?
