### ISSUE TITLE
DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

### ISSUE THREAD

**Issue by pqvst** [log4js-node/log4js-node#707]
When logging an `Error` object, the following prints to the console:
```
(node:93348) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
```

See deprecation notice for node v10:
[[DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated](https://nodejs.org/api/deprecations.html#deprecations_dep0079_custom_inspection_function_on_objects_via_inspect)

**Comment by nomiddlename** [comment]
Thanks for raising this issue. log4js v3.x will support node 10 properly, so I'll add it to the list of things to fix.

**Comment by AbhiMatcha** [comment]
When we can expect this ?
@nomiddlename

**Comment by nomiddlename** [comment]
Hard to say when 3.x will be released. There's only me, along with a couple of others that help out when they can, and I only get to spend about 4 hours a week on this (in a good week). Realistically you're looking at a couple of months before 3.x gets released.

I'd be happy to see a pull request that addresses this in the meantime, if anyone feels like helping out.
