### ISSUE TITLE
[multiprocess appender]: Master crashes when a worker process crashes

### ISSUE THREAD

**Issue by nicojs** [log4js-node/log4js-node#713]
The host process of the log4js appender `'multiprocess'` appender with `role: 'master'` is in risk of crashing. 

If a connected logger (`role: 'worker'`) exits (or crashes) **without** calling `log4js.shutdown()`, it results in an [uncaught exception](https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly) on the host process. If that is not handled, the host process exists:

```
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onread (net.js:659:25)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:174:19)
```

My suggestion is to add a listener: `clientSocket.on('error', handleError);`. The handleError method can be implemented with a `debug()` log message IMO. Don't know what else to do. If you agree, I'm prepared to do the work and create a PR.

Although I agree worker processes should call `shutdown` like good students, the penalty shouldn't be a crashing process. Expecting applications to implement the `process.on('uncaughtException')` is not a valid solution in my opinion, as stated in the documentation:

> The correct use of 'uncaughtException' is to perform synchronous cleanup of allocated resources (e.g. file descriptors, handles, etc) before shutting down the process. It is not safe to resume normal operation after 'uncaughtException'.

Tested on node 10.0.0.

**Comment by nomiddlename** [comment]
Definitely agree that a crashing worker process should not result in the host process crashing as well. If the host catches the error, it can probably just log it as an event for the underlying appender. Happy to see a PR to fix this, so thanks for the offer.

**Comment by nicojs** [comment]
No problem, I know how it is maintaining an open source project. Anything I can do to help 👍 

I did have some problems running the tests. It seems that they don't run on windows. I've added a test and it works for my machine. Hope Travis will be too.
