### ISSUE TITLE
Deprecation modules

### ISSUE THREAD

**Issue by cacothi** [log4js-node/log4js-node#715]
hi guys, 

I'm trying to build my project with no errors but there are some modules that are deprecated in the 2.7.0 version:

npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated buildmail@4.0.1: This project is unmaintained

**Comment by nomiddlename** [comment]
The node mailer deprecation is mentioned in the [FAQ](https://log4js-node.github.io/log4js-node/faq.html). You could try installing with the `--no-optional` NPM option, but I've had mixed reports for that. The deprecated modules are used in optional appenders, so it shouldn't really cause any problems unless you're using those appenders.

**Comment by cacothi** [comment]
Thanks, I actually use the nodemailer on my project, however the log4js is throwing this warning which concerns my team.

Thanks for that

**Comment by nomiddlename** [comment]
Fixed in log4js@3.0.0
