### ISSUE TITLE
Loggly security issues

### ISSUE THREAD

**Issue by amenadiel** [log4js-node/log4js-node#716]
Currently, loggly is listed as an optional dependency. However, npm@6 installs every optional dep regardless of using `--no-optional` or configuring `optional=false` in `.npmrc`.

Loggly hasn't been updated in 2 years and this is the result of running `npm audit`.

Moderate  | Prototype pollution                            
------------|-------------------------------------------------
 Path      | log4js > loggly > request > hawk > boom > hoek 
 More info | https://nodesecurity.io/advisories/566         

Moderate  | Prototype pollution                            
------------|-------------------------------------------------
 Path      | log4js > loggly > request > hawk > cryptiles   
 More info | https://nodesecurity.io/advisories/566         |

Moderate  | Prototype pollution                            
------------|-------------------------------------------------
 Path      | log4js > loggly > request > hawk > hoek        
 More info | https://nodesecurity.io/advisories/566         

Moderate  | Prototype pollution                            
------------|-------------------------------------------------
 Path      | log4js > loggly > request > hawk > sntp > hoek 
 More info | https://nodesecurity.io/advisories/566         

Moderate  | Memory Exposure                                
------------|-------------------------------------------------
 Path      | log4js > loggly > request > tunnel-agent       
 More info | https://nodesecurity.io/advisories/598         

Low       | Regular Expression Denial of Service           
------------|-------------------------------------------------
 Path      | log4js > loggly > timespan                     
 More info | https://nodesecurity.io/advisories/533   

So, I wonder, is it feasible to remove loggly from optional deps?

**Comment by wheresrhys** [comment]
I see you have an issue to switch to a fork of loggly https://github.com/log4js-node/log4js-node/pull/636, but it's earmarked for a v3 of this library, so presumably a breaking change. 

Are you aware of npm's rules on abandoned packages? If a package is unmaintained it is possible to request that npm transfer ownership, which'd give you the ability to bump the dependency versions on `loggly`, and fix the security warning without having it blocked by work on v3

See https://www.npmjs.com/policies/disputes

> This process is an excellent way to ... Adopt an "abandoned" package

**Comment by nomiddlename** [comment]
Loggly is being removed from the optional dependencies, and has been in the version-3.x branch.

**Comment by amenadiel** [comment]
@nomiddlename that's good news. So, if there are no huge breaking changes, when v3 is released I'll submit a PR to karma runner to get rid of npm alerts for the time being.

**Comment by ceastman-ibm** [comment]
@nomiddlename would removing loggly also make it into the 2.x version of log4js?

**Comment by nomiddlename** [comment]
No, because that would be a breaking change for anyone that uses the loggly appender - so it has to be a 3.x release. The appender has already been deprecated, and anyone using it will be prompted to install the external version.

**Comment by nomiddlename** [comment]
@wheresrhys I barely have time to maintain this library, let alone looking after another one. The library used in [log4js-node/loggly](https://github.com/log4js-node/loggly) is more up to date, and doesn't have the security problem. In the meantime, if someone else want to fix the loggly dependency I'll happily cheer them on from the sidelines.

**Comment by amenadiel** [comment]
hmmm you could declare loggly as a peer dependency, since peer deps (unlike optional deps) are not installed automatically and you would just get a warning.

**Comment by nomiddlename** [comment]
@amenadiel yep, the deps were originally peer dependencies, but people complained about getting the warnings, and suggested switching to optional deps. Peer deps, as I understand them, are more for plugins - if the loggly appender was an external project, it would declare log4js as a peer dependency, but log4js would not declare anything about loggly. Optional dependencies are meant for deps that shouldn't break the install if the install of those deps failed, so npm installs the optional ones anyway. There's no way, that I know of, of specifying that a dependency should only be installed if the user asks for it (and when they do, make sure they get a particular version). See this long-lived issue for more of the confusing history of peer dependencies and optional dependencies. https://github.com/npm/npm/issues/3066

It might make more sense to just remove the optional dependencies altogether, and rely on the users of the optional appenders to install the correct dependencies themselves. However, that too would be a breaking change and so would have to wait until version-3.x

**Comment by amenadiel** [comment]
Yeah I've googled a lot and every loose end eventually leads to that npm issue.

**Comment by nomiddlename** [comment]
Yep, it's a mess, but the good news is I've only got a few more appenders to extract before the optional dependencies are all gone (rabbitmq, and the http appenders that use the axis lib - log stash and log faces).

**Comment by amenadiel** [comment]
And then I'll just need to convince the karma people to update log4js to v3

**Comment by koooge** [comment]
npm@6 something wrong
https://github.com/npm/npm/issues/20769

**Comment by nomiddlename** [comment]
Fixed in log4js@3.0.0
