### ISSUE TITLE
about connect-logger.js

### ISSUE THREAD

**Issue by zjyonline** [log4js-node/log4js-node#719]
HI, I am a freshman for log4js.
When I use log4js with express framework, I use 'log4js.connectLogger()' as middleware for express.  
Log content like this 
'[2018-05-29T18:43:25.992] [INFO] http - ::ffff:127.0.0.1 - - "POST /graphql HTTP/1.1" 200 60 "" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"';
However , I also want **request body** in log file ,so I rewrite 'connect-logger.js' this file ,
add 'defaultTokens.push({ token: ':body', replacement: JSON.stringify(req.body).replace(/\\n/g,'','') });' for 'defaultTokens'  this  array.
Look forward to your reply~

**Comment by nomiddlename** [comment]
You don't have to edit the connect logger source to do this. You can pass an array of custom tokens in the options parameter. Something like this:
```javascript
log4js.connectLogger(logger, { format: ':body', tokens: [ { token: ':body', replacement: ... } ]);
```

**Comment by zjyonline** [comment]
I write own tokens like 
`tokens: [ { token: ':body', replacement: JSON.stringify(req.body).replace(/\n/g, '','')  } ]`
but there is an error that `req` is not defined

**Comment by nomiddlename** [comment]
Yep, you're right. Sorry - the custom tokens thing does not work the way I thought it did.

**Comment by zjyonline** [comment]
So，can you fix it in next version ?  haha

**Comment by nomiddlename** [comment]
Related to PR #868

**Comment by nomiddlename** [comment]
If you're still interested in this (it's only been 18 months after all), then PR #875 explains how to do it. See the connect-logger docs as well.
