### ISSUE TITLE
seems setLevel() is not existed in example

### ISSUE THREAD

**Issue by bi-kai** [log4js-node/log4js-node#720]
https://github.com/log4js-node/log4js-node/blob/dcbcbdb4d2aa42667282c441ae74c548cc6bc1dd/examples/fromreadme.js#L10

![image](https://user-images.githubusercontent.com/15070379/40694774-9d686bc8-63f0-11e8-96e6-bae2f575f076.png)
It seems function `setLevel()` is not existed in example.

**Comment by nomiddlename** [comment]
That stack trace image you've posted is not complaining about `setLevel` - it can't find `log4js`. But you are right - `setLevel` does not exist any more, it's just `logger.level = 'ERROR'` now.

**Comment by bi-kai** [comment]
@nomiddlename oh, right, the image is not correct, `setLevel` seems to be a function in `log4js v1`.
many examples on the web are for `v1` which brings many misleads.
