### ISSUE TITLE
layouts - red is difficult to see

### ISSUE THREAD

**Issue by rcwwilliams** [log4js-node/log4js-node#730]
The coloured appender shows errors as red which in layouts.js is currently "red: [31, 39]".

This red is quite dark and difficult to see against a black background.

Would it be possible to change it to "red: [91, 39]" as that is much easier to see?

Thanks.

**Comment by nomiddlename** [comment]
Sounds like a sensible request. Pretty easy to do, if anyone feels like tackling a simple issue. Otherwise I'll try to do it in the next release.

**Comment by rcwwilliams** [comment]
Thanks very much for fixing this - really appreciated.
