### ISSUE TITLE
TypeError: appender is not a function

### ISSUE THREAD

**Issue by nicojs** [log4js-node/log4js-node#746]
The order in which the appenders are defined seems _very_ important. This gives some strange results:

This sample:

```ts
const log4js = require('log4js');
log4js.configure({
  appenders: {
     filteredConsole: { type: 'logLevelFilter', appender: 'console', level: 'info' },
     console: { type: 'stdout' }
  },
  categories: {
    default: { appenders: ['filteredConsole'], level: 'trace' }
  }
});
log4js.getLogger('demo').info('test');
```

Results in error: `TypeError: appender is not a function`. 

A solution would be to sort the appenders topologically. We could use something like [toposort](https://www.npmjs.com/package/toposort)

**Comment by nomiddlename** [comment]
It might be simpler to just improve the error message when an appender refers to another appender that can't be found, so that users can fix this themselves. I can see lots of people making the mistake above, but I don't think people will have config that's a lot more complicated than that. I want to avoid including any more dependencies, if possible.

**Comment by nomiddlename** [comment]
Or do two passes over the appender list, maybe?

**Comment by nicojs** [comment]
The main problem with this is that property order is [not guaranteed by the spec](https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order#answer-5525820) and [sketchy at best](https://hackernoon.com/out-of-order-keys-in-es6-objects-d5cede7dc92e)

I think we should not rely on it. 

>  I want to avoid including any more dependencies, if possible.

I agree with this philosophy, but usually make exceptions for small dependencies that do exactly one thing and do it right, without any other dependencies. The toposort code is just 100 lines and has no other dependencies. I've used it in the past and it works great. 

Alternatively, we could also allow an `order` property for all appenders. My example could look something like this:

```ts
log4js.configure({
  appenders: {
     filteredConsole: { type: 'logLevelFilter', appender: 'console', level: 'info', order: 2 },
     console: { type: 'stdout', order: 1 }
  },
  categories: {
    default: { appenders: ['filteredConsole'], level: 'trace' }
  }
});
```

>  I can see lots of people making the mistake above, but I don't think people will have config that's a lot more complicated than that

My configuration is a little bit more complicated than the example above. It includes stuff like:

```ts
const allAppenders = ['console']
const config = {
  appenders: {
     console: { type: 'stdout' },
     all: { type: require.resolve('./MultiAppender'), appenders: allAppenders }, // this is my own multi appender. It will fan out all log events to the appenders.
    server: { type: 'multiprocess', mode: 'master', appender: 'all' }
  },
  categories: {
    default: { appenders: ['all'], level: 'trace' }
  }
};

if (logToFile) {
  allAppenders .push('file');
  config.appenders.file = { type: 'file', filename: 'logs.log' }; // this is the problem
}

log4js.configure(config);
```

It's even more complicated than that, but you get the picture.

**Comment by mvastola** [comment]
I'm having this same exact issue. `toposort` seems like a pretty straightforward fix. Could this be done? This was annoying to troubleshoot.

**Comment by mvastola** [comment]
Just cobbled together [a fix](https://github.com/log4js-node/log4js-node/pull/986) using the latter approach.
I'm realizing 'lazy-loading' probably isn't the right idea for what I was thinking, but the fix is very straightforward and a fairly clean solution.

**Comment by issgy** [comment]
log.js
`import log4js from 'log4js';

function debug(content) {
  log4js.configure({
    appenders: {
      dateFileOut: {
        type: 'dateFile',
        filename: 'logOut',
        pattern: '-yyyy-MM-dd.log',
        alwaysIncludePattern: true,
        daysToKeep: 30,
        layout: {
          type: 'basic'
        },
      },
      consoleOut: {
        type: 'console', // 输出至控制台
        layout: {
          type: 'colored' // console默认样式，console类不指定则为此样式
        }
      }
    },
    categories: {
      default: { appenders: ['consoleOut'], level: 'trace' },
      access: { appenders: ['dateFileOut'], level: 'debug' },
    }
  })
  const logger = log4js.getLogger()
  const logger1 = log4js.getLogger('access')
  logger.debug(content)
  logger1.debug(content)
  return null
}

export { debug };
`
route.js:
`
import { debug } from '../services/utility/logger'
......code.....

const getComponent = (isAdmin, authed, props) => {
  debug('this is home')
  return <Fragment>
    {isAdmin && <PrivateRoute authed={authed} path='/admin' component={AdminPage} />}
    {permissionData.hasXAndes() && <PrivateRoute authed={authed} path='/project' component={DesignPage} />}
  </Fragment>
}

.......code......
`
I encapsulated log4js in the folder for processing data in the src directory and attempted to use it in the route file.However, the following error was reported. How can I resolve it
**Uncaught_ TypeError: appenderModule.configure is not a function**

**Comment by zyy-llyx** [comment]
我遇到了和楼上相同的问题
