### ISSUE TITLE
Feature request: support for environment variable properties in configuration files.

### ISSUE THREAD

**Issue by mpekar** [log4js-node/log4js-node#751]
log4j had the ${env:ENV_NAME} syntax and it'd be great to see that supported in log4js.

https://logging.apache.org/log4j/2.x/manual/configuration.html#PropertySubstitution

Example usage:
```

{
	"appenders": [
		{
			"type": "file",
			"filename": "${env:ENV_NAME}/log/whatever.log",
			"maxLogSize": 20480,
      			"backups": 10,
      			"category": "somecat"
    		},
    		{
	      		"type": "console" 
	    	}
  	]
}
```

**Comment by nomiddlename** [comment]
That sounds like a useful feature. Have you looked at [node-config](https://github.com/lorenwest/node-config)? Many users of log4js use this package.

**Comment by mpekar** [comment]
Ah that makes a lot of sense.  So instead of having environment parsing specifically for log4js, I'd move the log4js config to my app config and use node-config to parse.

**Comment by nomiddlename** [comment]
@mpekar glad it looks like node-config will work for you. Be careful if you're using the dateFile appender though - there's currently a bug around that.
