### ISSUE TITLE
Migrating to v3

### ISSUE THREAD

**Issue by anseki** [log4js-node/log4js-node#757]
About updating to v3, I guessed that it includes breaking changes because of the version number.
So, is there information about that like migration guide?

**Comment by itaysabato** [comment]
A change log would also be nice :)

**Comment by dsbert** [comment]
Looking at the changelog, I'm guessing this is due to a change in the supported node versions

**Comment by nomiddlename** [comment]
I've added a [list of v3 changes](https://log4js-node.github.io/log4js-node/v3-changes.html) to the docs. Thanks for raising this issue. Please re-open if you think there's something I've missed.

**Comment by anseki** [comment]
Thank you! :smile:

**Comment by itaysabato** [comment]
@nomiddlename Thanks!
This is very helpful.

A couple of questions though:
Is the new TCP appender enabled by default when running a cluster?
Is it required for running a cluster with log4js?

I recall in v1 logging in a cluster worker "just worked" - if it is possible not to centralize logs in the master process I find that preferable.

Thank you for your efforts!

**Comment by nomiddlename** [comment]
The tcp appender isn't enabled by default, and isn't needed within a cluster. Cluster workers will forward their log messages to the master by default, to turn this behaviour off add `disableClustering: true` to your configuration - then it should behave in the same way as v1.
