### ISSUE TITLE
smtp-appender.js

### ISSUE THREAD

**Issue by greenteaone** [log4js-node/log4js-node#760]
根据smtp-appender.js里面的mail设置例子，设置了，运行的时候报错：appender "mail" is not valid (type "@log4js-node/smtp" could not be found)，请问问题出在哪里？

**Comment by victor0801x** [comment]
你有執行 `npm install @log4js-node/smtp` ?
https://github.com/log4js-node/smtp#smtp-appender-for-log4js

**Comment by nomiddlename** [comment]
I'm going to close this one. Please re-open if you feel you need more help.
