### ISSUE TITLE
Where can I find the wiki pages for version 1.x?

### ISSUE THREAD

**Issue by zealotds** [log4js-node/log4js-node#764]
Thanks in advance!

**Comment by nomiddlename** [comment]
Sorry - I disabled the wiki when version 2.x was released because it was confusing some users. I don't think I can get it back (and if I did, then I'd just confuse users even more). Is there a specific problem that you need help with?

**Comment by nomiddlename** [comment]
I'm going to close this issue. Please re-open if you feel you need more help.

**Comment by zealotds** [comment]
I don't check emails very often, sorry for my late response.
I have read the code and found what I need so don't need those pages any more.
Thanks anyway.
