### ISSUE TITLE
3.0.2版本 服务端log4js.configure，直接502get bad way

### ISSUE THREAD

**Issue by zjscy666** [log4js-node/log4js-node#767]
报错截图
![image](https://user-images.githubusercontent.com/22449281/43354979-0d274c8a-9287-11e8-860b-02b1acaf3a8c.png)
代码截图
![image](https://user-images.githubusercontent.com/22449281/43354986-19839bc8-9287-11e8-97cf-677bc9f75501.png)

**Comment by victor0801x** [comment]
@zjscy666 你可以參考這裡 [migration-guide](https://log4js-node.github.io/log4js-node/migration-guide.html)
我使用的經驗:
v1.x -> v2.x : refactor to ES6 & clear configuration(appenders + category)
v2.x -> v3.x : fixed security & reduce log4js core size (separate some appenders)

**Comment by nomiddlename** [comment]
I'm going to close this one. Please re-open if you need more help.
