### ISSUE TITLE
log4js is not working as windows service

### ISSUE THREAD

**Issue by snbaidya** [log4js-node/log4js-node#769]
Hi team,
I am trying to use log4js in my nodejs application and it is working fine as expected when running in windows commandline but when I added the nodejs app as windows service using NSSM tool, it is not creating log file and logging anymore.

Is it a known issue or am I doing something wrong?
Current platform:
Windows server 2007
nodejs -v 8.11.3
log4js-node-v 3.0.3

**Comment by nomiddlename** [comment]
When it runs as a service, does it run as the same user as the command-line? Perhaps there's a permissions problem with creating the log file.

**Comment by nomiddlename** [comment]
I'm going to assume you fixed your problem. Closing this issue.

**Comment by snbaidya** [comment]
Hi NomiddleName,
I am really for the delay as I was busy with another client and but I can confirm, it is working and generating the log files into nodeJS installed folder instead of log folder which is being configured in log4js properties file.

Thanks for the support.
