### ISSUE TITLE
ad-hoc reports with log4js

### ISSUE THREAD

**Issue by petehug** [log4js-node/log4js-node#775]
Our app processes import files as they arrive.  While processing a file, we write a log file with matching path but the .log extension. I can't really see how I could use log4js for this purpose. Am I missing something?

**Comment by nomiddlename** [comment]
Take a look at the [multiFile appender](https://log4js-node.github.io/log4js-node/multiFile.html), it might do what you want.

**Comment by petehug** [comment]
Thanks nomiddlename.  The user example tells me it creates logs/u12345.log, but I can't really workout how it deduces that filename. Also, I don't know much of the details until runtime so I'd have to be able to add appenders when needed and I need the ability to close the file. So my usage pattern is:

```
var mylogger = log4js.open(myLogFilePath/*, plus maybe some open file mode like append instead of truncate */);
...
mylogger.info('blah);
...
mylogger.close();
```

I would have thought any good logging package would support this most simple pattern.

**Comment by nomiddlename** [comment]
I'd use the category example. Create a new logger with the category whose name is your log file, log the output. The file will be closed after no writes have been received for the specified timeout. Take a look at the documentation for the file appender if you want to append to a file, multifile takes the same parameters.

**Comment by nomiddlename** [comment]
I'm going to assume you sorted out your problem. Closing this issue.
