### ISSUE TITLE
Logging without category name

### ISSUE THREAD

**Issue by ImRyanFeng** [log4js-node/log4js-node#778]
How do I remove the category name when I log? I have tried to remove it by doing `log4js.getLogger("");` but it still shows up as "default".

**Comment by nomiddlename** [comment]
The only thing I can suggest is to use a different log layout, so that the category doesn't get output (patternLayout, maybe?).

**Comment by ImRyanFeng** [comment]
I only want to log a certain code/file without the category name. I have tried to use a different config (same except config as the other but without %c) but it still shows up as "default".

Config 1 (used by everything else):
`{
    "appenders": {
        "Console": {
            "type": "stdout",
            "layout": {
                "type": "pattern",
                "pattern": "%d{hh:mm:ss,SSS} %-5p %-25.25c{1} %m"
            }
        }
    },
    "categories": {
        "default": {
            "appenders": ["Console"],
            "level": "INFO"
        }
    }
}`

Config 2 (used for certain file):
`{
    "appenders": {
        "Console": {
            "type": "stdout",
            "layout": {
                "type": "pattern",
                "pattern": "%d{hh:mm:ss,SSS} %-5p %m"
            }
        }
    },
    "categories": {
        "default": {
            "appenders": ["Console"],
            "level": "INFO"
        }
    }
}`

**Comment by nomiddlename** [comment]
Yep, sorry,  I don't think this is possible then if you want other categories to show as well. You could always use a short category name - like `log4js.getLogger("_")`?

**Comment by ImRyanFeng** [comment]
I just tried using `Logger.getLogger(".");` and nothing showed up for the category name when I logged. However, the layout is still the same as Config 1 even though I required Config 2, causing the padding to show. What is casuing this?

**Comment by nomiddlename** [comment]
Are you using both config 1 and 2 in the same process? log4js can only be configured once in a process.

**Comment by nomiddlename** [comment]
You might have more success by defining another console appender in config 1, with the layout that does not output the category. Then just define a special category for the log messages that you don't want to have a category.
```javascript
log4js.configure({ 
  "appenders": { 
    "Console": { "type": "stdout", "layout": { "type": "pattern", "pattern": "%d{hh:mm:ss,SSS} %-5p %-25.25c{1} %m" } },
    "without-category": { "type": "stdout", "layout": { "type": "pattern", "pattern": "%d{hh:mm:ss,SSS} %-5p %m"} }
  }, 
  "categories": { 
    "default": { "appenders": ["Console"], "level": "INFO" },
    "_": { "appenders": ["without-category"], "level": "INFO" }
  } 
});
const logger = log4js.getLogger('_');
logger.info('this has no category');
```

**Comment by ImRyanFeng** [comment]
Yes I was, and what you suggusted works. Thanks!
