### ISSUE TITLE
loadAppenderModule Webpack not working anymore

### ISSUE THREAD

**Issue by farfromrefug** [log4js-node/log4js-node#782]
In old version of log4js (before the recent refactor), we could "override" ```Configuration.prototype. loadAppenderModule``` to load appenders and fix webpack issues.

For example I was doing this
```
//webpack fix
const stdoutAppender = require('log4js/lib/appenders/stdout');
const fileAppender = require('log4js/lib/appenders/file');
const consoleAppender = require('log4js/lib/appenders/console');
const Configuration = require('log4js/lib/configuration');
const oldLoadAppenderModule = Configuration.prototype.loadAppenderModule;
Configuration.prototype.loadAppenderModule = function (type) {
    if (type === 'stdout') {
        return stdoutAppender;
    } else if (type === 'file') {
        return fileAppender;
    } else if (type === 'console') {
        return consoleAppender;
    }
    return oldLoadAppenderModule.call(this, type);
};
``` 
Now it is not working anymore.
How can I achieve the same result with the latest version?

Thanks

**Comment by nomiddlename** [comment]
This was to work around the problem with webpack not recognising dynamic loading of modules. With version 3.x, those appenders are always loaded - effectively doing what you're doing above, but in log4js core. So you shouldn't need this workaround any more. Give it a try, and let me know.

**Comment by nomiddlename** [comment]
I'm going to assume you fixed your problem. Please re-open the issue if this is not the case.

**Comment by farfromrefug** [comment]
@nomiddlename sorry for not closing this. Indeed it is fixed with 3.x

**Comment by mhahn-sighthoundlabs** [comment]
This works if someone does not need any other core appender, for which there is no clean way to get to that list at this moment, since it's all internal in _log4js/lib/appenders/index.js_:

```
const coreAppenders = new Map();
coreAppenders.set('console', require('./console'));
coreAppenders.set('stdout', require('./stdout'));
coreAppenders.set('stderr', require('./stderr'));
coreAppenders.set('file', require('./file'));
coreAppenders.set('dateFile', require('./dateFile'));
```

It can be accomplished with some dirty webpack moves:

```
        test: /log4js\/lib\/appenders\/index\.js$/,
        loader: "string-replace-loader",
        options: {
            search: "coreAppenders.set('dateFile', require('./dateFile'));",
            replace: "coreAppenders.set('dateFile', require('./dateFile')); " +
                     "coreAppenders.set('logLevelFilter', require('./logLevelFilter'));"
        }
```

Far from ideal though, so having a better/official way to do this would be great.

**Comment by bryanSME** [comment]
> test: /log4js\/lib\/appenders\/index\.js$/,
>         loader: "string-replace-loader",
>         options: {
>             search: "coreAppenders.set('dateFile', require('./dateFile'));",
>             replace: "coreAppenders.set('dateFile', require('./dateFile')); " +
>                      "coreAppenders.set('logLevelFilter', require('./logLevelFilter'));"
>         }

There appears to still be issues with this.  Where exactly are you placing `const coreAppenders`?
