### ISSUE TITLE
compress error when multi file appender exists

### ISSUE THREAD

**Issue by iampkuhz** [log4js-node/log4js-node#783]
hi, I found that if I create multi appender with type 'file', each of them have different name, e.g. x.log, x.monitor.log, when both of them reach max size limit, the compress gz file got error, it seems that both of them share same target log path( e.g. x.1.log.gz).
BTW, if I change the filename to x_all.log, x_monotor.log, there would be two gz file as expected.

**Comment by peteriman** [comment]
I'm not so sure what is meant by multiFile-appender with type 'file'.
Would you happen to have the codes for it?

**Comment by peteriman** [comment]
Nevertheless, I tried the following based on my assumption.

```javascript
const log4js = require('log4js');
log4js.configure({
  appenders: {
    out: { type: 'stdout' },
    multi: {
      type: 'multiFile', base: 'logs/', property: 'categoryName', extension: '.log', 
      maxLogSize: 1, backups: 3, compress: true
    }
  },
  categories: {
    default: { appenders: [ 'out', 'multi' ], level: 'debug' }
  }
});

const logger = log4js.getLogger('x');
logger.debug('Logging 111');
logger.debug('Logging 222');
const otherLogger = log4js.getLogger('x.monitor');
logger.info('Logging 333');
logger.info('Logging 444');
```
![image](https://user-images.githubusercontent.com/29530649/151407456-4a067a6c-358b-4d54-bf59-f11cdff3552a.png)


This seems weird, as `Logging 444` should not have been logged into `x.log`

This might be related to:
- https://github.com/log4js-node/log4js-node/issues/818

**Comment by peteriman** [comment]
Wait a minute. It seems that the multi-file appender is broken since `log4js@2.1.0`.

```javascript

const log4js = require('log4js');
log4js.configure({
  appenders: {
    multi: { type: 'multiFile', base: 'logs/', property: 'categoryName', extension: '.log' }
  },
  categories: {
    default: { appenders: [ 'multi' ], level: 'debug' }
  }
});

const logger = log4js.getLogger();
logger.debug('I will be logged in logs/default.log');
const otherLogger = log4js.getLogger('cheese');
logger.info('Cheese is cheddar - this will be logged in logs/cheese.log');
```
_(src: https://log4js-node.github.io/log4js-node/multiFile.html)_

I'm only getting `logs/default.log` and not `logs/cheese.log`.

**Comment by peteriman** [comment]
Nevertheless, I tried the following based on my assumption.
It looks correct.

```javascript
const log4js = require('log4js');
log4js.configure({
  appenders: {
    out: { type: 'stdout' },
    multi: {
      type: 'multiFile', base: 'logs/', property: 'categoryName', extension: '.log', 
      maxLogSize: 1, backups: 3, compress: true
    }
  },
  categories: {
    default: { appenders: [ 'out', 'multi' ], level: 'debug' }
  }
});

const logger = log4js.getLogger('x');
logger.debug('Logging 111');
logger.debug('Logging 222');
const otherLogger = log4js.getLogger('x.monitor');
otherLogger.info('Logging 333');
otherLogger.info('Logging 444');
```
![image](https://user-images.githubusercontent.com/29530649/151412916-708d86b1-398f-42a5-9b17-7ff02f7d26cf.png)
