### ISSUE TITLE
Can log4js listen different API?

### ISSUE THREAD

**Issue by unkownY** [log4js-node/log4js-node#786]
I want to use log4js to listen different API, just like:

      localhost/test1
      localhost/test2

and generate 2 diff file `test1.log`,`test2.log`

**CAN log4js DOWN THIS?**

**Comment by nomiddlename** [comment]
If you're using express, then you can add the connect-logger middleware at the two different app paths and use different logger categories to get the output into two log files. See the [connect-logger documentation](https://log4js-node.github.io/log4js-node/connect-logger.html).
