### ISSUE TITLE
electron log4js EACCES

### ISSUE THREAD

**Issue by netsmallhao** [log4js-node/log4js-node#787]
![image](https://user-images.githubusercontent.com/8485984/45250423-55f52c80-b365-11e8-9544-5fe2208e931e.png)
![image](https://user-images.githubusercontent.com/8485984/45250425-67d6cf80-b365-11e8-8465-c0a999c61fd1.png)

**Comment by nomiddlename** [comment]
The '.' in `./logs/mylog.log` in your log filename gets replaced by `process.cwd` - perhaps this value does not get set when running as an Electron app?

**Comment by nomiddlename** [comment]
Yep, that's the problem: [electron process docs](https://electronjs.org/docs/api/process)

You might want to define the log path in relation to another path in the system? (there's a `process.getResourcesPath` in the docs, but I don't know if that's appropriate).

**Comment by nomiddlename** [comment]
Closing this issue as it doesn't look to be a problem with log4js. Please reopen if you think otherwise.
