### ISSUE TITLE
Replace circular-json with flatted

### ISSUE THREAD

**Issue by LoneRifle** [log4js-node/log4js-node#789]
CircularJSON has been marked deprecated in npm, in favour of a new library from the same author: flatted. 

flatted uses a different serialization schema from CircularJSON, and as a result, moving to flatted may be a breaking change for those who use the recording appender and are trying to replay older files. 

This may be mitigated if a change to flatted allows for straight-up serialization/deserialization of non-circular structures.

This issue hence proposes the replacement of CircularJSON with flatted, corresponding adjustments to tests, and a new major version release.

**Comment by nomiddlename** [comment]
The recording appender doesn't do any serialisation to JSON, it stores the events in an in-memory array. As far as I know, it's only used by the log4js tests. 

The only problem I could see with this is for something like the tcp appender, which could receive straight JSON from a non-log4js system (in theory - I don't think anyone is actually using it like that). Flatted looks to have its own format - do you know if it can parse normal JSON? The tests for the project seem to just stringify and parse its own JSON structures.

**Comment by LoneRifle** [comment]
It currently doesn't - which I feel is a regression, somewhat (it expects an array as input). I allude to this in the 3rd line of my opening comment.

Has nobody out there persisted log4js events to disk for replaying later? I would imagine that would be incredibly useful as a tool. Why is the recording appender only storing the events in-memory?

**Comment by WebReflection** [comment]
FYI, flatted, like CircularJSON, expects a `flatted.stringify` or a `CircularJSON.stringify` as input.

Passing regular JSON can have catastrophic results in both libraries.

The fact people ignored that you should never `parse` with CircularJSON what wasn't produced via CircularJSON is one of the reason I'm strongly suggesting to change library and use a recursive capable library only with its own input/output (or port it to other PL).

**Comment by LoneRifle** [comment]
@WebReflection - thanks for bringing this up. In that case, we're just dealing with a simple API-breaking change from CircularJSON to flatted. Given it seems that nobody is storing log4js-node events serialized via CircularJSON to disk, I will try to put in a PR for the migration
