### ISSUE TITLE
Is there any chance to print log file and line numbers? like a.js:1222

### ISSUE THREAD

**Issue by seelikes** [log4js-node/log4js-node#791]

**Comment by nomiddlename** [comment]
It's been proposed a few times (#73), but I'm yet to see a PR that implements it in a way that is easy to switch off (it's a big performance drain to add the line numbers). I'd be happy for someone to work on this though.

**Comment by nomiddlename** [comment]
While we're waiting for someone to implement this, try [log4js-extend](https://github.com/ww24/log4js-node-extend).

**Comment by nomiddlename** [comment]
This will be fixed by PR #879

**Comment by nomiddlename** [comment]
Line number support (finally) added in log4js@4.3.0
