### ISSUE TITLE
Log4JS v0.6.38 logfile saves as ASCII

### ISSUE THREAD

**Issue by MarkMatute** [log4js-node/log4js-node#800]
HI, 

Im using an old version of Log4JS for our legacy project,
log file was saving ASCII instead of utf-8

My Log Config
```
{"appenders": [
    {
      "category": "DataService",
      "type": "dateFile",
      "filename": "log/",
      "maxLogSize": 2048000,
      "backups": 400,
      "pattern": "yyyy-MM-dd.log",
      "alwaysIncludePattern":true,
      "encoding": "utf-8"
    }
  ]
}
```

Thanks

**Comment by nomiddlename** [comment]
The value for encoding should be “utf8” (without the hyphen).

**Comment by MarkMatute** [comment]
@nomiddlename 
First it writes an empty log file which is **empty** filetype, 
Second if the log writes in all English its **ASCII**,
Third if the log writes with Chinese it becomes **UTF-8**

Is this a default behaviour?

**Comment by nomiddlename** [comment]
How are you working out the file type? ASCII is a subset of UTF8.
