### ISSUE TITLE
Bad behaviour of RollingFile appender

### ISSUE THREAD

**Issue by jesskomput** [log4js-node/log4js-node#802]
In log4js version 3.0.6, rolling renames not-log files.
For example, define an appender logging into "app.log" with a small maxLogSize and quite soon the file "app.js" will disappear (be renamed in fact).
This is due to  the 0.7.0 streamroller version, upgrading to 0.8.5 solves the issue.

**Comment by nomiddlename** [comment]
Thanks for raising this. Unfortunately, upgrading the streamroller version breaks a few other things (rolling logs hourly, for instance) so I can't publish a fix quickly. I'm working on it though.

**Comment by nomiddlename** [comment]
This should be fixed in log4js@4.0.0 in npm.
