### ISSUE TITLE
schedule for 4.x?

### ISSUE THREAD

**Issue by csantanapr** [log4js-node/log4js-node#805]
I'm interested on picking up version 4.x since it fixes the problem with circurlar-json 
https://github.com/log4js-node/log4js-node/pull/804

Was wondering if you have ball park estimate for the release being publish to npm registry.

**Comment by nomiddlename** [comment]
Probably within a couple of weeks - I'm trying to fix up the streamroller dependency (#758 amongst others) and that's the major blocker for a 4.x release.

**Comment by csantanapr** [comment]
Thanks @nomiddlename for responding 👍 , if you don't mind I will use this issue to track the release.

**Comment by nomiddlename** [comment]
I've added this to the 4.0.0 milestone, so that I remember to close this issue once that is released.

**Comment by csantanapr** [comment]
Any updates on this issue?

**Comment by nomiddlename** [comment]
Still working on the streamroller issues  - it's using a lot of synchronous file system calls which will end up using lots of memory and causing performance issues, so I need to get those fixed before I can change log4js to use the new version.

**Comment by csantanapr** [comment]
Ah cool thanks @nomiddlename for the quick update 👍

**Comment by csantanapr** [comment]
Thanks @nomiddlename
