### ISSUE TITLE
tcp appender not compatible with fluentbit

### ISSUE THREAD

**Issue by nuhamind2** [log4js-node/log4js-node#809]
I tried using tcp appender with fluentbit tcp input plugin (as the server). Expectedly , it doesn't work. Fluentbit complain that the input message is invalid JSON. It seem the cause is "\_\_LOG4JS\_\_" delimiter.

If I change the delimiter to space or new line, it work with fluentbit. Maybe option for fluentbit compability
can be added.

**Comment by nomiddlename** [comment]
The option to specify your own delimiter was included in log4js@6.2.0
