### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by baldraider** [log4js-node/log4js-node#812]
I'm getting this error while node application :
`Worker 18 died..
/home/sasuke/app-api-v2/node_modules/rfdc/index.js:44
    if (o instanceof Date) return new Date(o)
          ^
RangeError: Maximum call stack size exceeded
at cloneProto (/home/sasuke/app-api-v2/node_modules/rfdc/index.js:44:11)`

Node version : 7.10
Log4js Version : 3.0.6

**Comment by nomiddlename** [comment]
Hi - what makes you think this is caused by log4js? I can't see anything in the snippet you've posted that would suggest that. Does this only happen when you're logging something?

**Comment by nomiddlename** [comment]
Going to close this one because we never got any more information.
