### ISSUE TITLE
Potential Bug in Custom Json Layout - Date Format Not Aligned

### ISSUE THREAD

**Issue by prufeng** [log4js-node/log4js-node#814]
Found there is a potential bug in custom Json layout use case.

The date format of the startTime in custom Json layout log is ISO8601_WITH_TZ_OFFSET_FORMAT, while in default layout it is ISO8601_FORMAT (local time).

Should be aligned?
Or is there any way to change the custom layout date format to ISO8601_FORMAT?

**Comment by nomiddlename** [comment]
Could you give me some more details please? What is the custom JSON layout you're using?

**Comment by prufeng** [comment]
@nomiddlename 
Can reproduce like this, `console` prints local time, `errors` output timezone offset format.
```javascript
log4js.addLayout('json', function (config) {
    return function (logEvent) { return JSON.stringify(logEvent) + config.separator; };
});

const ptn = '[%d] [%p] [%c] - %m';
log4js.configure({
    "appenders": {
        "console": {
            "type": "console",
            layout: {
                type: 'pattern',
                pattern: ptn
            }
        },
        "errorFile": {
            "type": "file",
            "filename": "logs/log4js-errors.log",
            layout: { type: 'json', separator: ',' }
        },
        "errors": {
            "type": "logLevelFilter",
            "level": "ERROR",
            "appender": "errorFile",
        }
    },
    "categories": {
        "default": { "appenders": ["console", "errors"], "level": "DEBUG" }
    }
});
```

**Comment by victor0801x** [comment]
I guess @prufeng means

```js
const dateFormat1 = require("date-format@1.2.0");
console.log(dateFormat1("yyyyMMdd-hh:mm:ss.SSSO", new Date()));
  // "20181207-16:56:57.023+0800" (local datetime with local_timezone)

const dateFormat2 = require("date-format@2.0.0");
console.log(dateFormat2("yyyyMMdd-hh:mm:ss.SSSO", new Date()));
  // "20181207-08:56:57.027+0800" (utc datetime with local_timezone)

// and in 1.x we can pass timeoffset to transform datetime
// but not in 2.x
console.log(dateFormat1("yyyyMMdd-hh:mm:ss.SSSO", new Date(), -120));
  // "20181207-10:56:57.025+0200"
console.log(dateFormat2("yyyyMMdd-hh:mm:ss.SSSO", new Date(), -120)); 
  // "20181207-08:56:57.028+0800" (still utc with local_timezone)
```
right?

**Comment by nomiddlename** [comment]
log4js has no control over the format of the strings used for `Date` objects under these circumstances. `JSON.stringify` calls `Date.toJSON`, which returns the same as `Date.toISOString()`. See [JSON.stringify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) in the MDN docs for details. You might be able to change it by supplying a replacer function to `JSON.stringify` as the docs suggest.

**Comment by prufeng** [comment]
> log4js has no control over the format of the strings used for `Date` objects under these circumstances. `JSON.stringify` calls `Date.toJSON`, which returns the same as `Date.toISOString()`. See [JSON.stringify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) in the MDN docs for details. You might be able to change it by supplying a replacer function to `JSON.stringify` as the docs suggest.

Yup, already checked the source code and found the same answer, thank you.
