### ISSUE TITLE
Document '.' as category separator

### ISSUE THREAD

**Issue by ankon** [log4js-node/log4js-node#818]
Log4js seems to have support for hierarchies of loggers by using the '.' character as separator:
https://github.com/log4js-node/log4js-node/issues/392#issuecomment-313830423
https://github.com/log4js-node/log4js-node/commit/5283782#diff-563911440c8b98daa0ca68f53193a251R47 (although it seems that even before this was somewhat working due to prefix matching?)

I cannot find any documentation that spells out this support, and unfortunately there is also an older issue which seems to indicate that no such support exist: https://github.com/log4js-node/log4js-node/issues/193#issuecomment-39157450.

It would be great to have this documented to help future googlers :)

**Comment by nomiddlename** [comment]
There is some documentation that mentions [category separators](https://log4js-node.github.io/log4js-node/terms.html), but it should be made clearer. Always happy to see pull requests that improve the documentation.
