### ISSUE TITLE
Allow overriding levels/colors

### ISSUE THREAD

**Issue by nonyy** [log4js-node/log4js-node#821]
It should be possible to completely override levels/colors and that includes changing color library. Currently it's only possible to add custom levels.

**Comment by nonyy** [comment]
@nomiddlename the docs state otherwise:

> Levels defined here are used in addition to the default levels, with the integer value being used to determine their relation to the default levels. 

it should be possible to completely override levels i.e. no trace level or so. Just my custom levels. 

Regarding color library, I implemented my own color function, that's it.

**Comment by nomiddlename** [comment]
If you want to use your own colour library, then writing your own custom layout (or perhaps using the pattern layout) is probably the way to go. I don't think I'll support replacing all the levels with custom levels - could you give me a good reason why you don't just ignore the levels you're not interested in?

**Comment by nomiddlename** [comment]
Closing this one, nothing to fix here.
