### ISSUE TITLE
I want to log the request parameter information

### ISSUE THREAD

**Issue by jiangyan33** [log4js-node/log4js-node#823]
When using log4js as middleware, I wanted to record the request parameter information, but I could not find this function. I looked at the source code (connect-logger.js), and it seemed that it was not implemented,Would you consider adding this feature in a later version?

**Comment by nomiddlename** [comment]
For GET requests, the request parameters should be logged as part of the URL. Is this not working?

**Comment by jiangyan33** [comment]
Most are post requests, passing the data using json.

**Comment by Simmyoungsub** [comment]
I think related to #875.

**Comment by nomiddlename** [comment]
Yes, you can implement this by following @Simmyoungsub instructions in the [connect-logger docs](https://log4js-node.github.io/log4js-node/connect-logger.html).

**Comment by nomiddlename** [comment]
I'm going to close this because the custom connect-logger function can do this.
