### ISSUE TITLE
config file does not allow subcategory to inherit appenders

### ISSUE THREAD

**Issue by pharapiak** [log4js-node/log4js-node#824]
Contrary to the description of category hierarchies [here](https://log4js-node.github.io/log4js-node/terms.html), it seems that if I define a child category in a config file without appenders, the config file validation fails with the error, 
> category "myapp.child" is not valid (must be an object with properties "appenders" and "level").

Here's my config: 

> {
    "appenders": {
        "console": { "type": "console", "layout": { "type": "colored" } }
    },
    "categories": {
        "default": { "appenders": [ "console" ], "level": "WARN" },
        "myapp": { "appenders": [ "console" ], "level": "INFO" },
        "myapp.child": { "level": "DEBUG" }
    },
}

A quick scan of the code suggests that if we do a getLogger('myapp.child'), and there is no config for myapp.child, we'll inherit all of 'myapp's config, but if there _is_ a config for that child, it needs to be complete.

**Comment by k7sleeper** [comment]
One of many workarounds:

You can call `configure()` without that incomplete child configuration and then execute:
```js
log4js.getLogger('myapp.child').setLevel('DEBUG');
```

**Comment by pharapiak** [comment]
I'm working in an environment where all of the configuration is done with a config file, so I can't use a API-based workaround.

I come from a log4j / log4.net background, with a logger per source file (usually); with that setup, it's nice to be able to configure a hierarchy with inheritance.

 @nomiddlename , would you consider a PR along these lines?

- when defining a child category, all of the appenders and verbosity settings of the parent category apply, and the settings of the child category are handled as deltas.
- child category appenders would be in addition to those of the parent.  
- child category verbosity would override those of the parent
- this would apply recursively through a parent-child hierarchy

Is there a use case for allowing a child category's config to completely replace that of the parent?

**Comment by nomiddlename** [comment]
Sounds ok to me - having anything unspecified in the child category config inherit from the parent makes sense.

**Comment by pharapiak** [comment]
One caution...

With the current implementation, if somebody cranks up the verbosity for a child category, that extra 'noise' won't be sent to the appenders specified for the parent, unless the same appenders are specified for the child.

The functionality I'm suggesting would break that, since child appenders would be in addition to those of the parent.  Perhaps we should include an option to keep the old behaviour?   Say, "inherit": "OFF"?

Log4j subcategories also inherit appenders, unless the child category has "additivity=false".   IMO, "inherit=off" is more clear.
(see https://veerasundar.com/blog/2009/08/log4j-tutorial-additivity-what-and-why/)

**Comment by pharapiak** [comment]
This [PR](https://github.com/log4js-node/log4js-node/pull/863) has resolved this issue.

Unless a category has inherit=false, it will a) merge in unique appenders from parent categories, and b) inherit the level from the parent category if it doesn't specify its own level directly.  This inheritance is recursive.
