### ISSUE TITLE
Is there a changelog for v4?

### ISSUE THREAD

**Issue by fluxsauce** [log4js-node/log4js-node#828]
Congratulations on the release! I see docs on v2 and v3, but not on v4 (unless I'm looking in the wrong place). What changed and what's the migration path (if any)? Thanks!

**Comment by nomiddlename** [comment]
No real change log, but I group issues and pull requests for a release into a milestone in github. [Here's the one for the 4.0.0 release](https://github.com/log4js-node/log4js-node/milestone/51?closed=1), which shows which issues were fixed and which PRs were merged. Main change is the streamroller lib update, which could have weird side effects like your log filenames may be slightly different (an extra '.' kind of thing). For most users there should be no changes needed to config or anything.

**Comment by fluxsauce** [comment]
Sounds good, and looking at #826 I don't think it'll require any real changes on our end. Thanks again!

**Comment by julmot** [comment]
Would be very good to have a description in all releases (Git Tags) or in a CHANGELOG.md. Otherwise people like me searching minutes for finding this information.

**Comment by nicojs** [comment]
Internally, the multiprocess reporter uses a different serialization library (`flatted`). So if you depend on that (for example for tests) you might need to update it.
