### ISSUE TITLE
some questions about how rotate logs

### ISSUE THREAD

**Issue by didaquis** [log4js-node/log4js-node#829]
Hi. I'm using log4js 3.0.6 and this is my configuration of appenders: 
```
log4js.configure({
	appenders: {
		out:{ type: 'stdout' },
		file_log_info: { type: 'file', filename: 'logs/application.log', maxLogSize: 204800, backups: 0, keepFileExt: true },
		file_log_error: { type: 'file', filename: 'logs/application_error.log', maxLogSize: 204800, backups: 0, keepFileExt: true },
		file_log_info_filter: { type:'logLevelFilter', level: 'info', appender: 'file_log_info' },
		file_log_error_filter: { type:'logLevelFilter', level: 'error', appender: 'file_log_error' }
	},
	categories: {
		default: { appenders: [ 'file_log_info_filter', 'file_log_error_filter', 'out'], level: 'all' }
	}
});
```

I want to know how I need to modify my configuration for non rotate logs file but limit the size of logs. Anyone can explain me? 
I tried to set `backups: 0` but seems not work as I expected.

**Comment by nomiddlename** [comment]
If you set `maxLogSize` then the minimum number of backups is 1. To have no backup file at all would mean that the file would be constantly being truncated once it got to the max size.

**Comment by didaquis** [comment]
Hummm... let me check if I understand you correctly.
If I remove `maxLogSize ` property all the logs are writted to one file AND this is truncated once it got to the max sixe?? In this case, what is the max size??

**Comment by nomiddlename** [comment]
If you don't set `maxLogSize` then there is no maximum size for the file, and no files will be truncated.

**Comment by didaquis** [comment]
OK. Thanks for the info.
