### ISSUE TITLE
Document breaking changes (v4)

### ISSUE THREAD

**Issue by nicojs** [log4js-node/log4js-node#834]
@nomiddlename, my friend. Thanks for the ongoing hard work, I know you're doing it all in your spare time. 

Quick question, what are the breaking changes in v4? I can't seem to find it in a changelog or something. It might be a good idea to keep a changelog.md file in the root. 

If you send me a reply here, I can create a PR in order to create the changelog.

Thanks again! Log4js (v3) works like a charm in stryker-mutator.

**Comment by nomiddlename** [comment]
This issue might help you: https://github.com/log4js-node/log4js-node/issues/828

You're not the first to ask for a change log. I'll maintain one from now on - I was hoping the milestones and PRs would do that job, but it seems not.
