### ISSUE TITLE
soft reboot from a watchr update

### ISSUE THREAD

**Issue by appdreamer** [log4js-node/log4js-node#835]
I have implemented watchr to watch the log4js config file. When changes are saved to the file, watchr update function works. All I need to do is shut down and restart log4js, however this has been difficult to get to work. I'm initializing with 
`logger = log4js.getLogger;
`
I see that you can pass in a callback to shutdown function. I'm assuming I will need to reload the config file. Can you please provide a clean example of how to shutdown and restart log4js? Is it something like this?

… from watchr case 'update':
```
log4js.shutdown(cb);
log4js.configure('myconfigfile.json');
logger = log4js.getLogger();
```
I get errors with this on log4js.shutdown(cb);

**Comment by appdreamer** [comment]
Actually, found this on one of the deep threads on this library...with minor improvements for when there is no error...
```
console.log('shutting down log4js');
log4js.shutdown((err) => {
     if (err!=undefined) {
           consol.log('shutting down log4js msg: ' + err);
     }
});
log4js.configure('./myconfigfile.json');
console.log('rebooting log4js');
logger = log4js.getLogger();

```

**Comment by nomiddlename** [comment]
you need to call `log4js.configure` in the callback for `log4js.shutdown`. So, something like:
```javascript
//in some function called by watchr to tell you the config has changed
log4js.shutdown(() => {
  log4js.configure('myconfigfile.json');
});
```

**Comment by nomiddlename** [comment]
Hope this fixed your problem. Please re-open if you have more questions.
