### ISSUE TITLE
Does getLogger() give you a singleton instance?

### ISSUE THREAD

**Issue by wshi93** [log4js-node/log4js-node#837]
Every time I call `log4js.getLogger()`, it keeps creating new instances or it keeps the first instance and returns that to me?
I'm working on a relatively big cli tool. And currently I use `log4js.getLogger(category)` in each file and I use filename as `category` to record this log message is from which file. 

So I would like to know the cost of `log4js.getLogger(category)` or if there could be some potential issues with multiple(one per each file) instances of logger.

Also I wonder if there is better way to integrate filename into log message? Because now it looks like `category` in `log4js` does a lot more than just this.
Thanks

**Comment by nomiddlename** [comment]
Calling `getLogger` multiple times is fine - it does create new instances, but they are fairly lightweight. Logger does have an idea of a context, where you can set key-value pairs that are relevant to a series of log messages. You'd have to use the pattern layout to get the context values to show up in your logs though, they're not part of the basic layout.

**Comment by wshi93** [comment]
Thanks!
I tried logger context, but I think it still won't work if I'm using singleton since I use logger in multiple files. So I guess I'll just create a new logger for each file.
