### ISSUE TITLE
date wrong

### ISSUE THREAD

**Issue by houyanchao** [log4js-node/log4js-node#846]
log4js v1.1.1
node v4.1.0

type:dateFile
![WX20190313-101303](https://user-images.githubusercontent.com/9604104/54249176-2a543880-457a-11e9-903d-e4a0c0a73a74.png)

file create time
![WX20190313-101244](https://user-images.githubusercontent.com/9604104/54249184-37712780-457a-11e9-9cf6-2198d305dbbe.png)

yry-h5-err.log-2019-03-12 file detail(have 2019-03-13 log)
![WX20190313-101333](https://user-images.githubusercontent.com/9604104/54249166-20cad080-457a-11e9-8fdb-5bd26e0e05a5.png)

**Comment by houyanchao** [comment]
how to solve this question, thanks

**Comment by nomiddlename** [comment]
That looks like your file listing is showing the last modified time, not creation time. Last modified time matches up with your log output.

**Comment by nomiddlename** [comment]
Hope that answered your question, I'm going to close this issue. Feel free to re-open if you still think there is a problem.
