### ISSUE TITLE
TypeError thrown in writer.openTheStream.bind(writer)

### ISSUE THREAD

**Issue by Kiyoaki-w** [log4js-node/log4js-node#847]
The console shows like:

/root/DAP/node_modules/log4js/lib/appenders/file.js:59
    writer.closeTheStream(writer.openTheStream.bind(writer));
                                               ^

TypeError: Cannot read property 'bind' of undefined
    at Function.app.reopen (/root/DAP/node_modules/log4js/lib/appenders/file.js:59:48)
    at process.app.sighupHandler (/root/DAP/node_modules/log4js/lib/appenders/file.js:64:9)
    at process.emit (events.js:189:13)
/root/DAP/node_modules/log4js/lib/appenders/file.js:59
    writer.closeTheStream(writer.openTheStream.bind(writer));
                                               ^

TypeError: Cannot read property 'bind' of undefined
    at Function.app.reopen (/root/DAP/node_modules/log4js/lib/appenders/file.js:59:48)
    at process.app.sighupHandler (/root/DAP/node_modules/log4js/lib/appenders/file.js:64:9)
    at process.emit (events.js:189:13)
/root/DAP/node_modules/log4js/lib/appenders/file.js:59
    writer.closeTheStream(writer.openTheStream.bind(writer));

**Comment by nomiddlename** [comment]
Could you post your log4js config, please? Also which version of node and log4js are you using? What is happening when this error occurs - it looks like the application has been sent a HUP signal? Are you using logrotate in addition to log4js file rotation, maybe?

**Comment by wyzxxx123** [comment]
I have the same problem
win10
node 10.15.1
log4js 4.1.0

When I closed the 'run.bat', something happened.
run.bat:
node main.js
pause

code:
'use strict';
let net = require("net");
const log4js = require('log4js');

log4js.configure( {
     appenders: {
         infoLogger: {
             type: "file",
             filename: "info",
             pattern: ".log"
         },
     },
 
     categories: {
         default: {appenders: ["infoLogger"], level: "all"},
     },
   });

process.on('uncaughtException', (err)=> {
    console.log(err.stack);
});

const server = net.createServer((c)=>{
    c.on('data', (data)=>{
        
    });

    c.on('end', ()=>{
        
    });

    c.on('error', (e)=>{

    });
});

server.on('error', (err) => {
    throw err;
});

server.listen(8124, () => {

});

**Comment by nomiddlename** [comment]
Looks like this has been broken since the steamroller upgrade.

**Comment by nomiddlename** [comment]
A fix was published to NPM in version 4.2.0
