### ISSUE TITLE
connectLogger format no cookie data

### ISSUE THREAD

**Issue by dmfeng** [log4js-node/log4js-node#848]
connect-logger.js : assembleTokens one header data, no cookie data

':remote-addr - - [:date] ":method :url :body HTTP/:http-version" :status :content-length ":referrer" ":user-agent" ":cookie_a" ":cookie_b" :ip'

eg:   :cookie['a']

**Comment by nomiddlename** [comment]
You could use the `:req[cookie]` token to output all cookies, would that be enough?

**Comment by dmfeng** [comment]
@nomiddlename it can work,but all cookie is so big.
I tried the following ways to work, But with headers,not better.
req: why from req.headers?
`var format='":req[a]" ":req[b]"';
   req.headers.a = req.cookies['a'] || '-';
   req.headers.b= req.cookies['b'] || '-';
`

**Comment by nomiddlename** [comment]
It is possible to pass a custom format function to the [connect-logger](https://log4js-node.github.io/log4js-node/connect-logger.html), you could do what you want that way.
