### ISSUE TITLE
log4js with parceljs

### ISSUE THREAD

**Issue by nagoorkani** [log4js-node/log4js-node#849]
I am getting the below error when I integrate log4js within a `parcel+ts+react` project.

![Screen Shot 2019-03-20 at 10 45 00 AM](https://user-images.githubusercontent.com/1751374/54698554-7fa1c400-4afd-11e9-8b95-213d87826894.png)

package.json
`{
  "name": "ts-parcel-cra",
  "version": "1.0.0",
  "description": "",
  "main": "index.tsx",
  "scripts": {
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html",
    "test": "jest"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/jest": "^24.0.4",
    "@types/log4js": "^2.3.5",
    "@types/react-test-renderer": "^16.8.1",
    "jest": "^23.0.0",
    "jest-extended": "^0.11.0",
    "parcel-bundler": "^1.11.0",
    "react-test-renderer": "^16.8.2",
    "ts-jest": "^23.10.5",
    "typescript": "^3.3.3"
  },
  "dependencies": {
    "@types/node": "^11.10.5",
    "@types/react": "^16.8.3",
    "@types/react-dom": "^16.8.1",
    "axios": "^0.18.0",
    "axios-mock-adapter": "^1.16.0",
    "core-js": "^3.0.0",
    "log4js": "^4.0.2",
    "node": "^11.11.0",
    "react": "^16.8.2",
    "react-dom": "^16.8.2",
    "reset.css": "^2.0.2"
  }
}`

**Comment by nomiddlename** [comment]
Looks like you're trying to use the file appender in a browser? That won't work.

**Comment by lamweili** [comment]
Closed due to extended period of inactivity.
