### ISSUE TITLE
Letter T in my file

### ISSUE THREAD

**Issue by NotDonaldTrump** [log4js-node/log4js-node#850]
Got a T in my time stamp

My output:

[2019-03-22T17:28:06.079] [MESSAGE] LogBot - "#bot-spam" Parton | 𝓼𝓽𝓪𝓷𝓬𝓮.𝓭#8122 said "test" 

My Config:

log4js.configure({
levels: {
MESSAGE: { value: 20001, colour: 'green' }},
appenders: { LogBot: { type: 'dateFile', filename: './logs/all-the-logs.log' } },
categories: { default: { appenders: ['LogBot'], level: 'message' } }});
logger.message('LogBot Starting Up');

Any help is appreciated!

**Comment by nomiddlename** [comment]
That's the [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) combined date and time format.

**Comment by nomiddlename** [comment]
I'm going to close this one, if you have any more questions about timestamps feel free to re-open the issue.
