### ISSUE TITLE
[Request] 4.x Change Log/Migration Guide

### ISSUE THREAD

**Issue by ianlamb** [log4js-node/log4js-node#853]
Hi, I'm running into a bug since upgrading to 4.x but I can't even figure out what the breaking changes are. [The docs](https://log4js-node.github.io/log4js-node/) seem out of date (only a migration guide for 3.x) and there are no release notes anywhere.

**Comment by nomiddlename** [comment]
The github [milestone for 4.0.0](https://github.com/log4js-node/log4js-node/milestone/51?closed=1) should help you work out what changed. Places that bugs could hide would be anything to do with log rotation, really.

**Comment by nomiddlename** [comment]
I'm going to close this issue. If you've got any other questions about 4.x, feel free to re-open.
