### ISSUE TITLE
Do not create log files before writing to them

### ISSUE THREAD

**Issue by KonovalovaKV** [log4js-node/log4js-node#854]
You can add the ability not to create log files when calling log4js.configure(config). Instead, create a file when you first write to it.
Maybe there is something that will help me to achieve this?

**Comment by nomiddlename** [comment]
You might be able to use the [multiFile appender](https://log4js-node.github.io/log4js-node/multiFile.html). It creates log files based on properties you set in the log event, and does not create files until it sees that property.

**Comment by KonovalovaKV** [comment]
Thank you! This is combined with rolling by date? I can not find information(

**Comment by nomiddlename** [comment]
Yes, you can use all the date config on the file appender. Under the hood, they use the same code.

**Comment by KonovalovaKV** [comment]
Am I doing something wrong? But it does not work for me. There is no breakdown by day.
`
appenders: {
    app: {
      type: 'multiFile',
      base: 'logs/',
      pattern: '.yyyy-MM-dd',
      layout: LAYOUT,
      compress: true,
      property: 'categoryName',
      extension: '.log'
    }
  },
  categories: {
    default: { appenders: ['app'], level: LEVEL }
  }
`

**Comment by nomiddlename** [comment]
Did you try using `alwaysIncludePattern: true` ?

**Comment by KonovalovaKV** [comment]
I tried, does not work.
version 3.0.6

**Comment by nomiddlename** [comment]
Ah, ok - yes, date rolling will only work with multiFile if you use 4.0.0 or greater.

**Comment by KonovalovaKV** [comment]
Yes, it is work. Thank you!
But sometimes I get exception, when I stop my app.
![image](https://user-images.githubusercontent.com/1922073/55453497-59544c00-5606-11e9-811c-90fe187c78dd.png)

I do not know whether this is due to the new version or configuration. 
`
appenders: { app: { type: 'multiFile', base: 'logs/', pattern: '.yyyy-MM-dd', layout: LAYOUT, compress: true, property: 'categoryName', extension: 'log', alwaysIncludePattern: true } }, categories: { default: { appenders: ['app'], level: LEVEL } }
`

**Comment by KonovalovaKV** [comment]
And is it possible to add the ability to rotate by date so that you can specify not only the pattern, but also the path using the pattern.
For example: filePattern="logs/arch/{yy-MM-dd}/add/update.log"

**Comment by nomiddlename** [comment]
When you stop your app, does your shutdown function call `log4js.shutdown`? This makes sure all data is written to the log files before closing, and also removes that SIGHUP handler that is causing your error above.

**Comment by KonovalovaKV** [comment]
Yes, I added call log4js.shutdown. 
And it partially earned.
But when calling the Alt + F4 combination, an error appears.
![image](https://user-images.githubusercontent.com/1922073/55454710-07fa8b80-560b-11e9-8a33-87948254e7c2.png)

**Comment by nomiddlename** [comment]
`log4js.shutdown` takes a callback as an argument - did you supply one?
example:
```
log4js.shutdown(() => {
  // log4js has finished writing when this function gets called
});
```

**Comment by KonovalovaKV** [comment]
No, I don`t use. Now I write:

`
log4js.shutdown(() => {
  })
`
And it works correctly. Is it required to specify?

**Comment by KonovalovaKV** [comment]
Thanks for the help!

**Comment by nomiddlename** [comment]
No problem - glad you got things working.
