### ISSUE TITLE
Implement dateFileSync appender type

### ISSUE THREAD

**Issue by toddhay-NOAA** [log4js-node/log4js-node#856]
I recently started using log4js, thank you for all of the work on this.  I'm currently using the fileSync appender type, which works well, but am hoping to leverage a similar synchronous capability with the dateFile appender type.  Are there any plans for implementing a dateFileSync appender type?

**Comment by nomiddlename** [comment]
I don't think you need the sync appender any more. Instead you can use the file and dateFile appenders with the option `flags: 'as'` - the 's' means synchronous writes. See the [node fs module docs](https://nodejs.org/api/fs.html#fs_file_system_flags) for more options.

**Comment by toddhay-NOAA** [comment]
Oh interesting, thanks for the tip @nomiddlename , I will give that a go and report back.

**Comment by toddhay-NOAA** [comment]
I just confirmed that adding the `flags: 'as'` does indeed work to make the dateFile appender synchronous.  Thanks for the assistance with this @nomiddlename.  I'm closing this ticket.
