### ISSUE TITLE
How does log4js date generate files?

### ISSUE THREAD

**Issue by 200688523** [log4js-node/log4js-node#857]
How does log4js date generate files?

**Comment by Simmyoungsub** [comment]
Is it date-file-rolling?

example
https://github.com/log4js-node/log4js-node/blob/master/examples/date-file-rolling.js

**Comment by nomiddlename** [comment]
You use the [`dateFile` appender](https://log4js-node.github.io/log4js-node/dateFile.html).

**Comment by misland** [comment]
> You use the [`dateFile` appender](https://log4js-node.github.io/log4js-node/dateFile.html).

thanks,solve my question:)

**Comment by 200688523** [comment]
Thank you, the problem has been solved
