### ISSUE TITLE
console and stdout appenders start printing out whole Level object in node v12

### ISSUE THREAD

**Issue by Elmaranin** [log4js-node/log4js-node#859]
looks like this:
[2019-04-24T08:47:32.597] [Level { level: 20000, levelStr: 'INFO', colour: 'green' }]

**Comment by nomiddlename** [comment]
Fix published to NPM in log4js@4.1.1

**Comment by Elmaranin** [comment]
Now it's even worse with version 4.1.1  =(. New release fixed problem only with console appender, but 'stdout' and 'dateFile' appenders still produces full level string:
[2019-05-06T13:13:32.090] [Level { level: 20000, levelStr: 'INFO', colour: 'green' }] http-server 
moreover now 'alwaysIncludePattern' attribute for dateFile appender stops working, it always generates file without pattern now.
