### ISSUE TITLE
logs are not writable to files on prod server  

### ISSUE THREAD

**Issue by AhmadShahid** [log4js-node/log4js-node#864]
I have the problem on my EC2 instance log files are not writable even applying permission to it 

log4js.fileAppender - Writing to file /home/........../logs/app.log, error happened { Error: EACCES: permission denied, open '/home/..........//logs/app.log'

**Comment by nomiddlename** [comment]
Hard to say what is going wrong here - most likely a mismatch between the user your application is running as and the file permissions.

**Comment by nomiddlename** [comment]
I'm going to assume you fixed your problem and this isn't a log4js issue. Please re-open if you have more information.

**Comment by alisherafat01** [comment]
Same issue for me. what should i do? i can't even open the log file created by this library even in the windows file manager (explorer)

**Comment by nomiddlename** [comment]
Your EC2 instance is a windows server? Are you using the same user to read the files as the application is running as?

**Comment by devorrah** [comment]
I'm using log4js 6.3.0

log4js logs everything fine when I run it with the node command. When I try to run it as a daemon using forever it no longer logs anything and forever logs the following error.

//WITHIN THE .forerver/forever.log file
**log4js.fileAppender - Writing to file critter.log, error happened  { [Error: EACCES: permission denied, open '/critter.log']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/critter.log' }**

this is the config method
**log4js.configure({
        appenders: { PIR: { type: 'file', filename: 'critter.log' } },
        categories: { default: { appenders: [ 'PIR' ], level: 'trace' } }
});

const logger = log4js.getLogger('PIR');
logger.trace('--------PIR STARTED--------');
.   .   .   .   .
.   .   .   .   .
logger.trace('MOVEMENT' + ' at ' + currentTime);**

I tried this but it produces the same error.

**chmod 777 /home//dt/PIR_sensor_project/pir.js;

forever start --sourcedir /home/dt/PIR_sensor_project --workingdir /home/dt/PIR_sensor_project -l forever.log -o out.log -e err.log /home//dt/PIR_sensor_project/pir.js**

**Comment by rnd-debug** [comment]
@devorrah Hello.
According to the error message, the file that log4js tries to write is located at your root ("/"). According to [forever docs](https://www.npmjs.com/package/forever), working and source dirs arguments should be provided with an uppercase "D" (i.e. "sourceDir" and "workingDir"), which is not the case in the command you provided.
IMHO, this is the cause of the issue. Please, confirm.

**Comment by devorrah** [comment]
> @devorrah Hello.
> According to the error message, the file that log4js tries to write is located at your root ("/"). According to [forever docs](https://www.npmjs.com/package/forever), working and source dirs arguments should be provided with an uppercase "D" (i.e. "sourceDir" and "workingDir"), which is not the case in the command you provided.
> IMHO, this is the cause of the issue. Please, confirm.

rnd-debug I made the changes you suggested and changed this line to include the full file path:
**appenders: { PIR: { type: 'file', filename: ' /home/dt/PIR_sensor_project/critter.log' } }**
and it worked beautifully. ty
