### ISSUE TITLE
json object priting in multiple lines

### ISSUE THREAD

**Issue by saumilsdk** [log4js-node/log4js-node#865]
When i log following line,
`logger.debug({ a: 'this is something', b: 'this is something', c: 'this is something', d: 'this is something' });`

It prints 4 lines like below. Also after deploying on AWS it prints in each line. 
```
{ a: 'this is something',
  b: 'this is something',
  c: 'this is something',
  d: 'this is something' }
```

**Comment by Simmyoungsub** [comment]
{ a: 'this is something',
  b: 'this is something',
  c: 'this is something',
  d: 'this is something' }

This is an object. It is not a Json object.
The internally used util.format method seems to return an Object
So, Would you like to use 'custom layout'?
https://github.com/log4js-node/log4js-node/blob/master/docs/layouts.md#custom-layout-example

I hope it helps.

**Comment by nomiddlename** [comment]
Yep, @Simmyoungsub is correct - the default layout just uses `util.format`. If you want JSON output then you'll have to write a custom layout.

**Comment by Simmyoungsub** [comment]
@nomiddlename Thank you!

**Comment by nomiddlename** [comment]
I'm going to close this issue, as there's nothing to fix here. If you think otherwise, please feel free to re-open.
