### ISSUE TITLE
log4js - change filename for appender on runtime

### ISSUE THREAD

**Issue by saampryu** [log4js-node/log4js-node#871]
I have a custom appender in log4js configure, and I want to change the filename for that on run time.
Is it possible?
I am doing something like this in my configuration:
```
log4js.configure({  
   appenders:[  
      {  
         type:'file',
         filename:path.join(__dirname, 'log/cheese_1.log'),
         category:'cheese'
      }
   ],
   levels:{  
      "cheese":'info'
   }
});
```

It works fine, but on run time, I want to change the filename to 'cheese_2.log' and so on..

**Comment by nomiddlename** [comment]
There's two ways to do this - when you want to change the file name call `log4js.shutdown` and then `log4js.configure` with the new config. Or use the [multiFile appender](https://log4js-node.github.io/log4js-node/multiFile.html).

**Comment by saampryu** [comment]
Thanks!
