### ISSUE TITLE
typescript docs not working

### ISSUE THREAD

**Issue by WeihanLi** [log4js-node/log4js-node#874]
As the docs from [readme](https://github.com/log4js-node/log4js-node#typescript), it should be 

``` typescript
import { configure, getLogger } from './log4js';
configure('./filename');
const logger = getLogger();
// ...
```

but that's not working for me, I use the code like belows for instead:

``` typescript
import * as log4js from "log4js";
log4js.config({
  appenders: {
    file: { type: 'file', filename: './logs.log' },
    console: { type: 'console' }
  },
  categories: {
    default: { appenders: ['file', 'console'], level: 'debug' }
  }
});
let logger= log4js.getLogger("main");
```

and I'm using log4js version  4.1.0

**Comment by leak4mk0** [comment]
Hi,
I think there is a error in the document.
We should import 'log4js' instead of './log4js', normally.
Could you try the following code?
```typescript
import { configure, getLogger } from 'log4js'; // <--- valid module name
configure('./filename');
const logger = getLogger();
// ...
```

**Comment by WeihanLi** [comment]
I've tried `import { configure, getLogger } from 'log4js';` before but get an error like can not find module `log4js`, I think maybe there's something wrong with the types definition

**Comment by WeihanLi** [comment]
I've tried a new project with latest log4js, it works greatly, maybe because I've had a `@types/log4js` installed before?

**Comment by leak4mk0** [comment]
It can be possible because `@types/log4js` has been deprecated.
Can I see an error and npm version of `@types/log4js`?

**Comment by WeihanLi** [comment]
I'm using the latest `@types/log4js` seemed to be `2.3.5`, can not reproduce the error for now, sorry to disturb...

**Comment by Simmyoungsub** [comment]
"log4js.config" method is exist?

**Comment by WeihanLi** [comment]
maybe like that, I forgot it... it's couple of days ago...

**Comment by leak4mk0** [comment]
I'm glad that the problem was solved.
I'll close this issue after when my PR is merged.

**Comment by WeihanLi** [comment]
OK, Thanks @leak4mk0

**Comment by nomiddlename** [comment]
Docs fixed by @leak4mk0 - thanks!

**Comment by leak4mk0** [comment]
I didn't understand who can close an issue.
Thank you for closing this issue, @nomiddlename
