### ISSUE TITLE
compile warning clusterJS ...

### ISSUE THREAD

**Issue by seunggabi** [log4js-node/log4js-node#880]
Hello,
I have a issue...
I searched website for error fix
however I don't find it

```
 WARNING  Compiled with 3 warnings                                                                                                                                                              
 warning  in ./node_modules/log4js/lib/appenders/index.js
Critical dependency: the request of a dependency is an expression
 warning  in ./node_modules/cluster/lib/master.js
Critical dependency: the request of a dependency is an expression
 warning  in ./node_modules/defaultable/defaultable.js
Critical dependency: the request of a dependency is an expression
```
please check this!

<img width="1254" alt="스크린샷 2019-05-17 오전 12 57 16" src="https://user-images.githubusercontent.com/8468371/57868890-c6cadd80-783e-11e9-8150-e30b6355d3cb.png">

**Comment by nomiddlename** [comment]
Could you show your log4js config, please? Also list what version of node, log4js, and webpack you're using.

**Comment by seunggabi** [comment]
### My version
- `node`: `v12.2.0`
- `log4js`: `v4.2.0`
- `webpack`: `v4.28.4`

### log4js.conf
```json
{
  "levels": {
    "express": "INFO",
    "user": "DEBUG",
    "system": "WARN",
    "agent": "ERROR"
  },
  "replaceConsole": true,
  "appenders": [
    {
      "type": "file",
      "filename": "~/logs/error.log",
      "maxLogSize": 524288,
      "backups": 100,
      "compress": true
    }
  ]
}
```

@nomiddlename 
Hi! I commented my information
I'm sorry, I'm so late
Thanks for your help :)

**Comment by nomiddlename** [comment]
That error looks like it comes from the cluster module not log4js - I don't think you can use the cluster module in the browser. 

The warnings definitely come from log4js, but they should not stop anything from working.

**Comment by seunggabi** [comment]
@nomiddlename 
Thanks, quickly reply comment
I understand your comment, so I'll find different solution.
bye~
