### ISSUE TITLE
Support Multiple Appenders

### ISSUE THREAD

**Issue by AartiJ** [log4js-node/log4js-node#883]
Hello,
     I am trying to achieve Log4JS multiple appenders feature where I want the log messages on console in log file and in my mocha allure report. How can I achieve this. Please help.
Below is my code but it's not working.

require('mocha-allure-reporter');
const { configure, getLogger, Logger  } = require("log4js");
describe("Logging Service", () => {
    let log;
    const testStep = allure.createStep("Logs", () => {
        this.log.info("Test.");
    });

    beforeEach(()=> {
        configure({
                appenders: [
                    { type: 'file', filename: 'log/access.log'},
                    { type: 'console' }
                ]
        });
        this.log = getLogger("LoggingService");
    });
    it("should log", () =>  {
        testStep();
    });
});

**Comment by nomiddlename** [comment]
What version of log4js are you using? Because that config hasn't been a valid format for years. Also, don't call `configure` before each test, just call it once at the beginning.

**Comment by AartiJ** [comment]
I am using v 4.2.0. Also the format I got it from online forums. I did try the one from json file of log4JS example. But somehow it does not do both. It just prints either on console or in file. But not both together. And also it does not come into the allure report if I call within allure createStep.

**Comment by nomiddlename** [comment]
If you're using 4.2.0, then you should have got an error telling you that your config was wrong. If you're not seeing that error, then it sounds like your `log4js.configure` is never being called. The simplest config you could use to get output on the console and in a file looks like this:
```javascript
log4js.configure({
  appenders: {
   out: { type: 'stdout' },
   file: { type: 'file', filename: 'log/access.log' }
  },
  categories: {
    default: { appenders: ['out', 'file'], level: 'debug' }
  }
});
```
Put that at the start before your tests are run (configure should only be called once in an application).

**Comment by AartiJ** [comment]
Thanks @nomiddlename It works now.

**Comment by UP942901** [comment]
Thanks @nomiddlename i had the same issue, now fixed

**Comment by Kenhuey** [comment]
Thanks @nomiddlename
