### ISSUE TITLE
appender "logstash" is not valid (type "logstashUDP" could not be found)

### ISSUE THREAD

**Issue by prakasa-tkpd** [log4js-node/log4js-node#885]
https://github.com/log4js-node/log4js-node/blob/d83e211d7d4c608d8ab069130ece897aa8237d4a/examples/logstashUDP.js#L22

I using `@log4js-node/logstashUDP` but no data sent to UDP server.

configure:
```
type: '@log4js-node/logstashudp',
```

**Comment by nomiddlename** [comment]
Are you raising this issue to get the example file changed? Because you already have an issue open on the logstashUDP repository about not being able to get the appender working, so I don't want to duplicate it.
