### ISSUE TITLE
Problem with log4js configuration

### ISSUE THREAD

**Issue by Leksei37** [log4js-node/log4js-node#891]
Hello, can you help me?
I have the following code but I think it is for version 1 of log4js.

`log4js.configure({
	appenders: [
		{ type: 'console' },
		{ type: 'file', filename: 'logs/bot_'+process.argv[2]+'.log' }
	]
});`

Can someone help me to make it correct?
Thanks you!

**Comment by nomiddlename** [comment]
You should probably [read the documentation](https://log4js-node.github.io/log4js-node/index.html), or take a look at the [examples](https://github.com/log4js-node/log4js-node/tree/master/examples). But here's the quick cut-and-paste version:
```javascript
log4js.configure({
  appenders: { console: { type: 'console' }, file: { type: 'file', filename: 'logs/bot_'+process.argv[2]+'.log' } },
  categories: { default: { appenders: ['console', 'file'], level: 'info' } }
});
```

**Comment by nomiddlename** [comment]
I'm going to assume that this solved your problem. Please re-open the issue if you don't agree.
