### ISSUE TITLE
dateFile appender "mode" not working

### ISSUE THREAD

**Issue by ilsundal** [log4js-node/log4js-node#893]
The "mode" flag is not working as specified here:

https://github.com/log4js-node/log4js-node/blob/master/docs/dateFile.md

If I set it to 644 (same as the default value), I get these permissions:

--w----r-T 1 morten morten    15580 Jun 11 11:22 nb-api-server.log

but I should get

-rw-r--r-- 1 morten morten    15581 Jun 11 11:26 nb-api-server.log

**Comment by nomiddlename** [comment]
The leading zero in the mode argument is very important. It's an octal number, not decimal - use `0644` not just `644`, or even better use `0o644`. See the [node.js file modes docs](https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_file_modes) for more details.

**Comment by ilsundal** [comment]
Thanks for the insight. I see that you updated the documentation to say as much. Excellent.

I still have one problem, though, because neither 0644 nor 0o644 are valid JSON integer values, and thus cannot be parsed by Node. Or is there a way around this that I am not aware of?

In any case, one solution could be to allow "mode" to be also a String, e.g. "0644" or "0o644".

**Comment by nomiddlename** [comment]
Yep, easiest way would be to convert to decimal value in your case. Next easiest would be to convert your JSON config into a simple module that just exports the config object.

**Comment by ilsundal** [comment]
Yup, and thanks again.
