### ISSUE TITLE
How to log asynchronously?

### ISSUE THREAD

**Issue by yelexin** [log4js-node/log4js-node#894]
It seems that the IO operation is synchronous. Not sure.
I think it will improve the performance of my app if the logging IO operation is asynchronous.
This is more like a question than an issue.

**Comment by nomiddlename** [comment]
If you're using the file appenders (and most of the other appenders, really) then any I/O should be asynchronous by default. If you're using the stdout/stderr or console appenders then there are some circumstances where output can be synchronous - see the [node.js docs on this](https://nodejs.org/dist/latest-v12.x/docs/api/process.html#process_a_note_on_process_i_o).

**Comment by yelexin** [comment]
Thank you for the infomation. :joy:
