### ISSUE TITLE
Any discussions about this working with debug?

### ISSUE THREAD

**Issue by davimello28** [log4js-node/log4js-node#896]
## What?
I was thinking about forking this project and implementing a feature to make this works together [debug](https://www.npmjs.com/package/debug). I am here to check if there is any interest to implement it's features in the original repository.

## Why?
Since log4js has many advantages in comparison to debug (like log levels, the native features to write a log file, and others) and [debug is the most popular log platform](https://medium.com/@samngms/which-npm-logging-module-to-choose-debug-winston-log4js-and-bunyan-1045fb4b0475), but is oversimplistic, I really think that both can work together. One doesn't exclude the other. 

What do you think?

**Comment by nomiddlename** [comment]
I don't quite understand what you mean, but you're free to fork the project and make any changes you want. Perhaps an example of how and when you'd use it would help?

**Comment by davimello28** [comment]
I've edited my comment but realized during the editing that there is some
 other problem (like separation of concerns) that weight against my proposition so I decide to close the issue.
