### ISSUE TITLE
Using the log data array directly in pattern

### ISSUE THREAD

**Issue by thernstig** [log4js-node/log4js-node#898]
This might be a feature request.

Is the only way to do something like this with the help of tokens?

```javascript
        layout: {
          type: 'pattern',
          pattern: '%[[%d{ISO8601_WITH_TZ_OFFSET}] [%p] %c%] - %m[0], %m[1]'
        }
```

I.e. I want to get each element inserted to `logger.info(param1, param2)` via `%m[i]` where i is the position in the log data array.

Currently the only way to achieve this is like doing:

```javascript
         layout: {
          type: 'pattern',
          pattern:
            '%[[%d{ISO8601_WITH_TZ_OFFSET}] [%p] %c%] - %x{foo0}, %x{foo1}',
          tokens: {
            foo0(logEvent) {
              return logEvent.data[0];
            },
            foo1(logEvent) {
              return logEvent.data[1];
            }
          }
        }
```

**Comment by thernstig** [comment]
@nomiddlename What do you think about this feature? :)

**Comment by nomiddlename** [comment]
This is probably easiest to do by using a [custom layout](https://log4js-node.github.io/log4js-node/layouts.html).

**Comment by thernstig** [comment]
@nomiddlename Yes most likely easy to do, but would it not be a nice default feature? It's much less verbose than the current implementation.

**Comment by nomiddlename** [comment]
I'm trying to keep log4js core as small as I can, so I don't think it needs to be a default feature. I haven't had any other users requesting this, and nobody else has commented on this issue, so this might be specific to your particular use case. There are two ways (the tokens method you've used above, or the custom layout method) to achieve this result as well, so I don't think this needs doing.

**Comment by thernstig** [comment]
Fair stance :) Appreciate your work on log4js!

**Comment by nomiddlename** [comment]
Thanks for raising the issue, sorry it took me so long to respond initially.

**Comment by thernstig** [comment]
Just for future reference, I'll place some more information why I wanted it.

I have about 5-6 appenders, that outputs to various locations, and also custom layouts that can be changed via environment variables (e.g. normalt text vs json). I need to support logging with some variables via `logger.info(param1, param2, param3)`. With the above feature request support, this would have been small code changes that wouldn't have bee verbose. Without the feature, the whole log4js config will become quite bloated. I prefer cleaner code = easier to read, hence why I thought it would be nice to have this option and possibly something more users could use.

**Comment by nomiddlename** [comment]
I'm happy to revisit this, if it turns out that other users also have this requirement.

**Comment by OliverNChalk** [comment]
I am trying to achieve the same end result. The approach of using tokens is not functionally equivalent to using `LoggingEvent.data` because it only supports strings, right? I am now experimenting with writing a custom layout for the console but am unsure to have the console appender process multiple results like it does interpret multiple entries in the `data` array.

```
        Log4js.addLayout("custom-console", () =>
        {
            return (aLogEvent: Log4js.LoggingEvent): any =>
            {
                return [
                    aLogEvent.startTime,
                    aLogEvent.pid,
                ];
            }
        });
```

Is there a way to send multiple return values to the `console`/`stdout` appender and have it concatenate them and push it to `console`/`stdout`? The atlternative would be to have our appender return a string that has all of the concatenation done already?
