### ISSUE TITLE
Generate log file after each run

### ISSUE THREAD

**Issue by marcpre** [log4js-node/log4js-node#902]
Hello,

I am using `"log4js": "^4.3.1"`. Is there an option to create a log-file, with a timestamp, after each run of the program and not append to the same log file?

I have the following config file:

```
{
    "appenders": {
        "fileAppender": {
            "type": "file",
            "filename": "./logs/logging.log",
            "layout": {
                "type": "pattern",
                "pattern": "%d - %c:[%p]:%f:%l %m"
            }
        }
    },
    "categories": {
        "default": {
            "appenders": ["fileAppender"],
            "level": "info",
            "enableCallStack": true
        }
    }
}
```
I appreciate your replies!

**Comment by nomiddlename** [comment]
Take a look at the [node.js file flags](https://log4js-node.github.io/log4js-node/dateFile.html), which you can pass to the file appender in the `flags` option. Sounds like you want to use `flags: 'w'` (the default is `a` - append).

If you want to include a timestamp in the filename, then you probably want to use the [dateFile appender](https://log4js-node.github.io/log4js-node/dateFile.html) with the `alwaysIncludePattern: true` option. Or just use a config object and set the file name programatically when you start up.

**Comment by marcpre** [comment]
@nomiddlename Thx for your reply! I tried the following and it currently works:

```
{
    "appenders": {
        "fileAppender": {
            "type": "dateFile",
            "filename": "./logs/t04_logging.log",
            "layout": {
                "type": "pattern",
                "pattern": "%d - %c:[%p]: %m"
            },
            "flags": "w",
            "pattern": ".yyyy-MM-dd-hh-mm-ss", 
            "compress": true,
            "alwaysIncludePattern": true
        }
    },
    "categories": {
        "default": {
            "appenders": ["fileAppender"],
            "level": "info"
        }
    }
}
```

I still would like to add that after each run only the last three log files should be kept.

Any suggestions how to do this? I only found `compressed` within the documentation.

**Comment by nomiddlename** [comment]
Try adding the `numToKeep: 3` option to the date file appender config.

**Comment by marcpre** [comment]
Thx!

When running this config:

```
{
    "appenders": {
        "fileAppender": {
            "type": "dateFile",
            "filename": "./logs/t04_logging.log",
            "layout": {
                "type": "pattern",
                "pattern": "%d - %c:[%p]: %m"
            },
            "flags": "w",
            "pattern": ".yyyy-MM-dd-hh-mm-ss", 
            "compress": true,
            "alwaysIncludePattern": true,
            "numToKeep": 3
        }
    },
    "categories": {
        "default": {
            "appenders": ["fileAppender"],
            "level": "info"
        }
    }
}
```

With this code:

```
// require log4js
const log4js = require('log4js');

// Logger configuration
log4js.configure("./config/t06_log4js-config.json");

const logger = log4js.getLogger();

logger.level = 'info';
logger.info('Beginning program execution...');

// Log a message
function sleep(ms) {
    return new Promise(resolve => {
        setTimeout(resolve, ms)
    })
}

async function main() {
    for (let index = 0; index < 10; index++) {

        await sleep(1000)
        logger.trace('Trace, log4js!');
        logger.debug('Debug, log4js!');
        logger.info('Hello, log4js!');
        logger.warn('Heads up, log4js!');
        logger.error('Danger, log4js!');
        logger.fatal('Fatal, log4js!');
    }
}

main()
```
I get:

![log-output](https://i.imgur.com/jKQ67Ba.png)

The Problem is that I get 1 file for each second, BUT not 1 file for each run.

Any suggestion what I am doing wrong?

**Comment by hapvlz** [comment]
Anyone have an idea for above? im having the same question.

**Comment by phamnuhuyentrang** [comment]
You have this because of your dateFile pattern. It means that you will have a new log file per second. If you changed to yyyy-mm-dd it will renew your log per day.
