### ISSUE TITLE
component level filter

### ISSUE THREAD

**Issue by AartiJ** [log4js-node/log4js-node#903]
Hello,
     I have requirement that I need to show only certain level messages from few components. 
For ex I have component called wrapper, so all the files inside that component should only show log messages for warn and above level. 
I tried below for one of the file inside that package which worked fine. But I want to do same for all the files inside that folder. Do I need to mention each file like that or is there some other better way?
How can I achieve this? Please help
```javascript
const NDC = new(require('../lib/NDC'));

var exports = module.exports = {
    "appenders": {
        "out": {
            "type": "stdout",
            "layout": {
                "type": "pattern",
                "pattern": "%[%d{yyyy-MM-dd hh:mm:ss.SSS} [%p] [%c] [NDC: %x{specName}] %m%n%]",
                "tokens": {
                    "specName" : function() { return NDC.printStack(); }
                }
            }
        },
        "report": {
            "type": "ace-base-testlib/lib/appenders/AllureAppender",
            "layout": {
                "type": "pattern",
                "pattern": "%d{yyyy-MM-dd hh:mm:ss.SSS} %p [%c] [NDC: %x{specName}] %m%n",
                "tokens": {
                    "specName" : function() { return NDC.printStack(); }
                }
            }
        }},
    "categories": {
        "default": { "appenders": ["out","report"], "level": "INFO"},
        'lib/swagger/wrapper/workspaces': {"appenders": ["out","report"], "level": "WARN"}
    }
};
```

**Comment by nomiddlename** [comment]
Log4js does support a category hierarchy that inherits appenders and log levels, but it uses dots as separators. So your category above would look like this `lib.swagger.wrapper.workspaces` to use it. Then you could define appenders at the `lib.swagger.wrapper` level and any categories below it would inherit the values. You would refer to the categories in your code like this: `log4js.getLogger('lib.swagger.wrapper.workspaces.thingA`)`. Does that help?

**Comment by AartiJ** [comment]
Yes, thank you very much that helps. Closing the issue.
