### ISSUE TITLE
Log to syslog

### ISSUE THREAD

**Issue by thernstig** [log4js-node/log4js-node#905]
I've been searching extensively without an answer, so I am unsure if this is a valid feature request or more of a "how do I do this", but here goes.

I want to log to the syslog e.g. /var/log/messages via an appender, but no default appender seems to allow this. Is there no proper (default) way to do this?

**Comment by nomiddlename** [comment]
You're right, there is no core appender that does this. I found a couple of syslog appenders that were written by third parties: [log4js-syslog-appender](https://www.npmjs.com/package/log4js-syslog-appender) and [log4js-qradar-syslog-appender](https://www.npmjs.com/package/log4js-qradar-syslog-appender). The first one advises you to use much better logging libraries, which seems a bit rude (although probably accurate) - I must have done something to annoy that person :) The second is mainly for an IBM product, but does say it works with the normal syslog. Are they not suitable for your problem?

**Comment by thernstig** [comment]
It's just that the first one is unmaintained and the second one has 435 weekly downloads, so for me they are too small to incorporate as I prefer common libs. I assume I can implement my own appender that calls `logger` http://man7.org/linux/man-pages/man1/logger.1.html but that seems quite inefficient.

**Comment by nomiddlename** [comment]
Spawning an external process every time you want to log something will be very inefficient. If you're going to write your own appender, then you can probably make use of the [syslog2 library](https://www.npmjs.com/package/syslog2) which exposes a stream-based interface to syslog.

**Comment by thernstig** [comment]
@nomiddlename thank you for your replies to this. That one would work as well, but it is also "highly" umaintained. I'll have to think a bit, thanks!

**Comment by thernstig** [comment]
@lamweili is this something you'd be interested in implementing :D?

**Comment by lamweili** [comment]
@thernstig If I have time to spare. I'm a little stretched. 🥵
So I can't really commit. But if anyone has the time, PRs are welcomed!
