### ISSUE TITLE
Create 1 file for each execution of the script

### ISSUE THREAD

**Issue by marcpre** [log4js-node/log4js-node#908]
Hello,

I am using `"log4js": "^4.3.1"` and want to create 1 log file with a timestamp for each program run.

I tried the following:

When running this config:

```
{
    "appenders": {
        "fileAppender": {
            "type": "dateFile",
            "filename": "./logs/t04_logging.log",
            "layout": {
                "type": "pattern",
                "pattern": "%d - %c:[%p]: %m"
            },
            "flags": "w",
            "pattern": ".yyyy-MM-dd-hh-mm-ss", 
            "compress": true,
            "alwaysIncludePattern": true,
            "numToKeep": 3
        }
    },
    "categories": {
        "default": {
            "appenders": ["fileAppender"],
            "level": "info"
        }
    }
}
```

With this code:

```
// require log4js
const log4js = require('log4js');

// Logger configuration
log4js.configure("./config/t06_log4js-config.json");

const logger = log4js.getLogger();

logger.level = 'info';
logger.info('Beginning program execution...');

// Log a message
function sleep(ms) {
    return new Promise(resolve => {
        setTimeout(resolve, ms)
    })
}

async function main() {
    for (let index = 0; index < 10; index++) {

        await sleep(1000)
        logger.trace('Trace, log4js!');
        logger.debug('Debug, log4js!');
        logger.info('Hello, log4js!');
        logger.warn('Heads up, log4js!');
        logger.error('Danger, log4js!');
        logger.fatal('Fatal, log4js!');
    }
}

main()
```
I get:

![log-output](https://i.imgur.com/jKQ67Ba.png)

The Problem is that I get 1 file for each second, BUT not 1 file for each run.

Any suggestion what I am doing wrong?

**Comment by nomiddlename** [comment]
That's what the `dateFile` appender is meant to do, it rolls files based on the current time (main use case is for breaking your log files up into daily chunks). What you probably want to do is just generate your filename at the start of your application. Load your JSON config into an object and just set the value of the filename to something like `"./logs/t04_logging.log"+(new Date())`. You'll probably want to do some formatting of the date (take a look at the [date_format library](https://github.com/nomiddlename/date-format) - it's bundled as a dependency of log4js, so you've already got it in node_modules somewhere)

**Comment by nomiddlename** [comment]
I'm going to close this issue, feel free to re-open if you still have a problem.
