### ISSUE TITLE
Log4js-node does not write to file

### ISSUE THREAD

**Issue by serkanersanliuk** [log4js-node/log4js-node#912]
Hi, my code is as below : 

var log4js = require('log4js');

let config = log4js.configure({
        appenders: {
            logging: { type: 'file', filename:'/tmp/error.log', maxLogSize: 10485760, backups: 3, compress: true }
        },
        categories: { default: { appenders: [ 'logging' ], level: 'debug'}}
    });

    global.logger = log4js.getLogger('logging')

    global.logger.debug('LOGGING ACTIVATED')
    console.log(global.logger)

**The output in console is :** 

2019-07-05T09:42:04.374459800Z Logger { category: 'logging', context: {} }

**No Output in file :**

$ more /tmp/error.log
/tmp/error.log (END)

**Additional Notes:**
- I used global to keep the logger object to be used in all project. However, for the guys curious about if the problem is with the 'global', it is not ! Same with or without it..
- chmod 777 given to both /tmp folder and error.log file
- it works perfect when i turn the appender type to console

Thanks in advance

**Comment by rommni** [comment]
@serkanersanliuk not sure if it is the problem but i think there is an error on 
``` global.logger = log4js.getLogger('logging')```
Because the parameter of getLogger is supposed to be the category and not the appender, so it may work better with getLogger('default') or with getLogger(), like 'default' is the default parameter

**Comment by nomiddlename** [comment]
I just tried out your code and it worked fine for me. I'm on mac os 10.14.5, latest log4js (4.4.0), node v10.15.0.

**Comment by serkanersanli** [comment]
Figured out it is the docker issue on my mac. Thanks, it is working now

**Comment by serkanersanliuk** [comment]
I figured out the issue. The app was working within a docker container and it was creating log docker instance’s tmp directory rather than root /tmp. So once realised, linked mac’s /tmp in the docker-compose file and it was fixed. Thanks for help.
