### ISSUE TITLE
Module not found: Error: Can't resolve 'cluster'

### ISSUE THREAD

**Issue by uedaeita** [log4js-node/log4js-node#920]
I use webpack and I get the error message below:
```
ERROR in ./node_modules/log4js/lib/clustering.js
Module not found: Error: Can't resolve 'cluster' in '/path/to/node_modules/log4js/lib'
 @ ./node_modules/log4js/lib/clustering.js 1:16-34
 @ ./node_modules/log4js/lib/log4js.js
```

Has anyone else encountered this issue, and know how to resolve it?

**Comment by nomiddlename** [comment]
This looks like the same issue as in #928  - NUXT uses web pack as well.

**Comment by nomiddlename** [comment]
As a workaround, try downgrading log4js to version 3.0.6?

**Comment by mnrn** [comment]
I have the same problem in vue-cli.
Tried downgrading log4js to version 3.0.6, but seems that hasn't been resolved.

**Comment by nomiddlename** [comment]
I've pushed a fix for this to npm in log4js@5.0.0 - it may still not work, but at least you'll get a different error.

**Comment by nomiddlename** [comment]
I've got confirmation that logging works in NUXT with log4js@5.0.0 - there are warnings when bundling/compiling but it does work.

**Comment by alokjx** [comment]
我使用webpack也是这样的问题，怎么解决

**Comment by nomiddlename** [comment]
Closing this one because I know it works in some circumstances. Feel free to re-open if you still have problems.

**Comment by bryanSME** [comment]
broken in 6.1

**Comment by Mubashir-rehma** [comment]
Module not found: Error: Can't resolve 'cluster' in 'E:\Test\client\node_modules\shortid\lib\util'

I still find this error while running in react js

**Comment by peteriman** [comment]
@Mubashir-rehma, are you sure this is from `log4js`? It seems like from `shortid`. 

---

Also, do you have the full logs? For example:
```
 WARNING  Compiled with 2 warnings                                                                                                                                                                                              2:15:09 PM  
 warning  in ./node_modules/log4js/lib/appenders/index.js  
Critical dependency: the request of a dependency is an expression  
 warning  in ./node_modules/log4js/lib/clustering.js  
Module not found: Error: Can't resolve 'cluster' in '/.../node_modules/log4js/lib'  
```

In the above case, it's a warning and not an error.
A bundle should still be produced.

**Comment by ARiyou2000** [comment]
## The error occurs because there has been a breaking change in Webpack V5.
```js
{
  "dependencies": {},
  "devDependencies": {},

  // 👇️ add this to package.json 👇️
  "browser": {
    "cluster": false
  }
}
```

[More Info](https://bobbyhadz.com/blog/module-not-found-error-cant-resolve-tls)
