### ISSUE TITLE
Trace log is not stored in file

### ISSUE THREAD

**Issue by didaquis** [log4js-node/log4js-node#924]
Hi.

I can't log on a file the logs of level "trace". The others logs are working fine. This is my configuration: 
```
log4js.configure({
    appenders: {
        out:{ type: 'stdout' },
        trace: { type: 'file', filename: 'logs/application_trace.log', maxLogSize: 204800, backups: 8, keepFileExt: true },
        debug: { type: 'file', filename: 'logs/application_debug.log', maxLogSize: 204800, backups: 3, keepFileExt: true },
        info: { type: 'file', filename: 'logs/application.log', maxLogSize: 204800, backups: 8, keepFileExt: true },
        error: { type: 'file', filename: 'logs/application_error.log', maxLogSize: 204800, backups: 3, keepFileExt: true },
        trace_filter: { type: 'logLevelFilter', appender: 'trace', level: 'trace', maxLevel: 'trace' },
        debug_filter: { type: 'logLevelFilter', appender: 'debug', level: 'debug', maxLevel: 'debug' },
        info_filter: { type:'logLevelFilter', appender: 'info', level: 'info' },
        error_filter: { type:'logLevelFilter', appender: 'error', level: 'error' }
    },
    categories: {
        default: { appenders: [ 'trace_filter', 'debug_filter', 'info_filter', 'error_filter', 'out'], level: 'all' },
    }
});
```

When I log messages, the files "application_debug.log", "application.log" and "application_error.log" are created automatically, but file "application_trace.log" is not created and trace logs are logged only on the console. 

What I'm doing wrong? Am I understanding the documentation well or it's a bug?

I'm using log4js version 3.0.6

**Comment by didaquis** [comment]
WOW! Really weird, I delete the directory "logs" and restart my application and the issue is fixed now. Maybe some application was blocking the directory.... I'm not sure. 

Anyway, it's fixed now!

**Comment by didaquis** [comment]
Reopened! Seems like sometimes the file "application_trace.log" is not created. Seems like a random behavior.

**Comment by nomiddlename** [comment]
What operating system are you running this on? What version of node?

**Comment by didaquis** [comment]
Running on Windows 10 Professional and Node 8.16.1 LTS

**Comment by nomiddlename** [comment]
Log4js @ 5.2.2 contained a few fixes for files being locked/busy in windows. Could you give that a try and see if it fixes your problem, please?

**Comment by didaquis** [comment]
I'm out of work now. Give me some days to update and test. Thanks

**Comment by didaquis** [comment]
I updated Log4js on my codebase. I will test this issue over next days. Meanwhile, I will close this ticket. If necessary, I will reopen it.
