### ISSUE TITLE
cluster causes error in NUXT

### ISSUE THREAD

**Issue by nomiddlename** [log4js-node/log4js-node#928]
The node.js core `cluster` module does not exist in the NUXT environment, and causes an error in log4js even if `disableClustering: true` is set (the `require("cluster")` call is what generates the error). To fix it we need a try/catch around the require, and for the code to do something sensible in this case.

**Comment by nomiddlename** [comment]
I've pushed a fix for this to npm in log4js@5.0.0 - it may still not work, but at least you'll get a different error.

**Comment by nomiddlename** [comment]
Got a confirmation that logging works in NUXT - there are some warnings during compilation/bundling, but it works.

**Comment by ARiyou2000** [comment]
## The error occurs because there has been a breaking change in Webpack V5.
```js
{
  "dependencies": {},
  "devDependencies": {},

  // 👇️ add this to package.json 👇️
  "browser": {
    "cluster": false
  }
}
```

[More Info](https://bobbyhadz.com/blog/module-not-found-error-cant-resolve-tls)
