### ISSUE TITLE
If save the log as a file, a disk failure will cause the node to crash.

### ISSUE THREAD

**Issue by liujun-dlink** [log4js-node/log4js-node#929]
If save the log as a file, a disk failure will cause the node to crash. It is recommended that add an exception capture when write to log file.

**Comment by peteriman** [comment]
The appenders cause the Node.js process to exit as there was no listener for its `'error'` event.
Fixed in #529, #1089, #1097 of `log4js@6.4.0` by adding an `'error'` listener to `EventEmitter`.

> If an `EventEmitter` does not have at least one listener registered for the `'error'` event, and an `'error'` event is emitted, the error is thrown, a stack trace is printed, and the Node.js process exits.
> _(src: https://nodejs.org/docs/latest/api/events.html#error-events)_
