### ISSUE TITLE
Windows log rolling broken

### ISSUE THREAD

**Issue by gregoryjgarcia0** [log4js-node/log4js-node#932]
Previously we had been using Log4js 0.6.14 with Node 8.11 (I didn't realize it was that old until this came up) and experiencing this issue where it would roll logs until it hit max backups, then continually write to the log file until it used all the disk space. We are using Node 8.11 and have tried Log4js 4.5.1 and 5.0.0. 4.5.1 appears to present the issue, but 5.0.0 will hit max backups, generate one additional file, and stop writing. 

   appenders: {
		out: {
		"type": "console",
			layout: {
				type: 'pattern',
				pattern: "%d{DATE} %[[%p]%]- %m%n"
			}
		},
		file: {
			"type": "file",
			layout: {
				type: 'pattern',
				pattern: "%d{DATE} %[[%p]%] - %m%n"
		},
			"filename": "logs/server_log.txt",
			"maxLogSize": 10485760,
			"backups": "20"
		}
	},
		categories: {
		default: {appenders: ['file', 'out'], level: 'info'}}

**Comment by nomiddlename** [comment]
Could you give log4js@5.1.0 a try, please?

**Comment by nomiddlename** [comment]
I think this is a file-locking problem. I couldn't reproduce the issue in log4js@5.1.0 until I tried viewing the log files as they were being written. Do you have anti-virus or something running on your log directory? The log-rolling code assumes it is the only thing accessing those files and doesn't handle errors very well if it can't access them.

**Comment by nomiddlename** [comment]
You shouldn't have to do that, no. Under the hood we use [graceful-fs](https://github.com/isaacs/node-graceful-fs) which is supposed to handle things like temporary file locks for us, but it may be doing something weird in windows. I'll see if I can come up with a way to reliably reproduce the issue (I only managed to make it happen once) on my windows vm.

**Comment by nomiddlename** [comment]
Also, what version of windows are you using?

**Comment by gregoryjgarcia0** [comment]
This is Node 8.11 on Win2012R2.

**Comment by nomiddlename** [comment]
log4js@5.2.0 includes a fix for file rotation when the files are busy/locked.

**Comment by gregoryjgarcia0** [comment]
Confirmed fixed. I've been running 5.2.2 for a week now and it appears to be behaving itself. Thanks!

**Comment by nomiddlename** [comment]
Great news, thanks for confirming.
