### ISSUE TITLE
line number, function name and file path

### ISSUE THREAD

**Issue by abdolrhman** [log4js-node/log4js-node#935]
a great package indeed,
but i need to know if i can log the line number and function name and even the file path ??

also is it possible to log every level in a file
ex: filename.debug , filename.info ,, etc

thanks ^^

**Comment by nomiddlename** [comment]
Line numbers, etc can be logged using the [pattern layout](https://log4js-node.github.io/log4js-node/layouts.html).

Logging different levels into different files can be done using the [logLevelFilter](https://log4js-node.github.io/log4js-node/logLevelFilter.html).

**Comment by abdolrhman** [comment]
@nomiddlename thanks buddy for ur replay,

can i choose to make the file name today's date ?
also can i choose in the Date Rolling File Appender, that each 3hours create a new file ?

thank you :)

**Comment by nomiddlename** [comment]
The date file appender can't roll files every 3 hours, sorry. It can do every hour.

**Comment by abdolrhman** [comment]
hey buddy, 
thanks for ur reponse,

can i build two appenders and choose one from these two ,
i mean i have made two appenders one log in console the other log in file, but what ever i choose from both, both actions fire (pushing in file, pushing in console).

```
log4js.configure({
  appenders: {
    console: {
      type: 'console',
      level: 'info'
    },
    everything: {
      type: 'dateFile',
      filename: 'cp-logs.log',
      pattern: '.yyyy-MM-dd-hh',
      compress: true
    }
  },
  categories: {
    default: { appenders: ['everything', 'console'], level: 'debug' }
  }
});

log4js.getLogger('everything').info('hello');
```

this result firing the log in file and in console, so how to make one for ex: console one for file like this
```
log4js.getLogger('file').info('hello'); // this only fires in file
log4js.getLogger('console').info('hello'); //this only fires in console
```

**Comment by nomiddlename** [comment]
You need to use the categories.
```javascript
log4js.configure({
  appenders: { ... same as above },
  categories: {
    default: { appenders: [ 'everything','console'], level: 'debug' },
    file: { appenders: ['everything'], level: 'debug' },
    console: { appenders: [ 'console' ], level: 'debug' }
  }
});
log4js.getLogger("file").info("hello"); // goes to file
log4js.getLogger("console").info("hello"); // goes to console
log4js.getLogger("something else").info("hello"); // goes to "default" = file + console
```

**Comment by abdolrhman** [comment]
@nomiddlename thanks bro for all the help apperciate it,
regards if i want to use the log4js in all of the files instead of importing it with diffrent require levels,
can i use it in middleware or something in the main index file, so all files can use it without importing the file that contain the log4js configuration ?

thanks again ^^

**Comment by nomiddlename** [comment]
You only need to call `log4js.configure` once in your application, ideally in your main code at startup. You can then require log4js in any other module and it will use the configuration you've already specified.
