### ISSUE TITLE
Incorrect timestamp with ISO8601_WITH_TZ_OFFSET

### ISSUE THREAD

**Issue by danielwu68** [log4js-node/log4js-node#940]
With the log4js pattern:

pattern: "ISO8601_WITH_TZ_OFFSET %[%d{ISO8601_WITH_TZ_OFFSET}] ISO8601 %[%d{ISO8601}] %p %c -%] %m%n"

And testing code:

datelogger = require('log4js').getLogger('date-test');
datelogger.info("now is ", moment().utc());

log4js produce the following output:

ISO8601_WITH_TZ_OFFSET: [2019-09-09T_18_:46:36.673-0700] ISO8601: [2019-09-09T_11_:46:36.673] INFO date-test - now is  moment.utc("2019-09-09T_18_:46:36.672+00:00")

The value for ISO8601_WITH_TZ_OFFSET supposed to be 2019-09-09T**11**:46:36.673-0700 according to ISO8601 - see https://en.wikipedia.org/wiki/ISO_8601

**Comment by nomiddlename** [comment]
Yep, looks like you're right. UTC = local time - time zone offset, so in above example 18:46 = 11:46 - (-0700). I'll raise an issue in the date-format library.

**Comment by nomiddlename** [comment]
A fix for this was included in log4js@6.0.0

**Comment by nomiddlename** [comment]
Going to close this one, please open a new issue if you feel the timestamp issue has not been resolved.
