### ISSUE TITLE
Log print

### ISSUE THREAD

**Issue by pfzz** [log4js-node/log4js-node#945]
All logs are printed to debug folde 
appenders: {
        out: { type: 'stdout' },
        default: { type: 'dateFile', filename: './logs/defualt/d', pattern: "-yyyy-MM-dd.log", alwaysIncludePattern: true, },
        info: { type: 'dateFile', filename: './logs/info/i', pattern: "-yyyy-MM-dd.log", alwaysIncludePattern: true, },
        error: { type: 'dateFile', filename: './logs/error/e', pattern: "-yyyy-MM-dd.log", alwaysIncludePattern: true, }
    },r?

**Comment by pfzz** [comment]
[2019-09-20T17:13:30.354] [INFO] (^_^) - aa
[2019-09-20T17:13:30.357] [ERROR] (*>﹏<*) - aa
[2019-09-20T17:13:30.364] [DEBUG] (✪ ω ✪.) - aa

**Comment by nomiddlename** [comment]
You haven't provided your full log4js config, or a description of what you expect to happen, so I'm going to guess that you want different log levels to go to different files. Take a look at the [logLevelFilter](https://log4js-node.github.io/log4js-node/logLevelFilter.html) documentation, it may help.

**Comment by nomiddlename** [comment]
Closing this one because I didn't get any more information. Hope you managed to solve your problem.
