### ISSUE TITLE
logging to memory and then dumping to file at once (sync)

### ISSUE THREAD

**Issue by moda20** [log4js-node/log4js-node#946]
hey !
How can I dump to a memory son object in a map structure and then use the key to dump the memory log to file at will.

scenario : 

creating data trace, logging it to memory, only persisting it to file when error is detected in the data manipulation by some method or class.

**Comment by nomiddlename** [comment]
You could use a logger's context (see the `logger.addContext` function in the [api docs](https://log4js-node.github.io/log4js-node/api.html)) to build up your memory log, and then just log an error when you get an error - the context will be available in the error. You'll need to use the pattern layout (or a custom layout of your own) to see the context in the logs though, it won't be shown by default.

**Comment by nomiddlename** [comment]
I'm going to close this one, because there's no log4js issue to fix. Hope you managed to come up with a solution.
