### ISSUE TITLE
How to start server in tcp-server

### ISSUE THREAD

**Issue by JumpAttacker** [log4js-node/log4js-node#947]
Hey, im trying to use tcp-server, but when i running my code its not going to infinity cycl (like it shoude do server)

im using code from example
```
log4js.configure({
  appenders: {
    file: { type: 'file', filename: 'all-the-logs.log' },
    server: { type: 'tcp-server', host: '0.0.0.0' }
  },
  categories: {
    default: { appenders: ['file'], level: 'info' }
  }
});
```

also I used search and found dat code
```
log4js.configure({
  appenders: {
    out: { type: 'stdout' },
    file: { type: 'file', filename: 'some-logs.log' }
  },
  categories: {
    default: { appenders: ['file', 'out'], level: 'info' }
  },
  listen: {
    host: '192.168.1.46',
    port: 1234
  }
});
```

but its not working too

How to run dat server?

**Comment by JumpAttacker** [comment]
nvm, got it. Its working, but in background

**Comment by jastisriradheshyam** [comment]
hey how is it working in background and how did you verified it

> nvm, got it. Its working, but in background

**Comment by JumpAttacker** [comment]
> hey how is it working in background and how did you verified it
> 
> > nvm, got it. Its working, but in background

hey, just try to log something and you will see, that its working
