### ISSUE TITLE
Join slack room link not working

### ISSUE THREAD

**Issue by santosh-hegde** [log4js-node/log4js-node#950]
I would like to contribute here. But when I tried to join the slack room by hitting the link
https://join.slack.com/t/log4js-node/shared_invite/enQtMjk5OTcxODMwNDA1LTk5ZTA0YjcwNWRiYmFkNGQyZTkyZTYzYTFiYTE2NTRhNzFmNmY3OTdjZTY3MWM3M2RlMGQxN2ZlMmY4ZDFmZWY,
It says link expired

**Comment by nomiddlename** [comment]
I've updated the README with a new link. Give this a go: https://join.slack.com/t/log4js-node/shared_invite/enQtNzkyMTIzODgxMDQ2LWZmZGEzOGQzN2MzMmE3YWNiNDVmZDY3MjM2MTM3ZTlhOTg0ODkyODc3ODc5OWQ3MWNmMjU1M2U4ZmUzNTViNzI

**Comment by santosh-hegde** [comment]
That works!!

**Comment by peteriman** [comment]
The link has expired once again.

**Comment by nomiddlename** [comment]
@peteriman thanks for letting me know - I've replaced it with a link that should not expire (now that slack supports this)
