### ISSUE TITLE
logger.log('msg') does not print the message

### ISSUE THREAD

**Issue by AartiJ** [log4js-node/log4js-node#952]
Hello,
In my framework, I have used logger.log() several places with the message passing as parameter. But I do not see message coming neither to the report nor to the console. 
Please help.
Test
 it('Verify log method', function () {
        logger.log('this is to test log');
 });

Code:
log(...params) {
        this.logger.log.apply(this.logger, params);
 }

Output
✓ Verify log method
2019-10-10 13:18:59.655 [INFO] [ace-log.test.Log4JSTest] [NDC: ] 

I am expecting message passed in [NDC: ]

Thanks,

**Comment by nomiddlename** [comment]
Closing this because this isn't a log4js issue. Try `this.logger.log(...params)` instead of using apply. Or if you want to use apply anyway use `this.logger.log.apply(this.logger, [...params])`.
