### ISSUE TITLE
enableCallStack: true - Showing deprecation warning on console

### ISSUE THREAD

**Issue by leonardootoni** [log4js-node/log4js-node#957]
I am using enableCallStack: true in my appender configuration in order to log out filename information in all my logs. During the app staturtp, when I enabled this config, a message is printed out on console:

> (node:28310) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

My Appender config: 

> 

     appenders: {
        console: {
          type: 'console',
          layout: { type: 'pattern', pattern: '%[[%d] [%p] %f{1}%] %m' },
        },
      },
      categories: {
        server: {
          appenders: ['console'],
          level: LogLevel.info,
          enableCallStack: true,
        },
      },

Without `enableCallStack: true`, the warning message disappear.
I am using log4js 5.3.0 with node 12.11.1

**Comment by nomiddlename** [comment]
Hi, I'm having trouble reproducing this issue. The following code, in node v12.13.0, does not produce the deprecation warning.
```javascript
const log4js = require('../lib/log4js');

log4js.configure({
  appenders: {
    console: {
      type: 'console',
      layout: { type: 'pattern', pattern: '%[[%d] [%p] %f{1}%] %m' },
    }
  },
  categories: {
    default: {
      appenders: ['console'],
      level: 'info',
      enableCallStack: true
    }
  }
})

log4js.getLogger().info('This should not cause problems');
```

A quick search through the log4js code shows that we're not using Buffer directly anywhere, so perhaps this is coming from a dependency? `npm outdated` will list any dependencies that need updating.

**Comment by leonardootoni** [comment]
@nomiddlename I am also using node 12.13.0 in a Linux/Ubuntu 19.04 environment.
The log4js version is 5.3.0.
My environment is set with Typescript and I am using import, not commons js (I don't know if this can affect a different behaviour).
Anyways, turning on "enableCallStack" to true, causes the reported output. Maybe the problem is present in a dependency...

Let me know if I can provide more details to reproduce this issue.

**Comment by nomiddlename** [comment]
Perhaps typescript is converting something to use Buffer? Could you search through the generated javascript to see where the Buffer statement is used? That might give us a clue as to what's going on.

**Comment by leonardootoni** [comment]
> Perhaps typescript is converting something to use Buffer? Could you search through the generated javascript to see where the Buffer statement is used? That might give us a clue as to what's going on.

Good point. However, there is nothing inside my ./build folder regards to Buffer. This is my tsconfig file:
{
  "compilerOptions": {
    "strict": true,
    "rootDir": "./",
    "outDir": "./build",
    "allowJs": false,
    "sourceMap": true,
    "target": "es2018",
    "lib": ["es2018"],
    "esModuleInterop": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "include": ["./src/**/*"],
  "exclude": ["node_modules"],
  "files": ["src/app/util/typings/type.d.ts"]
}

Let me know if I can help with more details.

**Comment by leonardootoni** [comment]
Just coming back to this thread to enforce that when using enableCallStack = true, for some reason, just after the first call to .info() fires the message:

```
(node:5965) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

If I disable enableCallStack from my appenders, everything runs fine. I am using this property just because I need to print out the file name along with info or debug messages.
Does anyone have any idea about what can be causing this?
this is my log4js config:

```
private static configureAppender(): void {
    configure({
      appenders: {
        fileAppender: {
          type: 'file',
          filename: AppLogger.logFileName,
          keepFileExt: true,
          maxLogSize: 30000,
          backups: 5,
          layout: { type: 'pattern', pattern: '%[[%d] [%p] %f{1}%] %m' },
        },
        console: {
          type: 'console',
          layout: { type: 'pattern', pattern: '%[[%d] [%p] %f{1}%] %m' },
        },
      },
      categories: {
        default: {
          appenders: ['console', 'fileAppender'],
          level: LogLevel.debug,
          enableCallStack: true,
        },
        server: {
          appenders: ['console', 'fileAppender'],
          level: LogLevel.info,
          enableCallStack: true,
        },
        production: { appenders: ['fileAppender'], level: LogLevel.error },
      },
    });
  }
```

**Comment by leonardootoni** [comment]
Forget about it. I was using version 5.3.0. After upgrade to 6.1.0 the issue doesn't happen anymore.
