### ISSUE TITLE
dateFile appender cause crash

### ISSUE THREAD

**Issue by laowangnj** [log4js-node/log4js-node#958]
if log file named “x.log.2019-10-02” and there is “x.log.xxx“。
it will try to decode ”xxx“ as date，that cause exception。

**Comment by nomiddlename** [comment]
Hi - what version of log4js and node are you using?

**Comment by laowangnj** [comment]
> Hi - what version of log4js and node are you using?

node -v
v8.16.0

log4js-4.5.1

**Comment by nomiddlename** [comment]
Please try the latest version of log4js. It has fixes for this issue.
