### ISSUE TITLE
Question: (node:xxxx) logs

### ISSUE THREAD

**Issue by thernstig** [log4js-node/log4js-node#961]
Hi,

With node version 10.13.0 I sometimes see output such as:

`(node:2532) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
`

or

`(node:2466) UnhandledPromiseRejectionWarning: some text here and then a stack trace`

Is it possible to handle this with log4js?

**Comment by nomiddlename** [comment]
If you want those messages to go to your log4js logs, then take a look at [this article](https://medium.com/@jasnell/introducing-process-warnings-in-node-v6-3096700537ee#.9yle93tm2) which describes how to use `process.on('warning', cb)`  to listen for those messages and handle them yourself.

**Comment by thernstig** [comment]
That's great, thanks! At least now people can see this issue for reference in the future :)
