### ISSUE TITLE
How to implement custom appender that is async

### ISSUE THREAD

**Issue by ScottChapman** [log4js-node/log4js-node#970]
So I am writing a custom appender, that has a few async methods (for connecting, writing data, and disconnecting.

I'm not clear on the proper way to implement this since it doesn't feel like this used callback model consistently nor does it support promises.

So in my configure method I need to connect before I return the function, and my shutdown method can't be called unless all events have been written.

Is there a good example I can use as a guide on this?

**Comment by nomiddlename** [comment]
The [tcp appender](https://github.com/log4js-node/log4js-node/blob/master/lib/appenders/tcp.js) maintains a buffer of log messages that have been sent to it before its connection is open, and sends them once it gets the open event. Hope that helps.
