### ISSUE TITLE
Inconsistent typings for shutdown function

### ISSUE THREAD

**Issue by aaron-edwards** [log4js-node/log4js-node#971]
There seems to be an inconsistent typing of the shutdown function. 

The definition file specifies the shutdown function as follows 
```typescript
export function shutdown(cb?: (error: Error) => void): void | null;
```
however the function seems to require a cb function (See https://github.com/aaron-edwards/log4js-node/blob/master/lib/log4js.js#L106 & https://github.com/aaron-edwards/log4js-node/blob/master/lib/log4js.js#L112)

**Comment by nomiddlename** [comment]
Fix published to npm in log4js@6.1.1
