### ISSUE TITLE
categories just default valid

### ISSUE THREAD

**Issue by NightBreezeCQ** [log4js-node/log4js-node#973]
![image](https://user-images.githubusercontent.com/28768888/69851297-53f5f100-12bc-11ea-8682-d7e2b53e7a6a.png)
error and debug invalid after set.

**Comment by nomiddlename** [comment]
Could you give me a bit more detail, please? What is the rest of your config? What do you mean by "error and debug invalid after set" - what happens?

**Comment by peteriman** [comment]
@CQzhangshuai Would need the full code for the `log4js.configure()`, include the `appenders` section.

**Comment by lamweili** [comment]
Closed due to extended period of inactivity.
