### ISSUE TITLE
Functionality: How do you use log4js in a package.json script for logs per node evn runtime execution 

### ISSUE THREAD

**Issue by xtianus79** [log4js-node/log4js-node#977]
debug seems to do this readily out of the box and all the other log competitors don't seem to have this functionality or it isn't apparent in the docs.  Is this something you can do with log4js-node? 

Seems like a pretty important feature

**Comment by nomiddlename** [comment]
I don't understand what you're trying to do - could you give an example, please?

**Comment by xtianus79** [comment]
@nomiddlename it's what debug does on their documentation as a first thing they explain to you.  when starting your node app your would put debug=* <<< debug all or debug=redis for debugging only redis

**Comment by nomiddlename** [comment]
Ok, I get it - you can use the `LOG4JS_CONFIG` environment variable to point to different configuration files for different environments.
