### ISSUE TITLE
pattern for reloading log4js config when config file changes

### ISSUE THREAD

**Issue by GlenBikes** [log4js-node/log4js-node#978]
I'm sure that a github issue is not the appropriate place for this, so I apologize, but I can't find any other place to ask the question.

I know that reloading on config file changes has been removed from log4js, but I am trying to do it myself and I am struggling to figure out how to do this without getting errors. Also, searching github repos for log4js and chokidar or watchr gives no results which makes me think this is not something many people are trying to do?

Is there a sample somewhere that could be added to the documentation to show how to do this? I am trying to use chokidar to do this but no matter what I try I end up with errors due to write operations occurring after the shutdown occurs.

**Comment by nomiddlename** [comment]
Could you post some sample code for what you're trying to do, please? That might help us work out a solution, but basically what you should do is call `log4js.shutdown` in your chokidar event handler, and then call `log4js.configure` in the callback from `log4js.shutdown`. I haven't used chokidar or watchr, it wasn't something we ever ended up needing in our applications (hence why the feature was removed), so I'm just guessing here.

**Comment by peteriman** [comment]
Hi @nomiddlename ,

Can we call `log4js.configure`, without calling `log4js.shutdown`, to re-configure?

**Comment by nomiddlename** [comment]
The only problem with calling configure without shutdown is that it may leave resources open (file handles, network connections, etc). If you're just logging to console or stdout, or your appender creates a new connection for every log message, then you should be ok to skip shutdown.

**Comment by nomiddlename** [comment]
I'm going to close this, because there's no issue to fix.

**Comment by OmgImAlexis** [comment]
@nomiddlename if we're reloading for example to change pattern is there any issue with just calling configure? Also what happens while the logger is shutdown, is there a queue or anything?

**Comment by peteriman** [comment]
@OmgImAlexis From `log4js@6.4.0` onwards, calling `log4js.configure()` properly close all existing file handlers and re-initializes log4js using the latest provided configuration. Read more in #1105 and #1113.

**Comment by OmgImAlexis** [comment]
Thank you so so much @peteriman :pray:
