### ISSUE TITLE
this.log is not a function

### ISSUE THREAD

**Issue by williamdes** [log4js-node/log4js-node#979]
Hi, 
I have this error on my production environment and can not find out when and why it occurs, can you please help me fix it?
Some Googling hints it could be a finished callback

I use typescript and ts-node (or node-ts🤔) to run the code

```
TypeError: this.log is not a function
  File "/wwwroot/project/node_modules/log4js/lib/logger.js", line 124, col 10, in Logger.(anonymous function)
    this.log(level, ...args);
  File "internal/process/next_tick.js", line 68, col 7, in process._tickCallback
```

**Comment by nomiddlename** [comment]
I'm guessing that this is because you're using something like `logger.info` directly as a callback without binding it to an instance.
e.g. `someAsyncOperation(logger.info)` - hoping that when it finishes the result will be logged. But the problem is that the info function then no longer has a reference to the logger instance. You want to do something like this: `someAsyncOperation(logger.info.bind(logger))`.

If you post some sample code I can maybe help a bit more.

**Comment by williamdes** [comment]
@nomiddlename Thank you, indeed I had `.catch(logger.error);` in my codebase

**Comment by williamdes** [comment]
I am closing this issue, but if someone wants to document the issue or add some code please comment it here

Thank you for your help :)

**Comment by Hr-new** [comment]
Hi,
I have this error when i write test case using waitFor() or await findByRole() for find alert message when value is blank
`    const alert = await findByRole('alert')
    screen.debug(alert)`
    or
    `    const alert = await waitFor(() => getByRole('alert'))
    screen.debug(alert)`
  **Output**  
Test suite failed to run
    TypeError: this.log is not a function
      at XMLHttpRequestOverride.abort (node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts:436:12)
          <div   class="ant-form-item-explain-error"   role="alert"  >   Address is required  </div>
          here i got alert in dom but still it throw error

**Comment by lamweili** [comment]
@Hr-new, is this a `log4js-node` issue? Can you provide snippets of `log4js-node`?

**Comment by Hr-new** [comment]
No this is not log4js-node issue for writing test case in RTL i Set up Mock Service Worker (MSW) and tthis error is thow inside this module's file
`node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts`
when i write below code
`const alert = await findByRole('alert') screen.debug(alert)
or
const alert = await waitFor(() => getByRole('alert')) screen.debug(alert)`

**Comment by lamweili** [comment]
@Hr-new, then it's beyond the scope of `log4js-node`.
You might want to file over at https://github.com/mswjs/interceptors instead.
