### ISSUE TITLE
%m strangely also showing the date

### ISSUE THREAD

**Issue by Stylesoftware** [log4js-node/log4js-node#980]
Hope all is well and thank you for maintaining this great project.
I've not used log4js in a year or two, but my understanding was the pattern "%m" would just show the message text?
I don't wish to see the ISO date nor the debug level etc, as the timestamp comes from another source and is added to the message text long before it gets to the log.
```
      log4js.configure({
		appenders: { 
			log: { 
				type: 'file', 
				filename: settings.debug_log_filename,
				pattern: '%m',
			}
		},
		categories: { 
			default: { 
				appenders: ['log'],
				level: 'debug'
			} 
		}
	});
	
	logger = log4js.getLogger('log');
```

Gives:

`[2020-01-06T20:55:24.066] [DEBUG] log - TheMessage
`

**Comment by nomiddlename** [comment]
That's because you haven't configured the layout correctly. Take a look at [this example](https://github.com/log4js-node/log4js-node/blob/master/examples/patternLayout-tokens.js) - it's a more complicated pattern than you want, but the config is the same.

**Comment by Stylesoftware** [comment]
Apologies, I'm having difficulty finding the pattern documentation for some
reason.
Your example says:  %[%r (%x{pid}) %p %c -%] %m%n
But I'm just after the message, nothing else :/

**Comment by nomiddlename** [comment]
Your pattern layout config is correct (`%m` is what you want). The bit that's wrong is configuring the appender to use the layout. You need something like this:
```javascript
log4js.configure({
  appenders: {
    log: {
      type: 'file',
      filename: settings.debug_log_filename,
      layout: {
        type: 'pattern',
        pattern: '%m'
      }
    },
  categories: { default: { appenders: [ 'log'], level: 'debug' } }
});
```

**Comment by Stylesoftware** [comment]
Doh, thanks.
