### ISSUE TITLE
Collaborate on anylogger-log4js adapter?

### ISSUE THREAD

**Issue by Download** [log4js-node/log4js-node#981]
[`anylogger`](https://npmjs.com/package/anylogger) is a logging facade for Javascript, meant to be used by library authors, to decouple them from, but make use of, the logging framework selected by the application the library is used in.

In order to enable applications to use `anylogger` with a certain logging framework, the application author installs an adapter. For `log4js`, this adapter is:

#### Anylogger adapter for log4js

I made a simple first version of the adapter that seems to work well in my tests.

**Would you like to collaborate with me on this?**

Ideally, it would be great if you could have a look at the code and let me know if I am doing the right things in my adapter and tests. And maybe if you make new versions of `log4js`, you could test to see if the adapter still works and make the needed changes if it does not. And maybe link to the adapter from your README etc...

**Comment by nomiddlename** [comment]
Your adapter looks fine to me - although maybe consider not using single-letter variable names in your code, I found it a bit hard to read the section with just a, o, v, l. I would be happy to see a PR for the log4js documentation (in the README, and also the docs site that nobody seems to ever read) to mention anylogger and that you support log4js. However, I'm going to be a bit of a dick here and say that I barely have time to support my own library, never mind checking that I haven't broken someone else's so the responsibility for making sure the anylogger-log4js adapter works with new versions of log4js is going to have to be yours.

**Comment by Download** [comment]
Ha ha no I understand your attitude completely. For me it is just great you are aware the adapter exists. Thanks for having a look at the code!  

I will try to cook up a PR adding a note on `anylogger` with `log4js` in both the README as well as the docs. 👍

**Comment by Download** [comment]
I invited you as a collaborator, just because I think it is good to have more than one person with access to the repo, but I am not expecting anything of you, don't worry 👍

**Comment by nomiddlename** [comment]
No problem, happy to help where I can.
