### ISSUE TITLE
Consider replacing log4js-api with anylogger?

### ISSUE THREAD

**Issue by Download** [log4js-node/log4js-node#982]
Hi,

My name is Stijn de Witt and I have been developing on some logging libraries for a bunch of years. I am the author of [`picolog`](https://npmjs.com/package/picolog), later renamed to [`ulog`](https://npmjs.com/package/ulog).

Like you did with [`log4js-api`](https://www.npmjs.com/package/@log4js-node/log4js-api), I tried to come up with a mechanism that would improve interoperability and reduce coupling with the logging framework for library authors. I went a step further and tried to make a generic mechanism that would do the same thing as `log4js-api`, but across different logging frameworks. Here is what I came up with:

#### Get a logger. Any logger.

When a library author wants his library to do logging with whatever logging framework the application is using, he can use `anylogger`, like this:

*library.js*
```js
import anylogger from 'anylogger'
const log = anylogger('library')
// ...
log.info('Logging is simple!')
```

Then, when an application author decides he wants to use `log4js`, he installs the [`anylogger-log4js`](https://npmjs.com/package/anylogger-log4js) adapter along with `anylogger` and `log4js`, like this:

```sh
npm install --save anylogger log4js anylogger-log4js
```

and in his entry point, he imports the adapter:

*main.js*
```js
import 'anylogger-log4js'
```

From that point onward, all `anylogger` log calls will start to use `log4js` below the surface.

This means you could consider advising your users that are authoring libraries to use `anylogger` i.s.o. `log4js-api` and the library would not only be decoupled from specific `log4js` versions, but would even be completely decoupled from `log4js` itself, leaving the option open to use another logging library if it suits them. Also, the other way around, application users would be able to use `log4js` with any library that is logging using `anylogger`.

I would be willing to make a PR that updates the README for this project to refer library authors to `anylogger`, if you agree that's a good idea.

On a related note, I'd love for you to collaborate with me on this adapter. See #981

**Comment by nomiddlename** [comment]
I commented on #981 about updating the log4js docs, that's a good idea. If you also want to raise a PR to mention anylogger on the log4js-api page, as an alternative, that's good as well. I'm not going to retire log4js-api just yet, let's see what the library developers (if there are any - I'm not sure how many people actually use log4js-api) want to do. If they adopt anylogger, then I'm happy to get rid of it.
