### ISSUE TITLE
multiFile with daysToKeep as default (0), but files stored only the last 2 days

### ISSUE THREAD

**Issue by KonovalovaKV** [log4js-node/log4js-node#983]
version: all 5.1.x, 6.1.x

config:
`     
      type: 'multiFile',
      base: LOGS_PATH,
      pattern: 'yyyy-MM-dd',
      layout: LAYOUT,
      compress: true,
      property: 'categoryName',
      extension: '.log'
`

Sometimes files stored more than 2 days

**Comment by KonovalovaKV** [comment]
Is there any progress on the issue?

**Comment by KonovalovaKV** [comment]
This is a critical issue for me :(

**Comment by nomiddlename** [comment]
Hi - as a workaround, you can set daysToKeep to a very large number.

**Comment by KonovalovaKV** [comment]
Yes, I just got it, but the logs generally stopped working.

**Comment by nomiddlename** [comment]
What do you mean by "generally stopped working"? Did something change recently?

**Comment by KonovalovaKV** [comment]
I mean that adding the “daysToKeep: 90” parameter to my configuration breaks writing into log.

**Comment by KonovalovaKV** [comment]
Is there any news?

**Comment by KonovalovaKV** [comment]
@nomiddlename, Hi! I use last version 6.1.2. And I set daysToKeep to my configuration, but files stored only the last 2 days, sometimes 3 days. daysToKeep does not help me.

```
{
  appenders: {
    sys: {
      type: 'multiFile',
      base: path.join(LOGS_SYS),
      pattern: PATTERN,
      layout: LAYOUT,
      compress: true,
      daysToKeep: 90,
      property: 'categoryName',
      extension: '.log'
    }
  }
}
```

When I change my config to
```
{
  appenders: {
    sys: {
      type: 'multiFile',
      base: path.join(LOGS_SYS),
      pattern: PATTERN,
      layout: LAYOUT,
      compress: true,
      // daysToKeep: 90,
      property: 'categoryName',
      extension: '.log',
      alwaysIncludePattern: true
    }
  }
}
```
It seems files are being saved normally, but compress not working. All files created without compress.

You can help me?

**Comment by rnd-debug** [comment]
Old issue, but:
@KonovalovaKV as far as I understand, in your second example, files will not be compressed as no "daysToKeep" or no "maxLogSize" were defined.
For the first example, can you check with log4js@6.2.1 ?

**Comment by KonovalovaKV** [comment]
It works. Thanks!
