### ISSUE TITLE
how can we store logs into a flat file using NGX-Logger ??

### ISSUE THREAD

**Issue by ArpithaGMGowda** [log4js-node/log4js-node#987]
Hi,
we are storing a logs into a JSON Server in the format of 

  "logs": [
    {
      "message": "Warning message",
      "additional": [],
      "level": 4,
      "timestamp": "Tuesday, February 11, 2020",
      "fileName": "./src/app/test1/test1.component.ts",
      "lineNumber": "15",
      "id": 1
    },
    {
      "message": "Error message",
      "additional": [],
      "level": 5,
      "timestamp": "Tuesday, February 11, 2020",
      "fileName": "./src/app/test1/test1.component.ts",
      "lineNumber": "15",
      "id": 2
    },
}

so i want to store this things into a flat file in the format of 

2020-02-05T08:04:49|DEBUG|login.component.ts|43|Login successful 
2020-02-05T08:20:22|DEBUG|login.component.ts|133|Logout successful

**Comment by nomiddlename** [comment]
This isn't the repo for ngx-logger. You probably want to go here: https://github.com/dbfannin/ngx-logger
