### ISSUE TITLE
Log file isnt recreated if deleted for dateFile

### ISSUE THREAD

**Issue by jrj2211** [log4js-node/log4js-node#997]
I see from issue #409 a change was made to have log4js recreate the file if its been deleted or renamed, but only for the basic file appender and not DateFileAppender. 

This is an issue for me as I've created a page in my app for admins to view and delete logs. I want my logs to roll over on date and size, so I'm using the dateFile appender. If the admin deletes the current log its not recreated unless app is restarted or the time rolls over. I would suggest making it a configuration option for all appenders to turn on file watcher, instead of having that behavior only available to the basic file appender. 

Just out of curosity, does the file stream get an error if it tries to write to a file that no longer exists? Instead of using a file watcher, could it just be recreated if the stream tries to write but errors? This would allow the file to be deleted, and only recreated if a log message is trying to be written. I'm not sure how it currently works but it seems with using a file watcher it would immediately recreate the file on delete, even if theres not a pending log message to add?

If you advise on what you think would be best, I don't mind making a pull request for adding this.

**Comment by rnd-debug** [comment]
> does the file stream get an error if it tries to write to a file that no longer exists?

Nope: answer given after running a couple of tests and finding this link: [https://github.com/nodejs/help/issues/2092](url) And I am not sure that solution to issue 409 will actually solve your problem, as you are not emitting any additional signals when deleting.
