### ISSUE TITLE
how to open debug in source code

### ISSUE THREAD

**Issue by yuzhidi** [log4js-node/log4js-node#999]
Hi,
 I seem debug() in source code, how can I open it?
thx

**Comment by rnd-debug** [comment]
See **package.json** : **debug** is a third-party dependency. 
If you want to use it in your modules, it must be loaded separately. For example:
```
const messageProducer = require('debug').('smartName');
messageProducer.enabled = true;
messageProducer('this will be written to console');
```
For questions related to it, its own repo is probably more appropriate : https://github.com/visionmedia/debug
